### PR TITLE
dist/SelfLoader - Update missing build artifacts

### LINKED ISSUE #20874: dist/ modules have inconsistent build processes and missing build artifacts in the repo
Module:
```
$ find dist -mindepth 1 -maxdepth 1 -type d '!' -exec test -e '{}/Makefile.PL' ';' -print | sort
```
dist/Attribute-Handlers
dist/autouse
dist/constant
dist/Devel-SelfStubber
dist/Dumpvalue
dist/encoding-warnings
dist/Env
dist/Exporter
dist/Filter-Simple
dist/FindBin
dist/I18N-Collate
dist/I18N-LangTags
dist/Locale-Maketext
dist/Math-Complex
dist/Net-Ping
dist/SelfLoader
dist/Term-Complete
dist/Term-ReadLine
dist/Test
dist/Text-Abbrev
dist/Thread-Queue
dist/Thread-Semaphore
dist/Tie-File

Cross referencing with CPAN data we get this:

```
Attribute-Handlers               R/RJ/RJBS/Attribute-Handlers-0.99.tar.gz
autouse                          R/RJ/RJBS/autouse-1.11.tar.gz   
constant                         R/RJ/RJBS/constant-1.33.tar.gz  
Devel-SelfStubber                F/FL/FLORA/Devel-SelfStubber-1.05.tar.gz
Dumpvalue                        F/FL/FLORA/Dumpvalue-1.17.tar.gz
encoding-warnings                A/AU/AUDREYT/encoding-warnings-0.11.tar.gz
Env                              F/FL/FLORA/Env-1.04.tar.gz      
Exporter                         T/TO/TODDR/Exporter-5.77.tar.gz 
Filter-Simple                    S/SM/SMUELLER/Filter-Simple-0.91.tar.gz
FindBin                          T/TO/TODDR/FindBin-1.53.tar.gz  
I18N-Collate                     F/FL/FLORA/I18N-Collate-1.02.tar.gz
I18N-LangTags                    S/SB/SBURKE/I18N-LangTags-0.35.tar.gz
Locale-Maketext                  T/TO/TODDR/Locale-Maketext-1.32.tar.gz
Math-Complex                     Z/ZE/ZEFRAM/Math-Complex-1.59.tar.gz
Net-Ping                         R/RU/RURBAN/Net-Ping-2.75.tar.gz
SelfLoader                       S/SM/SMUELLER/SelfLoader-1.24.tar.gz
Term-Complete                    F/FL/FLORA/Term-Complete-1.402.tar.gz
Term-ReadLine                    F/FL/FLORA/Term-ReadLine-1.14.tar.gz
Test                             J/JE/JESSE/Test-1.26.tar.gz     
Text-Abbrev                      F/FL/FLORA/Text-Abbrev-1.02.tar.gz
Thread-Queue                     J/JD/JDHEDDEN/Thread-Queue-3.13.tar.gz
Thread-Semaphore                 J/JD/JDHEDDEN/Thread-Semaphore-2.13.tar.gz
Tie-File                         T/TO/TODDR/Tie-File-1.07.tar.gz
```
Everything that is not owned by FLORA (Dist::Zilla user), and AUDREYT (Module::Install) I believe has been done now. I may have missed out some ancillary files. I will go through the PR's and double check. For instance in one case there was an "examples" directory, in another the was a copy for Artistic.txt, in others there were README.md as well as README, in some there was a COPYING file, and others there was not. Not sure what we should do about that.

@Haarg has said he would pick up the Module::Install and Dist::Zilla files. 

**Description**
Many modules in dist/ lack a Makefile.PL or other build artifacts that would help roll a release.  There often is no repo for the released code, or the repo is out of date and the maintainer no longer participating in maintenance. This makes it hard to roll a release after the fact. 

To quote @haarg from 
https://github.com/Perl/perl5/pull/20867#issuecomment-1448422564

> I think this should really be done for everything in dist. As it is, many don't have a Makefile.PL or other packaging files, requiring external repositories to exist to track them. This makes patching the files a horrible pain in the ass, since you have to find the repository that contains the files you care about. But also often those repositories are long dead as the authors have moved on.

Reviewing the dists involved, many use Dist::Zilla (for instance all the dists owned by Florian Ragwitz), so they have no Makefile.pl at all in their repositories, only the version on CPAN, or in some cases they use Module::Install. 

Arguably all the dist modules should be EUMM based so their public build process mirrors that of the perl core, and all of the build product and changelog files should be in our repo so that we can roll a proper release from the materials in dist/ alone without depending on 3rd party repos, or even worse having to download the latest version from CPAN to get the files. 

**Steps to Reproduce**
NA.

**Expected behavior**
All of the build product and changelog files for dist/ modules should be in our repo so that we can roll a proper release from the materials in dist/ alone without depending on 3rd party repos, or even worse having to download the latest version from CPAN to get the files.  None of them should use Dist::Zilla, Module::Build, or Module::Install, the build tooling or the code in dist/ should be the same as the build tooling in the CPAN release.

**Perl configuration**
```
$ ./perl -Ilib -V
Summary of my perl5 (revision 5 version 37 subversion 10) configuration:
  Commit id: 1bc6b32c00831fcbf45413bd1e7d5ea44bff81ab
  Platform:
    osname=linux
    osvers=5.14.0-1057-oem
    archname=x86_64-linux-thread-multi
    uname='linux oncidium 5.14.0-1057-oem #64-ubuntu smp mon jan 23 17:02:19 utc 2023 x86_64 x86_64 x86_64 gnulinux '
    config_args='-Dusethreads -Doptimize=-g -d -Dusedevel -Dcc=ccache gcc -Dld=gcc -DDEBUGGING'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='gcc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-g'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='9.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='gcc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.31.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.31'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    DEBUGGING
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_TRACK_MEMPOOL
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Mar  1 2023 09:13:36
  %ENV:
    PERLBREW_CONFIGURE_FLAGS="-de -Dcc=ccache\ gcc -Dld=gcc"
    PERLBREW_HOME="/home/yorton/.perlbrew"
    PERLBREW_MANPATH="/home/yorton/perl5/perlbrew/perls/perl-5.34.1/man"
    PERLBREW_PATH="/home/yorton/perl5/perlbrew/bin:/home/yorton/perl5/perlbrew/perls/perl-5.34.1/bin"
    PERLBREW_PERL="perl-5.34.1"
    PERLBREW_ROOT="/home/yorton/perl5/perlbrew"
    PERLBREW_SHELLRC_VERSION="0.88"
    PERLBREW_VERSION="0.88"
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.37.10/x86_64-linux-thread-multi
    /usr/local/lib/perl5/site_perl/5.37.10
    /usr/local/lib/perl5/5.37.10/x86_64-linux-thread-multi
    /usr/local/lib/perl5/5.37.10
```

### PR DESCRIPTION
**Pull request by demerphq**
Fixes https://github.com/Perl/perl5/issues/20874 for this module

### CODE REVIEW

File: dist/SelfLoader/Makefile.PL [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+use strict;
+use ExtUtils::MakeMaker;
+WriteMakefile(
+  'NAME' => 'SelfLoader',
+  'VERSION_FROM' => 'lib/SelfLoader.pm', # finds $VERSION
+  'LICENSE' => 'perl',
+  'PREREQ_PM' => {},
+  'ABSTRACT_FROM' => 'lib/SelfLoader.pm',
+  'AUTHOR' => 'Steffen Mueller <smueller@cpan.org>',
+  'INSTALLDIRS' => 'perl',
```
Comment (tonycoz) [inline dist/SelfLoader/Makefile.PL]: INSTALLDIRS should be conditional on perl version:
```
INSTALLDIRS => ( $] < 5.011 ? 'perl' : 'site' ),
```

Comment (demerphq) [reply dist/SelfLoader/Makefile.PL]: @tonycoz fixed.

**Review by tonycoz — APPROVED** [review]
