### PR TITLE
class.c: clean up any state if we don't finish the class

### LINKED ISSUE #22169: perl cannot recover from failed class definitions (use feature "class";)
Module:

**Description**

Perl typically allows use to redefine anything, which allows reloading a module to recover from a failed definition, or to reload a module to simply redefine a successful definition.

The new class feature disallows both of these, but the inability to recover from the failed definition is especially a problem.

**Steps to Reproduce**

```
$ ./perl -Ilib -Mfeature=class -M-warnings=experimental -E 'eval "class C {" or print "1: $@"; eval q"class C { field $x:param; }" or print "2: $@"'
1: Missing right curly or square bracket at (eval 1) line 1, at end of line
syntax error at (eval 1) line 1, at EOF
Execution of (eval 1) aborted due to compilation errors.
2: Cannot reopen existing class "C" at (eval 2) line 1.
```

**Expected behavior**

Success when attempting to create the class with a valid definition.

**Perl configuration**

```
Summary of my perl5 (revision 5 version 39 subversion 10) configuration:
  Commit id: 122500c227656f4f9334ca280614d721dcabacba
  Platform:
    osname=linux
    osvers=6.1.0-17-amd64
    archname=x86_64-linux
    uname='linux venus 6.1.0-17-amd64 #1 smp preempt_dynamic debian 6.1.69-1 (2023-12-30) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING -Doptimize=-O0 -g'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g'
    cppflags='-fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='12.2.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -lgdbm -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/x86_64-linux-gnu/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.36'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O0 -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    DEBUGGING
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Apr 24 2024 09:56:39
  %ENV:
    PERLBREW_BASHRC_VERSION="0.43"
    PERLBREW_HOME="/home/tony/.perlbrew"
    PERLBREW_MANPATH=""
    PERLBREW_PATH="/home/tony/perl5/perlbrew/bin"
    PERLBREW_ROOT="/home/tony/perl5/perlbrew"
    PERLBREW_VERSION="0.67"
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.39.10/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.39.10
    /usr/local/lib/perl5/5.39.10/x86_64-linux
    /usr/local/lib/perl5/5.39.10
```

### PR DESCRIPTION
**Pull request by tonycoz**
Fixes #22169

### CODE REVIEW

File: class.c [hunk 1]
```diff
@@ -805,14 +805,80 @@ Perl_class_seal_stash(pTHX_ HV *stash)
...
             for(SSize_t i = PadnamelistMAX(fieldnames); i >= 0 ; i--) {
                 PADNAME *pn = PadnamelistARRAY(fieldnames)[i];
                 op_free(PadnameFIELDINFO(pn)->defop);
+                PadnameFIELDINFO(pn)->defop = NULL;
             }
+            PadnamelistREFCNT_dec(fieldnames);
+            aux->xhv_class_fields = NULL;
+        }
+
+        /* TODO: cleanup DOES if added above */
```
Comment (mauke) [inline class.c]: At first, I was confused by this comment. (What's so special about a `DOES` method that is not handled by the generic cleanup below? Why not add the code right now instead of relying on some unknown future developer? What are the consequences of not cleaning up `DOES`?)

Turns out this comment is entirely appropriate because the code that would create a `DOES` method only exists in the form of a "TODO" comment, too. There really is nothing to do here until `DOES` is actually implemented.

Comment (tonycoz) [reply class.c]: I thought about it and removed the comment.

If DOES() is synthesized before class_seal_stash() then we'll get extra warnings in the tests this change adds.

If DOES() is synthesized in class_seal_stash() then it won't exist at this point.

I'm going to make some other changes too, I think it's reasonable to put the clean up in a new function to keep class_seal_stash() focused.

**Comment by jkeenan** [comment]
@leonerd, could you please review this p.r. from @tonycoz?  Thanks.

File: class.c [hunk 2]
```diff
@@ -636,184 +636,264 @@ Perl_class_apply_attributes(pTHX_ HV *stash, OP *attrlist)
...
+been defined so a new attempt can be made.
+
+*/
+
+static void
+S_class_cleanup_definition(pTHX_ HV *stash) {
+    struct xpvhv_aux *aux = HvAUX(stash);
+
+    SvREFCNT_dec(aux->xhv_class_superclass);
+    aux->xhv_class_superclass = NULL;
```
Comment (bulk88) [inline class.c:661]: I suggest lifting the pointers to a C autos, and setting struct field to NULL, then call ```SvREFCNT_dec```. Analyse if ``` SvREFCNT_dec_NN``` is appropriate.

File: class.c [hunk 3]
```diff
@@ -636,184 +636,264 @@ Perl_class_apply_attributes(pTHX_ HV *stash, OP *attrlist)
...
+        HE *he;
+        while ((he = hv_iternext(stash)) != NULL) {
+            STRLEN klen;
+            const char * const kpv = HePV(he, klen);
+            SV *entry = HeVAL(he);
+            CV *cv = NULL;
+            if (SvTYPE(entry) == SVt_PVGV
+                && (cv = GvCV((GV*)entry))
+                && (CvIsMETHOD(cv) || memEQs(kpv, klen, "new"))) {
+                SvREFCNT_dec(cv);
```
Comment (bulk88) [inline class.c]: Add _NN(), cv already proved to be derefable

File: class.c [hunk 4]
```diff
@@ -636,184 +636,264 @@ Perl_class_apply_attributes(pTHX_ HV *stash, OP *attrlist)
...
+                GvCV_set((GV*)entry, NULL);
+            }
+            else if (SvTYPE(entry) == SVt_PVCV
+                     && (CvIsMETHOD((CV*)entry) || memEQs(kpv, klen, "new"))) {
+                (void)hv_delete(stash, kpv, HeUTF8(he) ? -(I32)klen : (I32)klen,
```
Comment (bulk88) [inline class.c:702]: Pass the HEK* maybe, or U32 hash. hv_delete_ent() maybe??? XS api is not fully there for exotic with HEK with hash, not fetch, HV operations.

File: class.c [hunk 5]
```diff
@@ -636,184 +636,264 @@ Perl_class_apply_attributes(pTHX_ HV *stash, OP *attrlist)
...
+
+    /* field clean up */
+    resume_compcv_final(aux->xhv_class_suspended_initfields_compcv);
+    SvREFCNT_dec(PL_compcv);
+    Safefree(aux->xhv_class_suspended_initfields_compcv);
+    aux->xhv_class_suspended_initfields_compcv = NULL;
+
+    /* remove any ISA entries */
+    SV *isaname = newSVpvf("%" HEKf "::ISA", HvNAME_HEK(stash));
+    sv_2mortal(isaname);
```
Comment (bulk88) [inline class.c]: ```sv_2mortal(isaname);``` to ```isaname = sv_2mortal(isaname);```, use the free retval register.

File: class.c [hunk 6]
```diff
@@ -636,184 +636,264 @@ Perl_class_apply_attributes(pTHX_ HV *stash, OP *attrlist)
...
-                newPADxVOP(OP_PADSV, 0, PADIX_SELF),
-                newPADxVOP(OP_PADHV, OPf_REF, PADIX_PARAMS),
-                /* TODO: This won't work at all well under `use threads` because
-                 * it embeds the CV * to the superclass initfields CV right into
-                 * the optree. Maybe we'll have to pop it in the pad or something
-                 */
-                newSVOP(OP_CONST, 0, (SV *)superaux->xhv_class_initfields_cv),
-                NULL);
+        U32 fieldix = PadnameFIELDINFO(pn)->fieldix;
+        (void)hv_store_ent(fieldix_to_padix, sv_2mortal(newSVuv(fieldix)), newSVuv(padix), 0);
```
Comment (bulk88) [inline class.c:770]: is there a better way of doing this other than a trip through ```SvPV(3args)```'s ```S_uiv_2buf()```, or worse going to libc sprintf with dozens of lock aq/releases, and maybe some kernel calls to the FS. I would just have 4 byte / 8 byte UVs stored straight as raw unprintable binary with SvPOK_on(). Hash algo/perl just sees char strings, vs turning them into longer less dense ascii bytes.

File: class.c [hunk 7]
```diff
@@ -636,184 +636,264 @@ Perl_class_apply_attributes(pTHX_ HV *stash, OP *attrlist)
...
-            }
+        aux[0].uv = fieldix;
+
+        OP *fieldop = newUNOP_AUX(OP_INITFIELD, valop ? OPf_STACKED : 0, valop, aux);
+        fieldop->op_private = op_priv;
+
+        HE *he;
+        if((he = hv_fetch_ent(fieldix_to_padix, sv_2mortal(newSVuv(fieldix)), 0, 0)) &&
+           SvOK(HeVAL(he))) {
+            fieldop->op_targ = SvUV(HeVAL(he));
```
Comment (bulk88) [inline class.c:892]: factor out ```HeVAL(he)```, get the SV*. its too many layers deep of derefs in code, and probably does optimize, but its 3 or 4 derefs now from the C auto. if accidents happen with multi eval, they will be smaller.

File: class.c [hunk 8]
```diff
@@ -636,184 +636,264 @@ Perl_class_apply_attributes(pTHX_ HV *stash, OP *attrlist)
...
-                PADNAME *pn = PadnamelistARRAY(fieldnames)[i];
-                op_free(PadnameFIELDINFO(pn)->defop);
-            }
+        aux[0].uv = fieldix;
+
+        OP *fieldop = newUNOP_AUX(OP_INITFIELD, valop ? OPf_STACKED : 0, valop, aux);
+        fieldop->op_private = op_priv;
+
+        HE *he;
+        if((he = hv_fetch_ent(fieldix_to_padix, sv_2mortal(newSVuv(fieldix)), 0, 0)) &&
```
Comment (bulk88) [inline class.c:890]: idk if this is a loop, but if it is, y not reuse the sv_2mortal(newSVuv()); ?

**Comment by jkeenan** [comment]
@tonycoz do you have a feeling for whether or not we're going to be able to merge this pull request into blead in this dev cycle or not?  If not, then I recommend we label it 'defer-next-dev'.

**Comment by tonycoz** [comment]
It's not going anywhere until @leonerd looks at it

**Comment by ap** [comment]
@leonerd Ping?

File: t/class/gh22169.t [hunk 9]
```diff
@@ -0,0 +1,59 @@
...
+}
+
+BEGIN {
+    our $saw_end;
+    eval <<'CLASS';
+class MyTest :isa(Base) {
+    field $x = "First";
+    field $w :reader;
+    ADJUST {
+        fail("ADJUST from failed class definition called");
```
Comment (leonerd) [inline t/class/gh22169.t]: Likely wants to be `::fail()`

**Review by leonerd — CHANGES_REQUESTED** [review]
Code addition looks fine.
I haven't read in detail the large changes to `Perl_class_seal_stash()` but I presume this is mostly just a re-indentation exercise with no change besides invoking the new cleanup function in the failure case.

I have read the new `.t` file about four times and I imagine it's supposed to invoke a compiletime error in the `eval STR` but I can't see what the error is supposed to be. Could it be made clearer there?

File: class.c (hunk 2 above)
Comment (tonycoz) [reply class.c:661]: `xhv_class_superclass` can be NULL if the class has no base class defined.

I don't think there's any value re-ordering here, since we only write to `xhv_class_superclass` after the REFCNT_dec.

I think it's unlikely the cache line will expire - this is a reference to an existing class, so it's just going to reduce the reference count and test it.

File: class.c (hunk 4 above)
Comment (tonycoz) [reply class.c:702]: `hv_delete_ent()` would require making a SV, this would only be efficient for the (I think) atypical case of the key being an SVKEY.

File: class.c (hunk 2 above)
Comment (tonycoz) [reply class.c:653]: This code was only re-indented.

**Comment by tonycoz** [comment]
> I haven't read in detail the large changes to `Perl_class_seal_stash()` but I presume this is mostly just a re-indentation exercise with no change besides invoking the new cleanup function in the failure case.

Yes,  Except for some re-wrapping it's just indentation, the github diff viewer has an option to ignore whitespace which is handy for changes like this:

image

**Comment by tonycoz** [comment]
> I have read the new `.t` file about four times and I imagine it's supposed to invoke a compiletime error in the `eval STR` but I can't see what the error is supposed to be. Could it be made clearer there?

There's no closing `}`, I'll add a comment.

File: class.c (hunk 3 above)
Comment (tonycoz) [reply class.c]: Done

File: class.c (hunk 5 above)
Comment (tonycoz) [reply class.c]: Done

File: class.c (hunk 6 above)
Comment (tonycoz) [reply class.c:770]: This code was only re-indented

File: class.c (hunk 7 above)
Comment (tonycoz) [reply class.c:892]: This code was only re-indented

File: class.c (hunk 8 above)
Comment (tonycoz) [reply class.c:890]: It is a loop, but this code was only re-indented.

File: t/class/gh22169.t (hunk 9 above)
Comment (tonycoz) [reply t/class/gh22169.t]: Fixed, thanks.

**Comment by tonycoz** [comment]
Squashed the two commits since it didn't seem worth messing with adding to the first commit and dealing with the conflicts in moving the code to the new function.

**Review by leonerd — APPROVED** [review]
Ah yes, that test makes sense now. LGTM

File: class.c (hunk 2 above)
Comment (bulk88) [reply class.c:661]: My rational for the change is so the CC has the opportunity to not write the int literal that is part of  `->xhv_class_superclass` 2x in machine code. I doubt the offset of `->xhv_class_superclass` is 0x0. Its more likely to be 0x18 or 0x30 or 0x10. Foo-arch RISC CPUs may or may not not allow writing a +/- (U8) 0xF0 literal, that will be embedded inside the `ld`/`st`/`mov` opcode.  So on Foo RISC CPU arch, Either the user wants load/store opcodes, or the user wants integer algebra opcodes. Can't have your cake and eat it too,

I have a personal policy to write C code, pretending that certain Intel x86 only op codes do not exist in my head, and to avoid writing C code, that will emit those certain Intel x86 only op,

Specifically I try to not use Intel's `lea` op, which is unique on planet earth. No other CPU has ever had an op that does `a1 = a1+a2+(a3<<a4) ;` AND that op DOES NOT CHANGE EFLAGS/jmp status control bits,

I also avoid Intel's swiss army knife of pre-calculus math exams, the 2 byte ling SIB operand specifier. I prefer to stick to old fashioned 1 byte long modR/M operands.

`lea` and `sib` is easily fixed by just factoring out some math from your struct deref statements in your inner loop. 
Change int i  = 0; i++; to using a real pointer, that gets bumped by sizeof(c_struct) and < compare against a read END pointer in your loop. All those LEA and SIB ops fluffery has been factored out by hand in C pretty easily.

ARM32 CPUs can't store more than  a U8 literal in THUMB machine code, and can't store more than a 2^12 (4096)  integer literal operand in 4byte OPs ARM. All C lang literals > 0x100 or > 4096, become separate  instruction `LOAD DblWrdRegX2, *(U32*)(IP+(0xff*4);` opcodes, Seeing all those >0x80 >0x100  >0x1000 src code literal ints/src code struct derefs on large structs,  turning to separate mov opcodes, to GET MY OWN CONST LITERALS THAT I TYPED IN BASE 10!!! It makes my stomach feel sick reason Arm32 asm code,

So to solve every possible flaw and defect,, on every CPU arch, for all CPU archs past present and future, on every  commercial grade and hobby grade C compiler from any vendor, combine whit any CC -O -m -arch cmd line args. and so I know I wrote good clean code and I dont need to decompile it because I can trust that the CC, any CC, I used, it did the best choice that I wanted. 

So solve all over that, just lift the ptr_to_dotr from malloc mem first, to a C auto/volatile register, assign NULL to the malloc mem you just lifted, then pass [IRL there is no"pass"its already inside RCX or RDI] the lifted ptr stored in a volatile register to the heavy weight C and invoke the heavy weight C call.

benefit is minimal phy mem interactions, minimum computing abs addrs of data vars from offsets into structs.

3 `aux->xhv_class_superclass` statements become

```
void ** p = &aux->xhv_class_superclass;
if(*p) {
    void * p2 = *p;
    *p = NULL;
    foo_free(p2);
}
```
not
```
if(aux->xhv_class_superclass) 
    foo_free(aux->xhv_class_superclass);
aux->xhv_class_superclass = NULL;
```
What if var `aux` happens to be a c stack var and not a non vol register? Maybe `foo_free()` changed the ptr inside C stack var `aux` that was stored/splilled to phy vir memory? escape analysis? How do you know what the the e-liberal/e-conservative/e-communist/e-fascist  parties at IEEE going to vote on for next month's draft spec of https://developers.redhat.com/articles/2022/06/02/use-compiler-flags-stack-protection-gcc-and-clang#safestack_and_shadow_stack ?

so worst case possible, `aux->xhv_class_superclass = NULL;` has 2 read ops, 1  xor op, 1 write op. my perfect version eliminated the 2 read ops, 
earlier by doing
```
void ** p = &aux->xhv_class_superclass;
if(*p) {
```

File: class.c (hunk 4 above)
Comment (bulk88) [reply class.c:702]: > `hv_delete_ent()` would require making a SV, this would only be efficient for the (I think) atypical case of the key being an SVKEY.
```
# define hv_deletehek(hv, hek, flags) \
    hv_common((hv), NULL, HEK_KEY(hek), HEK_LEN(hek), HEK_UTF8(hek), \
              (flags)|HV_DELETE, NULL, HEK_HASH(hek))
```
usng this vs `hv_delete()` is still a better choice, U32 has wasnt recalculated.

Unrealistic bc there arent supposd 2 exit outside TIEHASH
```
#define HePV(he,lp)		((HeKLEN(he) == HEf_SVKEY) ? SvPV(HeKEY_sv(he),lp) :((lp = HeKLEN(he)), HeKEY(he)))
```

If santa says youver been a good boy `HeKEY_sv(he)` will be a SVLEN()==0 HEK* COW. Note either way, you get 2 accelerated hash lookup data structures here, either an unreliatic SV*, or a HEK * from shared HEK POOL. Its wrong to use const RO "CString" `hv_delete()` here, you have the meta data to do something better,
