### PR TITLE
embed.pl: Fix BBC build failures #24196, #24197

### LINKED ISSUE #24196: BBC: Blead Breaks Sys::Ibam
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.43 running under perl 5.43.8.

-----------------------------------------------------------------

BBC: Blead Breaks Sys::Ibam

Please see https://fast2-matrix.cpantesters.org/?dist=Sys-Ibam-0.05

---
**Flags**
- category=core
- severity=low
---
**Perl configuration**
```
Site configuration information for perl 5.43.8:

Configured by cpan at Sun Feb 15 01:54:53 EST 2026.

Summary of my perl5 (revision 5 version 43 subversion 8) configuration:
  Commit id: e2935f028a6b644a1710455ee7b025b4866d438c
  Platform:
    osname=linux
    osvers=6.12.0-124.35.1.el10_1.x86_64
    archname=x86_64-linux
    uname='linux cjg-rhel10 6.12.0-124.35.1.el10_1.x86_64 #1 smp preempt_dynamic sat jan 31 19:10:18 est 2026 x86_64 gnulinux '
    config_args='-des -Dprefix=/home/cpan/bin/perl -Dscriptdir=/home/cpan/bin/perl/bin -Dusedevel -Duse64bitall'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='14.3.1 20250617 (Red Hat 14.3.1-2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib /usr/lib64 /usr/local/lib64
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/../lib64/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.39'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


---
@INC for perl 5.43.8:
    /home/cpan/bin/perl/lib/site_perl/5.43.8/x86_64-linux
    /home/cpan/bin/perl/lib/site_perl/5.43.8
    /home/cpan/bin/perl/lib/5.43.8/x86_64-linux
    /home/cpan/bin/perl/lib/5.43.8

---
Environment for perl 5.43.8:
    HOME=/home/cpan
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_ALL=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl/bin:/home/cpan/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
    PERL_BADLANG (unset)
    SHELL=/bin/bash
```

### LINKED ISSUE #24197: BBC: Blead Breaks Wifi::WpaCtrl
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.43 running under perl 5.43.8.

-----------------------------------------------------------------

BBC: Blead Breaks Wifi::WpaCtrl

Please see https://fast2-matrix.cpantesters.org/?dist=Wifi-WpaCtrl-0.02

---
**Flags**
- category=core
- severity=low
---
**Perl configuration**
```
Site configuration information for perl 5.43.8:

Configured by cpan at Sun Feb 15 01:54:53 EST 2026.

Summary of my perl5 (revision 5 version 43 subversion 8) configuration:
  Commit id: e2935f028a6b644a1710455ee7b025b4866d438c
  Platform:
    osname=linux
    osvers=6.12.0-124.35.1.el10_1.x86_64
    archname=x86_64-linux
    uname='linux cjg-rhel10 6.12.0-124.35.1.el10_1.x86_64 #1 smp preempt_dynamic sat jan 31 19:10:18 est 2026 x86_64 gnulinux '
    config_args='-des -Dprefix=/home/cpan/bin/perl -Dscriptdir=/home/cpan/bin/perl/bin -Dusedevel -Duse64bitall'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='14.3.1 20250617 (Red Hat 14.3.1-2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib /usr/lib64 /usr/local/lib64
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/../lib64/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.39'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


---
@INC for perl 5.43.8:
    /home/cpan/bin/perl/lib/site_perl/5.43.8/x86_64-linux
    /home/cpan/bin/perl/lib/site_perl/5.43.8
    /home/cpan/bin/perl/lib/5.43.8/x86_64-linux
    /home/cpan/bin/perl/lib/5.43.8

---
Environment for perl 5.43.8:
    HOME=/home/cpan
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_ALL=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl/bin:/home/cpan/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
    PERL_BADLANG (unset)
    SHELL=/bin/bash
```

### PR DESCRIPTION
**Pull request by khwilliamson**
Fixes https://github.com/Perl/perl5/issues/24196
Fixes https://github.com/Perl/perl5/issues/24197

This bug stemmed from a C preprocessor nuance that I was unaware of.  It
only happened on unthreaded builds and only affected functions that have
a single argument, the thread context, so that on unthreaded builds,
these have 0 parameters.  The preprocessor dropped the parens indicating
there is an argument list (empty), which led to compilation errors.
It does not do this if there is at least one argument besides the thread
context one.

The solution is to extend the use of a paradigm already in effect for
other situations, so that there is a placeholder argument for the thread
context that gets dropped.  This is only defined on unthreaded builds.
It is cleaner to do this for unaffected functions as well, (those that
have an argument besides the thread context).

Threaded is unchanged.

* This set of changes does not require a perldelta entry.

### CODE REVIEW

**Comment by jkeenan** [comment]
I installed a local branch derived from this p.r. and built an unthreaded perl on Linux.  I was then able to install Sys::Ibam and Wifi::WpaCtrl against that perl.
```
[gh-24200-khwilliamson-fix_longs-20260216] 2020 $ ./bin/perl -Ilib -MSys::Ibam -MWifi::WpaCtrl -E 'say join "|" => ($Sys::Ibam::VERSION, $Wifi::WpaCtrl::VERSION, "hello world");'
0.05|0.02|hello world
```
So in terms of the original complaint, this DWIMs.

perlguts code should get additional eyeballs.

**Comment by tonycoz** [comment]
> This bug stemmed from a C preprocessor nuance that I was unaware of. It
> only happened on unthreaded builds and only affected functions that have
> a single argument, the thread context, so that on unthreaded builds,
> these have 0 parameters. The preprocessor dropped the parens indicating
> there is an argument list (empty), which led to compilation errors.
> It does not do this if there is at least one argument besides the thread
> context one.

Do you have a concrete example of this?

If I preprocess:
```
typedef struct av AV;

#define myNewAV Perl_myNewAV
extern AV *Perl_myNewAV();

void f() {
    AV *av = myNewAV();
}
```
I get:
```
...

typedef struct av AV;


extern AV *Perl_myNewAV();

void f() {
    AV *av = Perl_myNewAV();
}
```

https://compiler-explorer.com/z/dooxvzzvM

**Comment by khwilliamson** [comment]
I took the single newAV() call in utf8.c and changed it to Perl_newAV(aTHX).  I then compiled the project without threads.  It fails with this error

> utf8.c:2550:50: error: macro "newAV" passed 1 arguments, but takes just 0
 2550 |                     msgs_return = Perl_newAV(aTHX);

I then did `make utf8.i`  That line expanded to `msgs_return = newAV;`
The same .i file contains these lines in this order:

> #define aTHX 
#define newAV() MUTABLE_AV(newSV_type(SVt_PVAV))
#define Perl_newAV newAV

The parens are missing in the expansion.  That's how I drew my conclusion.

**Comment by tonycoz** [comment]
> The parens are missing in the expansion. That's how I drew my conclusion.

Thanks, though the result of pre-processing is meaningless, since it failed, so you're fixing that failure rather than some unexpected C weirdness.

**Review by tonycoz — APPROVED** [review]

File: embed.h [hunk 1]
```diff
@@ -2315,110 +2311,110 @@
...
-#   define Perl_sv_utf8_upgrade_flags           sv_utf8_upgrade_flags
-#   define Perl_sv_utf8_upgrade_nomg            sv_utf8_upgrade_nomg
-#   define Perl_to_uni_fold                     to_uni_fold
-#   define Perl_uv_to_utf8_msgs                 uv_to_utf8_msgs
-#   define Perl_uvchr_to_utf8                   uvchr_to_utf8
-#   define Perl_uvchr_to_utf8_flags             uvchr_to_utf8_flags
-#   define Perl_uvchr_to_utf8_flags_msgs        uvchr_to_utf8_flags_msgs
-#   define Perl_uvoffuni_to_utf8_flags          uvoffuni_to_utf8_flags
-#   define Perl_whichsig                        whichsig
+#   define Perl_SvREFCNT_dec_set_NULL(mTHX,a)   SvREFCNT_dec_set_NULL(a)
```
Comment (Leont) [inline embed.h:2314]: That `mTHX,` looks wrong to me, on an non-multiplicity build there wouldn't be any interpreter pointer passed to these macros.

**Comment by khwilliamson** [comment]
@Leont, Thanks for noticing that
