### PR TITLE
Fix #20085 locale failure on certain threaded locale configurations

### LINKED ISSUE #20085: locale changes causes failures with -Duseithreads
After the merge of khw/locale-3 builds with `-Duesithreads` appear to trigger test failures.

Smoke reports:

* failure in lib/locale.t: https://perl5.test-smoke.org/report/5021335
* failure in t/uni/fold.t, t/re/subst.t, t/re/subst_wamp.t, t/re/substT.t: https://perl5.test-smoke.org/report/5021377
* failute in t/uni/fold.t, t/re/subst.t, t/re/subst_wamp.t, t/re/substT.t + others: https://perl5.test-smoke.org/report/5021356 [I am not certain if the other test failures are related, they did not appear to happen before the commits were merged]

I was able to reproduce the failure in t/re/subst.t (but need confirmation if the smoke setup is the same);
I was not yet able to reproduce the lib/locale.t failure.

Using current blead **with** `-Duseithreads`:

        $ ./Configure -des -Dusedevel -Duseithreads
        $ make -j8
        $ make test_prep
        $ cd t
        $ LC_ALL= LANG= LANGUAGE= LC_CTYPE="en_US.utf-8" ./perl harness re/subst.t
        re/subst.t .. 1/278 # Failed test 263 - \b matches Latin1 before string, mid, and end, /l at re/subst.t line 1070
        #      got "!á!.!è!"
        # expected "á.è"
        re/subst.t .. Failed 1/278 subtests

        Test Summary Report
        -------------------
        re/subst.t (Wstat: 0 Tests: 278 Failed: 1)
          Failed test:  263
        Files=1, Tests=278,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.10 cusr  0.03 csys =  0.16 CPU)
        Result: FAIL

Using current blead **without** `-Duseithreads`:

        $ ./Configure -des -Dusedevel
        $ make -j8
        $ make test_prep
        $ cd t
        $ LC_ALL= LANG= LANGUAGE= LC_CTYPE="en_US.utf-8" ./perl harness re/subst.t
        re/subst.t .. ok
        All tests successful.
        Files=1, Tests=278,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.09 cusr  0.02 csys =  0.13 CPU)
        Result: PASS

**Bisecting:**

Bisecting points to commit 19e550d7feff0e915e0f181add94aebe4e22c38b ( @khwilliamson ):

        commit 19e550d7feff0e915e0f181add94aebe4e22c38b
        Author:     Karl Williamson <khw@cpan.org>
        AuthorDate: Wed Jul 20 16:31:35 2022 -0600
        Commit:     Karl Williamson <khw@cpan.org>
        CommitDate: Tue Aug 9 18:05:59 2022 -0600

            locale.c: Don't waste time executing a no-op

            If we're trying to change the locale to what it already is, that's a
            no-op.  This skips that work.  As noted in the comments, this also led
            to subtle bugs with newlocale() trying to free the basis operand, and
            giving bad results.

**Trimming:**

Trimming the test in t/re/subst.t:

        use Test::More;
        use POSIX;

        my $a_acute = "\N{LATIN SMALL LETTER A WITH ACUTE}";
        my $egrave  = "\N{LATIN SMALL LETTER E WITH GRAVE}";

        setlocale(&POSIX::LC_ALL, "C");
        use locale;

        is("$a_acute.$egrave" =~ s/\b/!/gr, "$a_acute.$egrave", '\\b matches Latin1 before string, mid, and end, /l');

        done_testing();

Running:

        $ LC_ALL= LANG= LANGUAGE= LC_CTYPE=en_US.utf-8 ./perl -I../lib foo.t
        not ok 1 - \b matches Latin1 before string, mid, and end, /l
        #   Failed test '\b matches Latin1 before string, mid, and end, /l'
        #   at foo.t line 13.
        #          got: '!á!.!è!'
        #     expected: 'á.è'
        1..1
        # Looks like you failed 1 test of 1.

        $ LC_ALL=en_US.utf-8 ./perl -I../lib foo.t
        ok 1 - \b matches Latin1 before string, mid, and end, /l
        1..1

**Additional information:**

Also observed, in the build with `-Duseithreads`:

* `LC_ALL= LANG= LANGUAGE= ./perl harness re/subst.t` => PASS
* `LC_ALL= LANG= LANGUAGE= LC_CTYPE=en_US.utf-8 ./perl harness re/subst.t` => FAIL
* `LC_ALL= LANG= LANGUAGE= LC_TIME=en_US.utf-8 ./perl harness re/subst.t` => PASS
* `LC_ALL= LANG= LANGUAGE= LC_CTYPE=en_US.utf-8 LC_TIME=en_US.utf-8 ./perl harness re/subst.t` => FAIL
* `LC_ALL= LANG= LANGUAGE= LC_CTYPE=en_US.utf-8 LC_NUMERIC=en_US.utf-8 ./perl harness re/subst.t` => PASS
* `LC_ALL= LANG= LANGUAGE= LC_CTYPE=en_US.utf-8 LC_TELEPHONE=en_US.utf-8 ./perl harness re/subst.t` => PASS

### PR DESCRIPTION
**Pull request by khwilliamson**
Locale initialization was failing on threaded perls on systems without the ability to query the current locale (mainly linux) and with an initialization where some categories had a different locale than others

### CODE REVIEW

**Comment by jkeenan** [comment]
@bram-perl, would this p.r. address your concerns?

**Comment by Leont** [comment]
This PR could use a more descriptive title.

File: locale.c [hunk 1]
```diff
@@ -1180,7 +1180,7 @@ S_emulate_setlocale_i(pTHX_
                  * but tis is defensive coding.  The system setlocale() returns
                  * the desired information.  Calculate LC_ALL's entry on the
                  * final iteration */
-                for (PERL_UINT_FAST8_T i = 0; i <= NOMINAL_LC_ALL_INDEX; i++) {
+                for (PERL_UINT_FAST8_T i = 0; i < NOMINAL_LC_ALL_INDEX; i++) {
```
Comment (bram-perl) [inline locale.c]: Is the comment above still accurate?
That is:

    Calculate LC_ALL's entry on the final iteration

still correct?

**Review by bram-perl — COMMENTED** [review]
*commit locale.c: Imnprove LC_ALL recalculation determination*:

Small typo in commit message ("Imnprove" -> "Improve")

*commit locale.c: Make sure LC_ALL gets changed when necessary *:

In the message: can you include a (direct) reference to commit  19e550d7feff0e915e0f181add94aebe4e22c38b ?

(Either in the message itself or in a foot note)

File: locale.c (hunk 1 above)
Comment (khwilliamson) [reply locale.c]: yes

Comment (khwilliamson) [reply locale.c]: I will clarify the comment

File: locale.c [hunk 2]
```diff
@@ -1014,12 +1020,10 @@ S_emulate_setlocale_i(pTHX_
      * called with, and the 'new_locale' to set the category to.  It uses the
      * index to find the category mask that the POSIX 2008 functions use.
      *
-     * The function can be called recursively on all the individual categories,
-     * when the outer call is for LC_ALL.  It would be unnecessary work to
-     * recalculate LC_ALL in the middle of all this; so the 'recalc_LC_ALL'
-     * parameter is set to LOOPING in this circumstance, to indicate to
-     * recalculate only on the final category; 0 to indicate to not recalculate
-     * at all; and 1 to indicate to do so unconditionally */
+     * 'recalc_LC_ALL' is set to true iff this call isn't part of a tight loop
```
Comment (bram-perl) [inline locale.c]: small typo: `iff' -> 'if'

File: locale.c [hunk 3]
```diff
@@ -1049,9 +1049,17 @@ S_emulate_setlocale_i(pTHX_
...
-        && locale_on_entry
-        && strEQ(new_locale, locale_on_entry))
+    if (     entry_obj != LC_GLOBAL_LOCALE
+
+           /* Even if this particular category isn't changing in this call,
+            * this parameter being 'true', indicates this is just the final
+            * iteration in a loop.  Another iteration may have changed another
+            * category, which affects LC_ALL, so we need to continue on so as
+            * to recalculait LC_ALL */
+        && ! recalc_LC_ALL
```
Comment (bram-perl) [inline locale.c]: What slightly worries me: part of the comment above:

     Bitter experience also
     indicates that newlocale() can free up the basis locale memory if we
     call it with the new and old being the same. */

Is there now (again) a chance of that happening?

File: locale.c (hunk 2 above)
Comment (khwilliamson) [reply locale.c]: iff means "if and only if"  It is standard notation in English language mathematics.  I presumed it was international.  I can expand it out, but there are more than 100 occurrences of it in our source

Comment (bram-perl) [reply locale.c]: in that case, just leave it as is :)

(I'm/wasn't familiar with "iff".. I don't know if I ever saw it before.. maybe I did and mentally substituted it with "if")

File: locale.c (hunk 3 above)
Comment (khwilliamson) [reply locale.c]: I think you found a flaw.  Thank you.

Comment (khwilliamson) [reply locale.c]: should be fixed by latest push
