### PR TITLE
openbsd: ensure we link to the built libperl.a, not the system libperl.a

### LINKED ISSUE #22125: lib/ExtUtils/t/Embed.t: failures on OpenBSD when compiling with gcc but not with clang
For several months I have been noticing smoke-test failures under certain configurations on OpenBSD-7.4; see, *e.g.,* [report 5052514](https://perl5.test-smoke.org/report/5052514).  The failures occur when configuring a perl built with these command-line switches:
```
$ sh ./Configure -des -Dusedevel -Dcc=gcc -Accflags='-DPERL_RC_STACK -DDEBUG_LEAKING_SCALARS'
```
... and then, after running `make test_prep`, calling:
```
$ cd t; ./perl harness -v ../lib/ExtUtils/t/Embed.t; cd - 
ld: error: undefined symbol: Perl_more_sv
>>> referenced by embed_test.c
>>>               /tmp//ccE9t92Z.o:(S_new_SV)

ld: error: undefined symbol: PL_sv_serial
>>> referenced by embed_test.c
>>>               /tmp//ccE9t92Z.o:(S_new_SV)
>>> referenced by embed_test.c
>>>               /tmp//ccE9t92Z.o:(S_new_SV)
collect2: ld returned 1 exit status

not ok 1
not ok 10 # system returned -1
Failed 10/10 subtests 

Test Summary Report
-------------------
../lib/ExtUtils/t/Embed.t (Wstat: 0 Tests: 2 Failed: 2)
  Failed tests:  1, 10
  Parse errors: Tests out of sequence.  Found (10) but expected (2)
                Bad plan.  You planned 10 tests but ran 2.
Files=1, Tests=2,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.48 cusr  0.11 csys =  0.62 CPU)
Result: FAIL
```
I didn't pay these much attention at first because [at first](https://perl5.test-smoke.org/report/5049575) the perl was being built with a compiler I had never heard of, `eg++`.  But more recently these failures were occuring with `gcc` as the compiler.

I haven't been able to install an OpenBSD more recent than 6.9, but I decided to explore this problem on that version today regardless.  I got the test failure reported above on blead.  I then decided to see whether these failures were due to a recent code change or whether @cjg-cguevara's exploration of these config options had merely revealed a problem that was "always" there.  I tested at tag `v5.38.0` and got the failure reported above.
```
$ uname -mrs
OpenBSD 6.9 amd64

$ gcc --version | head -1
gcc (GCC) 4.2.1 20070719

$ git show | head -3
commit 76298ae68aa7796f0ffc05095b127d23f4b2de8f
Author: Ricardo Signes <rjbs@semiotic.systems>
Date:   Sat Jul 1 20:48:27 2023 -0400

$ sh ./Configure -des -Dusedevel -Dcc=gcc -Accflags='-DPERL_RC_STACK -DDEBUG_LEAKING_SCALARS'; make test_prep

$ ./perl -Ilib -V:config_args
config_args='-des -Dusedevel -Dcc=gcc -Accflags=-DPERL_RC_STACK -DDEBUG_LEAKING_SCALARS';

$ cd t; ./perl harness -v ../lib/ExtUtils/t/Embed.t; cd - 
ld: error: undefined symbol: Perl_more_sv
>>> referenced by embed_test.c
>>>               /tmp//ccE9t92Z.o:(S_new_SV)

ld: error: undefined symbol: PL_sv_serial
>>> referenced by embed_test.c
>>>               /tmp//ccE9t92Z.o:(S_new_SV)
>>> referenced by embed_test.c
>>>               /tmp//ccE9t92Z.o:(S_new_SV)
collect2: ld returned 1 exit status

not ok 1
not ok 10 # system returned -1
Failed 10/10 subtests 

Test Summary Report
-------------------
../lib/ExtUtils/t/Embed.t (Wstat: 0 Tests: 2 Failed: 2)
  Failed tests:  1, 10
  Parse errors: Tests out of sequence.  Found (10) but expected (2)
                Bad plan.  You planned 10 tests but ran 2.
Files=1, Tests=2,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.48 cusr  0.11 csys =  0.62 CPU)
Result: FAIL
```
Since the `gcc` version I was testing with dates back to 2007, I decided to try with the system's default C-compiler, `clang-10`.
```
$ clang --version                                                               >
OpenBSD clang version 10.0.1 
Target: amd64-unknown-openbsd6.9
Thread model: posix
InstalledDir: /usr/bin

$ sh ./Configure -des -Dusedevel -Dcc=clang -Accflags='-DPERL_RC_STACK -DDEBUG_LEAKING_SCALARS'; make test_prep
```
With this more recent `clang`, the failing tests PASSed.
```
$ cd t; ./perl harness -v ../lib/ExtUtils/t/Embed.t; cd -

ok 1
ok 2
ok 3
ok 4
ok 5
ok 6
ok 7
ok 8
ok 9
ok 10 # system returned 0
ok
All tests successful.
Files=1, Tests=10,  1 wallclock secs ( 0.01 usr  0.02 sys +  0.55 cusr  0.36 csys =  0.94 CPU)
Result: PASS
```
It would be good if someone could test these config options on an up-to-date OpenBSD with both `gcc` and `clang`.  We can then try to evaluate the source of the test failures.  cc: @afresh1

### PR DESCRIPTION
**Pull request by tonycoz**
When building with gcc, lib/ExtUtils/t/Embed.t would link against the system libperl.a rather than the newly built libperl.a.
    
Due to the limited API used by the sample code this typically didn't crash, but some configuration changes could result in a crash or a link error.
    
For OpenBSD, change the link options to more closely match those used when building the perl executable, which results in linking against the correct library.
    
Fixes #22125

Also adds a test to ensure we are linking against the correct libperl.

Smoke reports from before a trivial rebase at https://perl.develop-help.com/?b=smoke-me%2Ftonyc%2F22125-openbsd-embed

---------------------------------------------------------------------------------
* This set of changes requires a perldelta entry, and it is included.

### CODE REVIEW

**Comment by jkeenan** [comment]
@tonycoz, thanks for continuing to investigate this.  Could you rebase your smoke-me branch and push this new code to that branch?  That way, @cjg-cguevara's smoker will pick up the branch.

@afresh1, can you take a look at this p.r.?  Thanks.

**Comment by jkeenan** [comment]
@tonycoz:  I fetched your p.r. and built a `perl` locally per the following:
```
$ uname -mrs
OpenBSD 6.9 amd64
$ gcc --version
gcc (GCC) 4.2.1 20070719 
$ gitcurr
gh-23265-tonycoz-22125-openbsd-embed-20250507
$ ./perl -Ilib -V:config_args
config_args='-des -Dusedevel -Dcc=gcc -Accflags=-DPERL_RC_STACK -DDEBUG_LEAKING_SCALARS';
$ ./perl -Ilib -v | head -2 | tail -1
This is perl 5, version 41, subversion 13 (v5.41.13 (v5.41.12-41-g060adda81e)) built for OpenBSD.amd64-openbsd
```
This configuration was the first one I discussed in https://github.com/Perl/perl5/issues/22125.  All tests PASSed.  So that's a very good sign.  I will want to re-test this with `clang10` and `g++`.  However, as previously reported my OpenBSD-VM version is obsolete, so we'll need feedback from people who have more up-to-date versions of the platform and its C-compilers.  Having your p.r. code in the smoke-me branch will be very helpful for this.

**Comment by tonycoz** [comment]
> Having your p.r. code in the smoke-me branch will be very helpful for this.

I pushed it to the smoke-me, https://perl.develop-help.com/?b=smoke-me%2Ftonyc%2F22125-openbsd-embed we're just waiting for results now.

**Comment by jkeenan** [comment]
I've also gotten a PASS with the following configuration:
```
$ ./perl -Ilib -V:config_args
config_args='-des -Dusedevel -Dcc=clang -Accflags=-DPERL_RC_STACK -DDEBUG_LEAKING_SCALARS';
```
Am beginning a smoke-test run with my customary configurations.  That will take several hours.  Note that I haven't looked at the code changes at all -- only the test results.

**Comment by afresh1** [comment]
I should be able to run tests with this.  Will have to remember which architectures I have that still use gcc :-)

File: util.c [hunk 1]
```diff
@@ -5737,6 +5737,52 @@ S_xs_version_bootcheck(pTHX_ SSize_t items, SSize_t ax, const char *xs_p,
...
 }
 
+/*
+=for apidoc api_version_assert
+
+Used by the PERL_API_VERSION_CHECK macro to compare the perl the
+object was built with and the perl that C<libperl> was built with.
+
+This can be used to ensure that these match and produces a more
+diagnosable than random crashes and mis-behaviour.
```
Comment (jkeenan) [inline util.c:5666]: There seems to be a word or two missing after `diagnosable`.  `diagnosable behavior`, perhaps?

**Comment by Leont** [comment]
Intuitively, it seems wrong to me that this is OpenBSD specific code. Are we sure we're fixing this in the right place?

**Comment by tonycoz** [comment]
> Intuitively, it seems wrong to me that this is OpenBSD specific code. Are we sure we're fixing this in the right place?

Smoke testing didn't find anything else tripping the added version check.

There may be other systems that trip this, but I'd rather not risk breaking this test for other systems by making the change for other systems too without evidence that it's needed.

**Comment by ap** [comment]
Both points seem reasonable. We (PSC) are thinking we should ship this patch as is for now, but we also want to pick this up early next cycle and investigate whether we can make this change across the board without limiting it to OpenBSD.

**Comment by Leont** [comment]
> Both points seem reasonable. We (PSC) are thinking we should ship this patch as is for now, but we also want to pick this up early next cycle and investigate whether we can make this change across the board without limiting it to OpenBSD.

Yeah that sounds reasonable to me.

**Comment by afresh1** [comment]
> I should be able to run tests with this. Will have to remember which architectures I have that still use gcc :-)

Time got away from me, it won't be this week.

**Comment by afresh1** [comment]
On my machine where it is easy to build a smoke-me perl:
```$ ./perl -v

This is perl 5, version 41, subversion 13 (v5.41.13 (v5.41.12-41-g060adda81e)) built for OpenBSD.sparc64-openbsd
```
with
```
./Configure -des -Dusedevel -Dcc=gcc -Accflags="-DPERL_RC_STACK -DDEBUG_LEAKING_SCALARS"
```
I get:
```
Failed 3 tests out of 2664, 99.89% okay.
        ../lib/locale.t
        porting/authors.t
        run/locale.t
```

Which does not include failures from `lib/ExtUtils/t/Embed.t`.

**Comment by tonycoz** [comment]
rebased to clear the conflict

File: util.c [hunk 2]
```diff
@@ -5739,6 +5739,52 @@ S_xs_version_bootcheck(pTHX_ SSize_t items, SSize_t ax, const char *xs_p,
...
+Perl_api_version_assert(size_t interp_size, void *v_my_perl,
+                        const char *api_version) {
+    dTHX;
+
+    PERL_ARGS_ASSERT_API_VERSION_ASSERT;
+
+    if (interp_size != sizeof(PerlInterpreter)) {
+        /* detects various types of configuration mismatches */
+        /* diag_listed_as: Mismatch between expected and libperl %s */
+        Perl_croak(aTHX_
```
Comment (bulk88) [inline util.c:5681]: use a croak_nocontext(), this fn is max run 1x a process. the croak branches are 0 Kelvin code and will never execute w/o C dev user error, the performance of executing  `while (1) { eval { croak("heap corruption"); }; }` is illogical. smaller machine code is the correct goal.

File: util.c [hunk 3]
```diff
@@ -5739,6 +5739,52 @@ S_xs_version_bootcheck(pTHX_ SSize_t items, SSize_t ax, const char *xs_p,
...
+
+This can be used to ensure that these match and produces a more
+diagnosable than random crashes and mis-behaviour.
+
+=cut
+*/
+
+void
+Perl_api_version_assert(size_t interp_size, void *v_my_perl,
+                        const char *api_version) {
```
Comment (bulk88) [inline util.c:5673]: why not switch `const char *api_version` to `PERL_BCDVERSION` which is an integer? The only reason `xs_handshake()` uses a  `const char *api_version` is hysterical raisins with pre-existing EU::PXS code gen behavior and hysterical raisins over `string equality` `method of operation` in the `IEEE` vs `W3C` vs `WHATWG` vs `IETF` `version.pm` standards war (example: https://github.com/Perl/perl5/commit/fb7942811c8097ed2e61fd35a90345226546176a ).

Since my TLDR understanding of v-strings and version string equality and comparison logical operations is, v-str and ver.pm `==` `>` `<` logical operations, should just be labeled `abstract undefined behavior <=> operator` if your writing code for CPAN or writing PP code that will execute on more than 1 build number of `libperl.so`. Or will execute on any `/bin/perl` other than your employer's official corporate "Perl on Docker" image.

So b/c there is so much soap drama with non-floating point version numbers, and PERL_API_VERSION, is a 3 '.' dots thing, which means is part of the standards war, I decided to keep the `const char * null_term_perl_api_ver` parameter for xs_handshake. The drama with  3 '.' dots and `v` prefix was quite active 10 years ago. And `xs_handshake()` was supposed to be "low impact" or "not invasive" or minimalist in design.

using `const char * null_term_perl_api_ver` instead of a `U32` aka `PERL_BCDVERSION`, in the prototype of `xs_handshake()` would've allowed macro PERL_API_VERSION_STRING to be string `"5.40.0-armbe-hurd-newlib-no_rms-lgbtqabi"` or `"5.40.0-mipsle-muscl-no_afferoabi"`. P5P would never modify the `PERL_API_VERSION_STRING` macro to be `"5.40.0-mipsle-muscl-no_afferoabi"`, but P5P can't send lawyers and SWAT/GIGN to force random Linux/BSD distros projects to reverse their patches to Perl on their published `.iso`s.

So that was reason # 2 why I left it as a `char *` and not a `U32`. Minimalist, most flexible for the future, wait and see what happens, dont do an over engineered forklift refactor.

AFAIK the `ELF` spec is mostly written where all the behaviors are "optional" to implement, but if the feature/constant/bit in a bitfield/C struct/member in a struct, is implemented by a vendor, then the feature/constant/bit in a bitfield/C struct/member in a struct has "defined behavior" in `ELF`. `ELF` isn't like Windows and its `PE` format, where there is ONE WAY TO DO IT, NO EXCEPTIONS! B/c Windows and `PE` mandate forever backwards ABI compatibility to the "i386 pre-release SDK" from Oct 1992.

I don't believe ELF binaries compiled in the 1980s for i386 are copy+paste+double click executable on Ubuntu/Freebsd/Fedora in 2025. besides, the Linux kernel doesn't even know what an `ELF` file is, and isn't aware that the `ELF` spec exists.

From Linux's viewpoint, `ELF` is just a random 3rd party kernel driver someone wrote a while back. You can disable ELF support in Linux if you prefer Windows PE .exes/.dlls or MachO files more than the ELF format.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/fs/binfmt_elf_fdpic.c#n92 

https://docs.kernel.org/admin-guide/binfmt-misc.html

So yeah, I have no clue if some Unix OS will add a dozen random tokens/identifiers/english lang words, to the `PERL_API_VERSION_STRING` `"5.40.0"` macro. I don't think any Linux/BSD distro has randomly decided to start patching `PERL_API_VERSION_STRING` in their system perls, in the last couple of years, so at this point in 2025, I would say to use `PERL_BCDVERSION` U32 instead here. Also this code is the REVERSE of `xs_handshake()`, the consumer and producer were flipped around. This is a `.bin` file under full end user control compiled by the end user, loading a  random unknown `libperl.so` file into address space.  The end user is using the cryptographic-ally secure P5P code base (aka `git` + SSL + `github.com`), the end user didn't checkout the patched system perl and its exact `Configure` settings from their Distro vendor (canonical)'s RCS. So P5P  codebase and the end user's fork of the P5P repo, have no reason to change macro `PERL_API_VERSION_STRING` to  `"5.40.0-mipsle-muscl-no_afferoabi"` for some real or imaginary engineering reason.

File: lib/ExtUtils/t/Embed.t [hunk 4]
```diff
@@ -196,6 +209,8 @@ int main(int argc, char **argv, char **env) {
     perl_construct(my_perl);
     PL_exit_flags |= PERL_EXIT_WARN;
 
+    PERL_API_VERSION_ASSERT;
+
```
Comment (bulk88) [inline lib/ExtUtils/t/Embed.t:213]: why not move `PERL_API_VERSION_ASSERT;` to right below `my_perl = perl_alloc();`. me knowing various permutatoins of  crashing ancient modern perl5xx.dll permutations, this test code/demo code already segved or caused heap corruption before reaching the ` PERL_API_VERSION_ASSERT;` statement. 

`PL_exit_flags |= PERL_EXIT_WARN;`

What is grammar token/src code ascii string `PL_exit_flags` in machine code view?

Is `PL_exit_flags` a Perl 5.6/5.8/5.10 symbian/win32/win16/cray style
` extern "C" int * Perl_Isolation_PL_exit_flags(void);`
is it?
` extern "C" int * Perl_Isolation_PL_exit_flags(my_perl);`

is it? IIRC below is AKA `dVAR;` macro,
` extern "C" int * Perl_Isolation_PL_exit_flags(my_env, my_perl);`

is it?
` extern "C" int PL_exit_flags;`

is it?
` extern  int __@@C$PLUS$__PLUSSS$666@_QWERTY@_PL_exit_flags@__;`

is it?
`*(int*)(   ((char*)my_perl) + 0x47c)`

is it?
` extern "C" int __$SONAME@PL_exit_flags$libperl.so.5.40.1.0083.6798;`

What did the end user C dev really write (hex dump wise) with ascii string `PL_exit_flags |= PERL_EXIT_WARN;` ?

Lets do our best to print in english to STDERR before `LD_LAZY_LINK` insta-KILL the process and fills the users console with unreadable CPU GPR and FP register hex dumps and leaves a 30MB core dump file of gibberish on the end users machine.

File: util.c (hunk 3 above)
Comment (bulk88) [reply util.c:5673]: > So yeah, I have no clue if some Unix OS will add a dozen random tokens/identifiers/english lang words, to the `PERL_API_VERSION_STRING` `"5.40.0"` macro. I don't think any Linux/BSD distro has randomly decided to start patching `PERL_API_VERSION_STRING` in their system perls, in the last couple of years, so at this point in 2025, I would say to use `PERL_BCDVERSION` U32 instead here. Also this code is the REVERSE of `xs_handshake()`, the consumer and producer were flipped around. This is a `.bin` file under full end user control compiled by the end user, loading a random unknown `libperl.so` file into address space. The end user is using the cryptographic-ally secure P5P code base (aka `git` + SSL + `github.com`), the end user didn't checkout the patched system perl and its exact `Configure` settings from their Distro vendor (canonical)'s RCS. So P5P codebase and the end user's fork of the P5P repo, have no reason to change macro `PERL_API_VERSION_STRING` to `"5.40.0-mipsle-muscl-no_afferoabi"` for some real or imaginary engineering reason.

15 minutes after I speak of the devil, and the devil himself appears in production perl code. See this ticket.

https://github.com/Perl/perl5/issues/23355

Someone was NOT USING the cryptographically signed .git P5P's Perl code base, but their vendor's [`Fedora 501(c)(3) LLC`] cryptographically signed .git repo that is a fork of P5P codebase, to do their own personal Perl interp core hacking adventures. And then they ran into problems using the code base of `Fedora`'s fork of Perl 5 code base, then came to this GH, looking for help, for a fork of Perl that P5P isn't responsible for. Out of civility, P5P volunteers will obviously offer advice to that person, even though P5P is not legally responsible for a Linux Distro's vendor patches to mainline Perl 5 VM. But still, 15 mins ago I said nobody will ever do that, and someone just did that.

**Comment by iabyn** [comment]
Note that Embed.t fails similarly on FreeBSD with useshrplib=true

**Comment by tonycoz** [comment]
> Note that Embed.t fails similarly on FreeBSD with useshrplib=true

```
LD_LIBRARY_PATH=/usr/home/tony/dev/perl/git/perl ./runtests choose
t/../lib/ExtUtils/t/Embed ... ok
All tests successful.
Elapsed: 1 sec
u=0.00  s=0.01  cu=0.13  cs=0.27  scripts=1  tests=10
$ grep useshrplib config.sh
config_args='-des -Dusedevel -Duseshrplib -Dusethreads'
config_arg3='-Duseshrplib'
useshrplib='true'
$ uname -a
FreeBSD freebsd12 13.1-RELEASE-p3 FreeBSD 13.1-RELEASE-p3 GENERIC amd64
```

Can you be more specific?  blead works for me

**Comment by iabyn** [comment]
On Wed, Jul 23, 2025 at 05:34:36PM -0700, Tony Cook wrote:
> Can you be more specific?  blead works for me

This was just something I noticed in passing while trying to reproduce the
DBI failures, so I haven't looked closely. But:

$ uname -a
FreeBSD perlmonger.nycbug.org 14.2-RELEASE-p1 FreeBSD 14.2-RELEASE-p1 GENERIC amd64
$ env | grep LD_
$ env | grep PERL
$ echo $PATH
/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/davem/bin
$

then with a freshly untarred perl-5.43.1.tar.gz and the following build
script:

```
#!/bin/sh

PP=5.43
PPP=5.43.1

OUT=/home/davem/dbi_issue/perl-$PPP

( sh Configure  \
-Dusedevel \
-Darchlib=$OUT/lib/perl-$PP/mach -Dcc=cc -Dinc_version_list=none -Dlibperl=libperl.so.$PPP -Dman1dir=$OUT/lib/perl5/$PP/perl/man/man1 -Dman3dir=$OUT/lib/perl5/$PP/perl/man/man3 -Dprefix=$OUT -Dprivlib=$OUT/lib/perl5/$PP -Dscriptdir=$OUT/bin -Dsitearch=$OUT/lib/perl5/site_perl/mach/$PP -Dsitelib=$OUT/lib/perl5/site_perl -Dsiteman1dir=$OUT/lib/perl5/site_perl/man/man1 -Dsiteman3dir=$OUT/lib/perl5/site_perl/man/man3 -Dusenm=n -Duseshrplib -sde -Ui_iconv -Ui_malloc -Uinstallusrbinperl -Alddlflags="-L$OUT/lib/perl5/$PP/mach/CORE" -Dshrpldflags='-Wl,-soname,$(LIBPERL:R)' -Doptimize='-g -pipe -fstack-protector-strong -fno-strict-aliasing' -Dusedtrace -Ui_gdbm -Dusemultiplicity=y -Duse64bitint -Dusemymalloc=n -Dusethreads=y -Dversiononly -Accflags='-DDEBUGGING -ggdb' && \
    TEST_JOBS=4  HARNESS_OPTIONS=j4  make  -j 4 test_harness &&          \
    make  -j 4 install                                                   \
) > stdout.log 2> stderr.log
```

I get:

../lib/ExtUtils/t/Embed.t                                          (Wstat: 0 Tests: 2 Failed: 2)
  Failed tests:  1, 10



-- 
Diplomacy is telling someone to go to hell in such a way that they'll
look forward to the trip

**Comment by tonycoz** [comment]
From what I can see that requires the `-Dlibperl=libperl.so.$PPP` for the test to fail, and causes problems on Linux too.

But it looks like the fix is similar - skipping `-lperl` and linking directly to $libperl

Setting libperl like that seems like it would cause other problems, from what I can tell from Configure any system that uses any of these from Configure:
```
	cygwin*)
		shrpldflags="$shrpldflags -Wl,--out-implib=libperl.dll.a"
...
		linklibperl="-L. -lperl"
		;;
	sunos*)
		linklibperl="-lperl"
		;;
	netbsd*|freebsd[234]*|openbsd*|dragonfly*|bitrig*)
		linklibperl="-L. -lperl"
		;;
	interix*)
		linklibperl="-L. -lperl"
		shrpldflags="$shrpldflags -Wl,--image-base,0x57000000"
		;;
```
if going to fail to link ./perl (or link to the wrong library).

eg. on DragonflyBSD:
```
LD_LIBRARY_PATH=/home/tony/dev/perl/git/perl ./miniperl -Ilib make_ext.pl DynaLoader.o  MAKE="make" LIBPERL_A=libperl.so.5.43.2 LINKTYPE=static 
cc -o perl -Wl,-E  -fstack-protector-strong -L/usr/local/lib -Wl,-R/usr/local/lib/perl5/5.43.2/x86_64-dragonfly/CORE perlmain.o   -L. -lperl `cat ext.libs` -lpthread -ldl -lm -lcrypt -lutil -lc
/usr/libexec/binutils234/elf/ld.gold: error: cannot find -lperl
perlmain.o:perlmain.c:function xs_init: error: undefined reference to 'boot_DynaLoader'
perlmain.o:perlmain.c:function xs_init: error: undefined reference to 'Perl_newXS'
...
perlmain.o:perlmain.c:function main: error: undefined reference to 'perl_run'
collect2: error: ld returned 1 exit status
*** Error code 1

Stop.
make: stopped in /home/tony/dev/perl/git/perl
```

**Comment by khwilliamson** [comment]
I don't have any expertise in this area, but to reiterate what @iabyn said in #22125, is this p.r. ready to merge?

**Comment by jkeenan** [comment]
> I don't have any expertise in this area, but to reiterate what @iabyn said in #22125, is this p.r. ready to merge?

I no longer have access to an OpenBSD VM, so unfortunately I'm not in a position to make a recommendation on this.  I think it's up to @afresh1 and @tonycoz .

**Comment by tonycoz** [comment]
I think it's fine to merge.

Though the Embed.t test isn't failing on the current BSD smokers in blead. so it may only be useful for older OpenBSDs.

**Comment by afresh1** [comment]
Don't seem to get Embed failures in this branch:

```
$ ./perl -Ilib -V:config_args
config_args='-des -Dusedevel -Dcc=gcc -Accflags=-DPERL_RC_STACK -DDEBUG_LEAKING_SCALARS';
```

```
Failed 1 test out of 2688, 99.96% okay.
        porting/authors.t
```
