### PR TITLE
fix trim() handling of TARG (and minor refactor)

### LINKED ISSUE #22784: builtin::trim return value numifies incorrectly in a loop
**Description**
When used in a foreach loop, builtin::trim returns the same PV in subsequent iterations which then numifies to the same IV as in the first loop even though the PV has changed.

Reported by damien on IRC

**Steps to Reproduce**

    perl -Mv5.40 -MDevel::Peek -E'for my $i ("4" .. "5") { Dump builtin::trim($i); Dump 0+builtin::trim($i) }'

```
SV = PV(0xd61dbc0) at 0xd65ba58
  REFCNT = 1
  FLAGS = (PADTMP,POK,pPOK)
  PV = 0xd5cce70 "4"\0
  CUR = 1
  LEN = 16
SV = IV(0xd65b970) at 0xd65b980
  REFCNT = 1
  FLAGS = (PADTMP,IOK,pIOK)
  IV = 4
SV = PV(0xd61dbc0) at 0xd65ba58
  REFCNT = 1
  FLAGS = (PADTMP,POK,pPOK)
  PV = 0xd5cce70 "5"\0
  CUR = 1
  LEN = 16
SV = IV(0xd65b970) at 0xd65b980
  REFCNT = 1
  FLAGS = (PADTMP,IOK,pIOK)
  IV = 4
```

**Expected behavior**
outputting a PV  of '4', IV of 4, PV of '5', and IV of 5

**Perl configuration**

```
Summary of my perl5 (revision 5 version 40 subversion 0) configuration:
   
  Platform:
    osname=linux
    osvers=6.3.8-200.fc38.x86_64
    archname=x86_64-linux
    uname='linux home.grinnz.com 6.3.8-200.fc38.x86_64 #1 smp preempt_dynamic thu jun 15 02:15:40 utc 2023 x86_64 gnulinux '
    config_args='-Dprefix=/home/grinnz/.plenv/versions/5.40.0 -de -Dversiononly -A'eval:scriptdir=/home/grinnz/.plenv/versions/5.40.0/bin''
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='13.2.1 20231011 (Red Hat 13.2.1-4)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib /usr/lib64 /usr/local/lib64
    libs=-lpthread -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/../lib64/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.37'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'
 
 
Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Jun 10 2024 21:21:12
  @INC:
    /home/grinnz/.plenv/versions/5.40.0/lib/perl5/site_perl/5.40.0/x86_64-linux
    /home/grinnz/.plenv/versions/5.40.0/lib/perl5/site_perl/5.40.0
    /home/grinnz/.plenv/versions/5.40.0/lib/perl5/5.40.0/x86_64-linux
    /home/grinnz/.plenv/versions/5.40.0/lib/perl5/5.40.0
```

### PR DESCRIPTION
**Pull request by tonycoz**
Fix mishandling of re-use of TARG in trim.

Fixes #22784 

Note that this code could simply have done sv_setpvn(), but trim() goes it's own way in handling taint, inconsistent with the rest of perl, as implemented by sv_setpvn(), so we see this bug.

I did consider just replacing this code with sv_setpvn(), but I don't know if the difference from normal perl taint usage was intentional, I didn't see any mention of it in #19433, the PR that added trim().

---------------------------------------------------------------------------------
* This set of changes requires a perldelta entry, and it is included.

perldelta:
```
builtin::trim() didn't properly clear C<TARG> which could result in out of date cached numeric versions of the value
being used on a second evaluation.  Properly clear any cached values. [GH #22784]
```

### CODE REVIEW

**Comment by richardleach** [comment]
Should `builtin::trim()` do some flavour of `SV_CHECK_THINKFIRST(TARG)`?

I'm wondering if the likes of this could happen:
* Say you have something like: `foreach my $i (@strs) { $i = trim $i }`
* Assume that in an iteration, the `TARG`'s PV buffer finds itself in the sweet zone for COW, so `sassign` COWs `TARG`'s buffer
* On the next iteration, the shared buffer will get clobbered

**Comment by tonycoz** [comment]
> Should `builtin::trim()` do some flavour of `SV_CHECK_THINKFIRST(TARG)`?

I think you're right, though I didn't come up with a test case off hand.

And of course sv_setpvn() would fix it.

**Comment by richardleach** [comment]
> Should `builtin::trim()` do some flavour of `SV_CHECK_THINKFIRST(TARG)`?

Hmm, I couldn't come up with a test case either. Quickly looking at Perl_sv_setsv_flags, maybe it will always either swipe the buffer or copy it, never COW? Even if so, may be worth guarding against that logic ever changing.

**Comment by leonerd** [comment]
> I did consider just replacing this code with sv_setpvn(), but I don't know if the difference from normal perl taint usage was intentional, I didn't see any mention of it in #19433, the PR that added trim().

I don't believe there's any reason for `trim()` to taint differently, no.

File: builtin.c [hunk 1]
```diff
@@ -273,33 +272,26 @@ XS(XS_builtin_trim)
         }
     }
 
-    dest = TARG;
+    SV_CHECK_THINKFIRST(TARG);
+    SvUPGRADE(TARG, SVt_PV);
+    SvGROW(TARG, len + 1);
```
Comment (leonerd) [inline builtin.c]: Is grow required here? Fairly sure that trim can't make an SV bigger, only smaller, so surely it must already have enough storage for the new size.

File: builtin.c [hunk 2]
```diff
@@ -273,33 +272,26 @@ XS(XS_builtin_trim)
...
-    }
-    else {
-        SvUPGRADE(dest, SVt_PV);
-        SvGROW(dest, len + 1);
-
-        Copy(start, SvPVX(dest), len, U8);
-        SvPVX(dest)[len] = '\0';
-        SvPOK_on(dest);
-        SvCUR_set(dest, len);
+    Copy(start, SvPVX(TARG), len, U8);
```
Comment (leonerd) [inline builtin.c]: Is `start` always still valid after the THINKFIRST? Is it possible that could copy out a CoW string to a new buffer?

Oh but then I suppose `start` will still point at the original untouched buffer so it's probably all fine.

File: builtin.c (hunk 1 above)
Comment (tonycoz) [reply builtin.c]: TARG and source are not the same SV.

If this were a pp func and implemented TARGLEX, then we'd retain the branch I removed and do some special handling for that.

But it's XS, so `TARG` shouldn't be `source` (though source might be the TARG from another entersub calling trim, or from the same entersub in recursion, in either case it's not the TARG here.

I tried adding an assert(0) to the original "same SV" handling code and it never triggered.

File: builtin.c (hunk 2 above)
Comment (tonycoz) [reply builtin.c]: > Oh but then I suppose `start` will still point at the original untouched buffer so it's probably all fine.

That's what I expect.

**Comment by tonycoz** [comment]
I expect to squash this before merging.

File: builtin.c (hunk 1 above)
Comment (leonerd) [reply builtin.c]: Ohright of course, this isn't an in-place trim, it's a substr copy.

**Review by leonerd — APPROVED** [review]
LGTM.

Fixes a whole lot of issues, and simplifies much of the logic.

File: builtin.c (hunk 2 above)
Comment (bulk88) [reply builtin.c]: About https://github.com/Perl/perl5/commit/4539fb8c81b73cb8057859ccab110502c1db28b3 

Not saying the fix in blead/this ticket is wrong, but there might a better way to do it, or in general for XS "do it".

Note the old code removed in this commit used the *VERY* underused (core/cpan) SvOOK flag optimization. The new code does not have `sv_chop()` optimization to prevent double buffering and maybe a trip through `re/malloc()`. 

The 5.25 newish `sv_set_undef()` to get a no-leak SvOK_off() then sv_chop(), or SvCUR() lowering, which is changing 1 or 2 integers only, vs Move()/memcpy(), is the better implementation for white space trimming a string. Perl has the API to do it efficiently (string manipulation), SvOOK needs to be used more often by the community.

Comment (tonycoz) [reply builtin.c]: > Note the old code removed in this commit used the VERY underused (core/cpan) SvOOK flag optimization. The new code does not have sv_chop() optimization to prevent double buffering and maybe a trip through re/malloc().

The sv_chop() branch was removed because the input and output SVs are never the same SV.

> The 5.25 newish sv_set_undef() ...

I have a [clang-tidy check for that](https://github.com/tonycoz/perl-check#perl-check) (though I believe loadable clang-tidy checks don't work on Windows).

Comment (bulk88) [reply builtin.c]: Can you discreetly slip that magic potion into EU::ParseXS when nobody is looking??!?!  :pleading_face:

Comment (tonycoz) [reply builtin.c]: I expect most of the API use comes from the `typemap`.

It can be run on the generated XS code, in pretty much the same way you use it on the perl sources, though it may point you at APIs that aren't covered by `ppport.h` and so won't work with older perls.
