### PR TITLE
Fix function calls being misinterpreted as bareword filehandles

### LINKED ISSUE #19271: Functions treated as bareword filehandles under `no feature 'bareword_filehandles';`
**Description**

When the `bareword_filehandles` feature is disabled (e.g. in the `:5.36` feature bundle as of v5.35.6), having a function call as the first argument to an operator that takes a filehandle erroneously complains about bareword filehandles not being allowed.

**Steps to Reproduce**

```
~/src/perl (blead $)$ ./perl -Ilib -M-feature=bareword_filehandles -le 'sub foo { shift } print foo("bar")'
Bareword filehandle "foo" not allowed under 'no feature "bareword_filehandles"' at -e line 1.
Execution of -e aborted due to compilation errors.
```

**Expected behavior**

The return value of the function is printed, like without the feature disabled:

```
~/src/perl (blead $)$ ./perl -Ilib -Mfeature=bareword_filehandles -le 'sub foo { shift } print foo("bar")'
bar
```

**Perl configuration**

```
~/src/perl (blead $)$ ./perl -V
Can't locate Config.pm in @INC (you may need to install the Config module) (@INC contains: /home/ilmari/.perlbrew/libs/34.0@std/lib/perl5/x86_64-linux /home/ilmari/.perlbrew/libs/34.0@std/lib/perl5 /usr/local/lib/perl5/site_perl/5.35.7/x86_64-linux /usr/local/lib/perl5/site_perl/5.35.7 /usr/local/lib/perl5/5.35.7/x86_64-linux /usr/local/lib/perl5/5.35.7).
BEGIN failed--compilation aborted.
ilmari@ilmari-thinkpad:~/src/perl (blead $)$ ./perl -Ilib -V
Summary of my perl5 (revision 5 version 35 subversion 7) configuration:
  Commit id: 0a91ad7bad09fcaf7a49940068a65ce44e753743
  Platform:
    osname=linux
    osvers=5.10.0-8-amd64
    archname=x86_64-linux
    uname='linux ilmari-thinkpad 5.10.0-8-amd64 #1 smp debian 5.10.46-4 (2021-08-03) x86_64 gnulinux '
    config_args='-des -Dusedevel'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='10.2.1 20210110'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib
    libs=-lpthread -lnsl -lgdbm -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.31.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.31'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Dec 10 2021 14:15:15
  %ENV:
    PERL5LIB="/home/ilmari/.perlbrew/libs/34.0@std/lib/perl5"
    PERLBREW_HOME="/home/ilmari/.perlbrew"
    PERLBREW_LIB="std"
    PERLBREW_MANPATH="/home/ilmari/.perlbrew/libs/34.0@std/man:/home/ilmari/perl5/perlbrew/perls/34.0/man"
    PERLBREW_PATH="/home/ilmari/.perlbrew/libs/34.0@std/bin:/home/ilmari/perl5/perlbrew/bin:/home/ilmari/perl5/perlbrew/perls/34.0/bin"
    PERLBREW_PERL="34.0"
    PERLBREW_ROOT="/home/ilmari/perl5/perlbrew"
    PERLBREW_SHELLRC_VERSION="0.82"
    PERLBREW_VERSION="0.91"
    PERL_LOCAL_LIB_ROOT="/home/ilmari/.perlbrew/libs/34.0@std"
    PERL_MB_OPT="--install_base /home/ilmari/.perlbrew/libs/34.0@std"
    PERL_MM_OPT="INSTALL_BASE=/home/ilmari/.perlbrew/libs/34.0@std"
  @INC:
    lib
    /home/ilmari/.perlbrew/libs/34.0@std/lib/perl5/x86_64-linux
    /home/ilmari/.perlbrew/libs/34.0@std/lib/perl5
    /usr/local/lib/perl5/site_perl/5.35.7/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.35.7
    /usr/local/lib/perl5/5.35.7/x86_64-linux
    /usr/local/lib/perl5/5.35.7
```

### PR DESCRIPTION
**Pull request by ilmari**
When bareword filehandles are disabled, the parser was interpreting
any bareword as a filehandle, even when immediatey followed by parens:

    $ perl -M-feature=bareword_filehandles -le 'print foo()'
    Bareword filehandle "foo" not allowed under 'no feature "bareword_filehandles"' at -e line 1.

While with the feature enabled, it works and prints the value returned
by the function:

    $ perl  -le 'sub foo { @_ } print foo("bar")'
    bar

As for filehandles versus functions, a space before the parens makes
the difference:

    $ perl -le 'print STDOUT ("bar")'
    bar
    $ perl -le 'print STDOUT("bar")'
    Undefined subroutine &main::STDOUT called at -e line 1.

This fixes the bug by using the already-existing "immediate_paren"
variable to make it consistent when the feature is disabled.

Fixes #19271

### CODE REVIEW

File: toke.c [hunk 1]
```diff
@@ -7620,6 +7620,7 @@ yyl_just_a_word(pTHX_ char *s, STRLEN len, I32 orig_keyword, struct code c)
         s = SvPVX(PL_linestr) + s_off;
 
         if (((PL_opargs[PL_last_lop_op] >> OASHIFT) & 7) == OA_FILEREF
+            && !immediate_paren
             && !FEATURE_BAREWORD_FILEHANDLES_IS_ENABLED) {
             no_bareword_filehandle(PL_tokenbuf);
```
Comment (tonycoz) [inline toke.c]: adding `&& !c.cv` seems to fix the other problem.

Comment (ilmari) [reply toke.c]: Thanks, done.

**Review by tonycoz — APPROVED** [review]
