### PR TITLE
Mark svpv_buf as uninitialized to avoid performance regression

### LINKED ISSUE #24317: [core-perf] `pp_multiconcat()` has perf overhead when compiled with `-ftrivial-auto-var-init=zero`
**Description**

There is a performance bug when Perl is built with the `-ftrivial-auto-var-init=zero` compiler option, available since GCC 12.

For context: I was looking into different compiler hardening flags, please see https://github.com/ossf/wg-best-practices-os-developers/issues/245

**Steps to Reproduce**

- I used [the latest commit](https://github.com/Perl/perl5/commit/ef53bc6892cb851320be193e8cd9b15b2494e24c) in the `blead` development branch.
- I used a particular [test `benchmarks/string/ipol.t`](https://github.com/briandfoy/perlbench/blob/master/benchmarks/string/ipol.t) from the [`perlbench` benchmark suite](https://github.com/briandfoy/perlbench)
- I used the Amazon Linux 2023 Docker container, but this can be similarly reproduced in e.g. Fedora

```bash
# relax seccomp to be able to run `perf`
docker run --security-opt seccomp=unconfined --rm -it amazonlinux:2023 /bin/bash

# --- in docker container -->

dnf install -y gcc14 perf git vim make strace perl-Sys-Hostname

git clone https://github.com/Perl/perl5.git
cd perl5/

git show --format=medium -s
# commit ef53bc6892cb851320be193e8cd9b15b2494e24c (HEAD -> blead, origin/blead, origin/HEAD)
# Author: Eric Herman <eric@freesa.org>
# Date:   Mon Mar 23 09:58:11 2026 +0100
#
#     update Module CoreList

# VANILLA PERL
./Configure -des -Dusedevel -DDEBUGGING=-g -Dcc=gcc14-gcc -Dprefix=$PWD/vanilla-perl
make -j && make install

# SLOW PERL: with `-ftrivial-auto-var-init=zero`
make distclean
./Configure -des -Dccflags="-ftrivial-auto-var-init=zero" -Dusedevel -DDEBUGGING=-g -Dcc=gcc14-gcc -Dprefix=$PWD/slow-perl
make -j && make install

# LET'S TEST
git clone https://github.com/briandfoy/perlbench
cd perlbench/
chmod +x perlbench-run

PERL5LIB="$(pwd)" ./perlbench-run -t ipol ../vanilla-perl/bin/perl5.43.10 ../slow-perl/bin/perl5.43.10
```

The result of running perlbench on my local machine:
```
A) perl-5
        version     = 5.04301
        git-version = v5.43.9-12-gef53bc6892
        path        = ../vanilla-perl/bin/perl5.43.10
        ccflags     = -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2

B) perl-5
        version     = 5.04301
        git-version = v5.43.9-12-gef53bc6892
        path        = ../slow-perl/bin/perl5.43.10
        ccflags     = -ftrivial-auto-var-init=zero -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2

                           A       B
                         ---     ---
string/ipol              100      87
```

**Expected behavior**

The above scores -- 87 vs 100 -- show runtime overhead of ~13%. On other machines/environments, I observed as much as 29%.

**Root causing with `perf`**

TLDR:
- Problematic declaration of local array on stack in `pp_multiconcat()`: [`svpv_buf[PERL_MULTICONCAT_MAXARG]`](https://github.com/Perl/perl5/blob/ef53bc6892cb851320be193e8cd9b15b2494e24c/pp_hot.c#L710)  
- This is a rather large array: [`#define PERL_MULTICONCAT_MAXARG 64`](https://github.com/Perl/perl5/blob/ef53bc6892cb851320be193e8cd9b15b2494e24c/perl.h#L1540)
- This is in the hot function, so with `-ftrivial-auto-var-init=zero`, initializing this array to zero leads to high perf overhead.

For profiling, I ran this:
```bash
# VANILLA PERL
PERL5LIB="$(pwd)" perf record -g --call-graph dwarf -- \
  ../vanilla-perl/bin/perl5.43.10 benchmarks/string/ipol.t 2800984 37817066
perf report --children

# SLOW PERL
PERL5LIB="$(pwd)" perf record -g --call-graph dwarf -- \
  ../slow-perl/bin/perl5.43.10 benchmarks/string/ipol.t 2800984 37817066
perf report --children
```

The results are like this:
```
# VANILLA

-   99.99%     0.00%  perl     perl                  [.] _start
   - main                                                      
      - 99.99% perl_run                                        
         - Perl_runops_standard                                
            + 36.88% Perl_pp_multiconcat                       
              17.09% Perl_pp_gvsv                              
              16.00% Perl_pp_nextstate     

/* NOTICE: no zeroing out of the svpv_buf array (i.e. no instruction `rep stos`) */

       │      svpv_buf[PERL_MULTICONCAT_MAXARG]; /* buf for storing SvPV() results */
       │                                                                             
       │      aux   = cUNOP_AUXx(PL_op)->op_aux;                                     
  1.43 │        mov      0x8(%rdi),%rax

# SLOW

-   99.99%     0.00%  perl     perl                  [.] _start  
   - main                                                        
      - 99.98% perl_run                                          
         - Perl_runops_standard                                  
            + 60.08% Perl_pp_multiconcat                         
              16.65% Perl_pp_gvsv                                
              6.08% Perl_pp_nextstate   

       │      svpv_buf[PERL_MULTICONCAT_MAXARG]; /* buf for storing SvPV() results */ 
  0.31 │        mov      %rdi,0x18(%rsp)                                              
 44.67 │        rep      stos %rax,%es:(%rdi) 
```

These results clearly indicate that the root cause of perf overhead is the `rep stos` instruction, which is inserted to initialize the `svpv_buf` array to all-zeros. Depending on the CPU, it runs slower or faster on different machines.

**Perl configuration**

```bash
$ ./vanilla-perl/bin/perl5.43.10 -V   # slow-perl is basically the same

Summary of my perl5 (revision 5 version 43 subversion 10) configuration:
  Commit id: ef53bc6892cb851320be193e8cd9b15b2494e24c
  Platform:
    osname=linux
    osvers=5.10.251-<hidden>.x86_64
    archname=x86_64-linux
    uname='linux <hidden>'
    config_args='-des -Dusedevel -DDEBUGGING=-g -Dcc=gcc14-gcc -Dprefix=/perl5/vanilla-perl'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='gcc14-gcc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2 -g'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='14.2.1 20250110 (Red Hat 14.2.1-7)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='gcc14-gcc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib /usr/lib64 /usr/local/lib64
    libs=-lpthread -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.34'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector-strong'

Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Mar 23 2026 13:40:04
  @INC:
    /perl5/vanilla-perl/lib/site_perl/5.43.10/x86_64-linux
    /perl5/vanilla-perl/lib/site_perl/5.43.10
    /perl5/vanilla-perl/lib/5.43.10/x86_64-linux
    /perl5/vanilla-perl/lib/5.43.10
```

### PR DESCRIPTION
**Pull request by dimakuv**
Fixes #24317. See details in that issue.

---

Previously, when compiling Perl with `-ftrivial-auto-var-init=zero` (on GCC14+), there was a performance regression in pp_multiconcat(). This happened because of the `svpv_buf` local array with a rather-large size, which was auto initialized to zero.

Since `svpv_buf` is used in a performance-critical path, and is used safely in the current codebase, this commit marks this array as `__attribute__((uninitialized))`. This way, even when compiled with `-ftrivial-auto-var-init=zero`, Perl still exhibits good performance.

-------------------------------------------------------------------------------

With this PR, the reproducer from #24317 doesn't have any performance overhead:

```
$ PERL5LIB="$(pwd)" ./perlbench-run -t ipol ../vanilla-perl/bin/perl5.43.10 ../slow-perl/bin/perl5.43.10

A) perl-5
        version     = 5.04301
        git-version = v5.43.9-12-gef53bc6892
        path        = ../vanilla-perl/bin/perl5.43.10
        ccflags     = -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2

B) perl-5
        version     = 5.04301
        git-version = v5.43.9-12-gef53bc6892*
        path        = ../slow-perl/bin/perl5.43.10
        ccflags     = -ftrivial-auto-var-init=zero -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2

                           A       B
                         ---     ---
string/ipol              100     103
```

### CODE REVIEW

**Comment by tonycoz** [comment]
The change looks reasonable to me and it mitigates a performance issue from an option that a reasonable security conscious vendor or user might enable. (started the workflow)

**Comment by tonycoz** [comment]
You need to `make regen` and `make test_porting`

**Comment by dimakuv** [comment]
> You need to `make regen` and `make test_porting`

Done, I didn't realize I need to do `make test_porting`. And I attributed a couple failing tests in `make test` to the peculiarities of my system... Hopefully now all tests pass.

**Comment by dimakuv** [comment]
@tonycoz Gentle ping. Is there anything else I need to do for this PR?

File: embed.h [hunk 1]
```diff
@@ -28,6 +28,7 @@
 #   undef CC_MAGICAL_
 #   undef CC_UNDERSCORE_
 #   undef do_aexec
+#   undef HASATTRIBUTE_UNINITIALIZED
```
Comment (Leont) [inline embed.h:31]: It looks to me like this line was added manually, even though this is a generated file. @khw probably knows better how to deal with this.

**Comment by Leont** [comment]
IMO this commit should be split in 3 commits:
* Add you to AUTHORS
* Add the attribute macro
* Use the attribute macro

File: embed.h (hunk 1 above)
Comment (khwilliamson) [reply embed.h:31]: The line looks to me like it was automatically generated.  The default visibility for newly minted macros is now the same as for functions, hidden outside of core.  The `undef` accomplishes this, and doesn't happen to core files.  This PR only uses this macro inside core, so everything works as-is.  It isn't a problem, and non-core code doesn't see this macro.

Comment (dimakuv) [reply embed.h:31]: Just to be clear: this line was added when I ran `make test_porting`, as mentioned in the previous comments. To be honest, I didn't know why this line was needed :)

**Comment by dimakuv** [comment]
> IMO this commit should be split in 3 commits:
> [...]

This was done now.

**Review by Leont — APPROVED** [review]
