### PR TITLE
`locale.pm`: Fix indirect syntax

### LINKED ISSUE #21596: `locale.pm`: Indirect syntax
https://github.com/Perl/perl5/blob/4b5c1775cec6d4fe978b19274b2c24098bb9f151/lib/locale.pm#L113

### PR DESCRIPTION
**Pull request by rwp0**
`POSIX` in `eval`

Fixes https://github.com/Perl/perl5/issues/21596

### CODE REVIEW

File: lib/locale.pm [hunk 1]
```diff
@@ -15,37 +15,37 @@ locale - Perl pragma to use or avoid POSIX locales for built-in operations
...
 change need not be explicit; some operations cause perl to change the
-locale itself.  You are vulnerable simply by having done a C<"use
-locale">.
+locale itself.  You are vulnerable simply by having done a C<use
+locale>.
 
 =head1 SYNOPSIS
 
-    @x = sort @y;      # Native-platform/Unicode code point sort order
+    my @x1 = sort @y;      # Native-platform/Unicode code point sort order
```
Comment (rwp0) [inline lib/locale.pm:28]: Scope variables with `my` inside Synopsis
