### PR TITLE
Prevent loop exits from unwinding the context/scope stacks beyond a call_sv for smartmatch subs and class constructors

### LINKED ISSUE #16608: Segfault when leaving smartmatch'ed sub
Migrated from [rt.perl.org#133330](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133330) (status was 'open')

Searchable as RT133330$

### PR DESCRIPTION
**Pull request by tonycoz**
smartmatch: fail to find the loop instead of crashing

dopoptoloop() or dopoptolabel() would find a loop outside the sub called from call_sv() and rewind the context and save stack to outside the context set up by call_sv(), crashes and panics ensure.

Switching stacks here also starts a new context stack, so the outer loop isn't found and we don't crash.

Most other callers to call_sv() (or call_method() etc) do the same.

I'm not entirely sure about passing flags = 1 to push_stackinfo(), this matches pp_sort, but not other callers.

Fixes #16608

class.c, injected_constructor: prevent loop exits exiting

Using last, next etc would pop the context stack to above the call_sv(), generally resulting in a crash or assertion failure.

The search the context to pop to stops at the top of the current context stack, and PUSHSTACKi() switches to a new stack, preventing the search from finding any loop outside the call_sv()

Similar to #16608

Also fixes a missing -DDEBUGGING string for PERLSI_REGCOMP

---------------------------------------------------------------------------------
* This set of changes requires a perldelta entry, and it is included.

### CODE REVIEW

**Review by Leont — APPROVED** [review]

File: class.c [hunk 1]
```diff
@@ -175,6 +175,8 @@ XS(injected_constructor)
 
     SV *self = sv_2mortal(newRV_noinc(instance));
 
+    PUSHSTACKi(PERLSI_CONSTRUCTOR);
```
Comment (Leont) [inline class.c:178]: Any particular reason for not using `push_stackinfo` here? Is that because of `SP`?

File: deb.c [hunk 2]
```diff
@@ -236,7 +236,10 @@ static const char * const si_names[] = {
     "WARNHOOK",
     "DIEHOOK",
     "REQUIRE",
-    "MULTICALL"
+    "MULTICALL",
+    "REGCOMP",
+    "SMARTMATCH",
+    "CONSTRUCTOR"
```
Comment (bulk88) [inline deb.c:242]: does dump.c need an update?

File: class.c (hunk 1 above)
Comment (tonycoz) [reply class.c:178]: Yes, for SP
