### PR TITLE
open: only treat literal undef as special

### LINKED ISSUE #22385: open unexpectedly creates temporary files with undefined variables sometimes
**Description**
`perldoc -f open`:

> As a special case the three-argument form with a read/write mode and the third argument being `undef`:
>
> ```perl
> open(my $tmp, "+>", undef) or die ...
> ```
>
> opens a filehandle to a newly created empty anonymous temporary file.  (This happens under any mode, which makes `+>` the only useful and sensible mode to use.)  You will need to `seek` to do the reading.

This feature was added in 5.8.0 and is intended to only trigger when a literal `undef` is passed as the filename. It does not happen if a variable whose contents are `undef` is used:
```
$ perl -we 'open(my $fh, "+>", my $bogus) or die $!'
Use of uninitialized value $bogus in open at -e line 1.
No such file or directory at -e line 1.
$ perl -we 'my @bogus = undef; open(my $fh, "+>", $bogus[0]) or die $!'
Use of uninitialized value $bogus[0] in open at -e line 1.
No such file or directory at -e line 1.
$ perl -we 'my %bogus = (a => undef); open(my $fh, "+>", $bogus{a}) or die $!'
Use of uninitialized value $bogus{"a"} in open at -e line 1.
No such file or directory at -e line 1.
```

**Steps to Reproduce**
However, if you use an array or hash element that doesn't exist at all (as opposed to existing but containing `undef`), the special behavior kicks in and `open` silently succeeds, creating a temp file:
```
$ perl -we 'my @bogus; open(my $fh, "+>", $bogus[0]) or die $!'
$ perl -we 'my %bogus; open(my $fh, "+>", $bogus{a}) or die $!'
$ perl -we 'open(my $fh, "+>", $ARGV[0]) or die $!'
$ 
```

Even this behavior is not entirely consistent, however. If you use a runtime call to `&CORE::open`, it starts failing again (but with duplicate warning messages for some reason):
```
$ perl -we 'my @bogus; &CORE::open(my $fh, "+>", $bogus[0]) or die $!'
Use of uninitialized value in open at -e line 1.
Use of uninitialized value in open at -e line 1.
No such file or directory at -e line 1.
$ perl -we 'my %bogus; &CORE::open(my $fh, "+>", $bogus{a}) or die $!'
Use of uninitialized value in open at -e line 1.
Use of uninitialized value in open at -e line 1.
No such file or directory at -e line 1.
```

**Expected behavior**
A call to `open` that does not pass a literal `undef`, but an element of an array or hash, should complain about the undefined value and fail. Basically like the `&CORE::open` version, but there I'd expect to see only one copy of the warning.

**Perl configuration**
```
Summary of my perl5 (revision 5 version 40 subversion 0) configuration:
   
  Platform:
    osname=linux
    osvers=6.5.0-10040-tuxedo
    archname=x86_64-linux-thread-multi-ld
    uname='linux luum 6.5.0-10040-tuxedo #44 smp preempt_dynamic wed may 8 17:36:39 utc 2024 x86_64 x86_64 x86_64 gnulinux '
    config_args='-de -Dprefix=/home/mauke/perl5/perlbrew/perls/perl-5.40.0 -Dcc=cgcc -Dman1dir=none -Dman3dir=none -Dusethreads -Duselongdouble -Aoptimize=-flto -Aeval:scriptdir=/home/mauke/perl5/perlbrew/perls/perl-5.40.0/bin'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=define
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cgcc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2 -flto'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='11.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='long double'
    nvsize=16
    Off_t='off_t'
    lseeksize=8
    alignbytes=16
    prototype=define
  Linker and Libraries:
    ld='cgcc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/x86_64-linux-gnu/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.35'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -flto -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_LONG_DOUBLE
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Jun  9 2024 23:04:17
  %ENV:
    PERLBREW_BASHRC_VERSION="0.74"
    PERLBREW_HOME="/home/mauke/.perlbrew"
    PERLBREW_MANPATH="/home/mauke/perl5/perlbrew/perls/perl-5.40.0/man"
    PERLBREW_PATH="/home/mauke/perl5/perlbrew/bin:/home/mauke/perl5/perlbrew/perls/perl-5.40.0/bin"
    PERLBREW_PERL="perl-5.40.0"
    PERLBREW_ROOT="/home/mauke/perl5/perlbrew"
    PERLBREW_VERSION="0.94"
    PERLDOC="-oman"
    PERL_UNICODE="SAL"
  @INC:
    /home/mauke/perl5/perlbrew/perls/perl-5.40.0/lib/site_perl/5.40.0/x86_64-linux-thread-multi-ld
    /home/mauke/perl5/perlbrew/perls/perl-5.40.0/lib/site_perl/5.40.0
    /home/mauke/perl5/perlbrew/perls/perl-5.40.0/lib/5.40.0/x86_64-linux-thread-multi-ld
    /home/mauke/perl5/perlbrew/perls/perl-5.40.0/lib/5.40.0
```

### PR DESCRIPTION
**Pull request by mauke**
Passing undef as the filename to open should create a temporary file. Previously, this was implemented as a simple `if (arg == &PL_sv_undef)` check. However, other operations (such as accessing non-existent array/hash elements) also return `&PL_sv_undef` directly, which `open` would then silently interpret as directions to create a temp file.

Solution: Check (at compile time) whether the filename argument is an `OP_UNDEF`, and if so, set the `OPf_SPECIAL` flag on `OP_OPEN`. At runtime, if `&PL_sv_undef` is passed but `OPf_SPECIAL` is not set, replace it by a new mortal SV, which is treated as a regular filename (that happens to be undef) by PerlIO.

(For runtime calls via `&CORE::open`, we cannot distinguish between `undef` and `delete $hash{nosuchkey}` as arguments, so to keep the `undef` case working, we always set `OPf_SPECIAL` in the generated core sub for `open`.)

This functionality probably should be a private op flag (something like `OPpUNDEF_MEANS_TEMPFILE`?), but as far as I can tell, all possible private bits are already taken in `OP_OPEN`.

Fixes #22385.

### CODE REVIEW

File: op.c [hunk 1]
```diff
@@ -15679,7 +15692,19 @@ Perl_coresub_op(pTHX_ SV * const coreargssv, const int code,
             }
             return o;
         default:
-            o = op_convert_list(opnum,OPf_SPECIAL*(opnum == OP_GLOB),argop);
+            /* For open(), OPf_SPECIAL indicates we saw a literal undef as the
+             * filename argument and thus a &PL_sv_undef argument at runtime
+             * should trigger the creation of a temp file. This is to
+             * distinguish between open(..., ..., undef) and
+             * open(..., ..., delete $hash{key}), which also passes
```
Comment (tonycoz) [inline op.c:15699]: The comments for `OPf_SPECIAL` in op.h needs to be updated to describe the usage for OP_OPEN.

Comment (mauke) [reply op.c:15699]: Thanks; done.

**Review by tonycoz — APPROVED** [review]
