### PR TITLE
sv.c: fix crash with newSVpvf("")

### LINKED ISSUE #23393: BBC: Blead breaks Net-DNS-Resolver-Unbound-1.32
Please see https://rt.cpan.org/Ticket/Display.html?id=167874
The module author writes "It appears that an empty format string now causes newSVpvf to crash." (the crash is a segfault).
The problem is now solved in a newer module version, but maybe this needs to be addressed in perl.

### PR DESCRIPTION
**Pull request by mauke**
Fixes #23393.

---------------------------------------------------------------------------------
* This set of changes does not require a perldelta entry.

### CODE REVIEW

**Review by ilmari — APPROVED** [review]

File: sv.c [hunk 1]
```diff
@@ -10004,13 +10004,12 @@ Perl_newSVpvf(pTHX_ const char *const pat, ...)
...
 {
-    SV *sv;
-
     PERL_ARGS_ASSERT_VNEWSVPVF;
 
     STRLEN patlen = strlen(pat);
 
-    sv = newSV(patlen);
+    /* newSV(0) would allocate a blank bodyless SV */
+    SV *sv = newSV(patlen ? patlen : 1);
```
Comment (Leont) [inline sv.c:10012]: Honestly, seems like we need a better API here.

**Review by Leont — APPROVED** [review]

**Comment by richardleach** [comment]
Thanks, @mauke!
