### PR TITLE
regcomp.c: Fix leak

### LINKED ISSUE #17729: Memory leak in blead regatom()
**Description**
The changes in commit 95815e9df4dca7d5909d369abff1a1c4a779de0b introduced two memory leaks to regatom().

The leaks are easy to pinpoint with a 32bit ASAN build. 

The specific lines leaking memory are https://github.com/Perl/perl5/blob/c3ac3d3a0cd6dfd27ca304bfa677a49ca62fd76d/regcomp.c#L14871 and https://github.com/Perl/perl5/blob/c3ac3d3a0cd6dfd27ca304bfa677a49ca62fd76d/regcomp.c#L14872

**Steps to Reproduce**
Configure and build blead with:
```
./Configure -des -Dusedevel -DDEBUGGING=-g -Doptimize=-O0 -Dcc=clang -Accflags="-g -O0 -m32 -fsanitize=address -fno-omit-frame-pointer" -Aldflags="-g -O0 -m32 -fsanitize=address -fno-omit-frame-pointer" -Alddlflags="-shared -g -O0 -m32 -fsanitize=address  -fno-omit-frame-pointer"
```

Example leak:
```
jd@toucan:~/src/git/lab/perl5 (blead)$ PERL5LIB=lib ./perl -e 'my $re = q<(?il)aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\p{Inf}>; eval { "" =~ /$re/ }; print $@ if $@; print "Done\n";'
Done

=================================================================
==28047==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1180 byte(s) in 1 object(s) allocated from:
    #0 0x8123735 in calloc (/home/jd/src/git/lab/perl5/perl+0x8123735)
    #1 0x86a3b3d in Perl_safesyscalloc /home/jd/src/git/lab/perl5/util.c:451:18
    #2 0x85b11ff in S_regatom /home/jd/src/git/lab/perl5/regcomp.c:14872:21
    #3 0x8557987 in S_regpiece /home/jd/src/git/lab/perl5/regcomp.c:12591:11
    #4 0x8527b46 in S_regbranch /home/jd/src/git/lab/perl5/regcomp.c:12511:18
    #5 0x849b76c in S_reg /home/jd/src/git/lab/perl5/regcomp.c:12213:10
    #6 0x843ffd1 in Perl_re_op_compile /home/jd/src/git/lab/perl5/regcomp.c:7845:9
    #7 0x895b7ff in Perl_pp_regcomp /home/jd/src/git/lab/perl5/pp_ctl.c:114:14
    #8 0x879288f in Perl_runops_standard /home/jd/src/git/lab/perl5/run.c:41:26
    #9 0x825092d in S_run_body /home/jd/src/git/lab/perl5/perl.c:2759:2
    #10 0x824e546 in perl_run /home/jd/src/git/lab/perl5/perl.c:2682:2
    #11 0x8154029 in main /home/jd/src/git/lab/perl5/perlmain.c:127:9
    #12 0xf7c1cb40 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x1ab40)

Direct leak of 295 byte(s) in 1 object(s) allocated from:
    #0 0x8123735 in calloc (/home/jd/src/git/lab/perl5/perl+0x8123735)
    #1 0x86a3b3d in Perl_safesyscalloc /home/jd/src/git/lab/perl5/util.c:451:18
    #2 0x85b11b5 in S_regatom /home/jd/src/git/lab/perl5/regcomp.c:14871:21
    #3 0x8557987 in S_regpiece /home/jd/src/git/lab/perl5/regcomp.c:12591:11
    #4 0x8527b46 in S_regbranch /home/jd/src/git/lab/perl5/regcomp.c:12511:18
    #5 0x849b76c in S_reg /home/jd/src/git/lab/perl5/regcomp.c:12213:10
    #6 0x843ffd1 in Perl_re_op_compile /home/jd/src/git/lab/perl5/regcomp.c:7845:9
    #7 0x895b7ff in Perl_pp_regcomp /home/jd/src/git/lab/perl5/pp_ctl.c:114:14
    #8 0x879288f in Perl_runops_standard /home/jd/src/git/lab/perl5/run.c:41:26
    #9 0x825092d in S_run_body /home/jd/src/git/lab/perl5/perl.c:2759:2
    #10 0x824e546 in perl_run /home/jd/src/git/lab/perl5/perl.c:2682:2
    #11 0x8154029 in main /home/jd/src/git/lab/perl5/perlmain.c:127:9
    #12 0xf7c1cb40 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x1ab40)

SUMMARY: AddressSanitizer: 1475 byte(s) leaked in 2 allocation(s).
```

**Expected behavior**
No memory leak.

**Perl configuration**
```
Summary of my perl5 (revision 5 version 31 subversion 11) configuration:
  Commit id: c3ac3d3a0cd6dfd27ca304bfa677a49ca62fd76d
  Platform:
    osname=linux
    osvers=4.19.0-8-amd64
    archname=x86_64-linux
    uname='linux toucan 4.19.0-8-amd64 #1 smp debian 4.19.98-1 (2020-01-26) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING=-g -Doptimize=-O0 -Dcc=clang -Accflags=-g -O0 -m32 -fsanitize=address -fno-omit-frame-pointer -Aldflags=-g -O0 -m32 -fsanitize=address -fno-omit-frame-pointer -Alddlflags=-shared -g -O0 -m32 -fsanitize=address  -fno-omit-frame-pointer'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=undef
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='clang'
    ccflags ='-g -O0 -m32 -fsanitize=address -fno-omit-frame-pointer -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g'
    cppflags='-g -O0 -m32 -fsanitize=address -fno-omit-frame-pointer -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Clang 7.0.1 (tags/RELEASE_701/final)'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=4
    doublesize=8
    byteorder=1234
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=12
    longdblkind=3
    ivtype='long'
    ivsize=4
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=4
    prototype=define
  Linker and Libraries:
    ld='clang'
    ldflags =' -g -O0 -m32 -fsanitize=address -fno-omit-frame-pointer -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/llvm-7/lib/clang/7.0.1/lib /usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -lgdbm -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.28.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.28'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags=' -shared -g -O0 -m32 -fsanitize=address -fno-omit-frame-pointer -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Apr 20 2020 09:18:44
  %ENV:
    PERL5LIB="lib"
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.31.11/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.31.11
    /usr/local/lib/perl5/5.31.11/x86_64-linux
    /usr/local/lib/perl5/5.31.11
```

### PR DESCRIPTION
**Pull request by khwilliamson**
This leak is the result of my misplacing the frees in an inner block
which isn't always executed after space is allocated; instead of the
next outer where the free will get done.

This fixes #17729

### CODE REVIEW

File: regcomp.c [hunk 1]
```diff
@@ -15173,9 +15173,6 @@ S_regatom(pTHX_ RExC_state_t *pRExC_state, I32 *flagp, U32 depth)
                         * have to map that back to the original */
                         if (need_to_fold_loc) {
                             upper_fill = loc_correspondence[s - s_start];
-                            Safefree(locfold_buf);
-                            Safefree(loc_correspondence);
-
                             if (upper_fill == 0) {
                                 FAIL2("panic: loc_correspondence[%d] is 0",
```
Comment (hvds) [inline regcomp.c:15177]: Are the frees not still required before the FAIL2?

**Comment by khwilliamson** [comment]
On 4/26/20 3:33 AM, Hugo van der Sanden wrote:
> *@hvds* commented on this pull request.
> 
> ------------------------------------------------------------------------
> 
> In regcomp.c 
> <https://github.com/Perl/perl5/pull/17747#discussion_r415265604>:
> 
>> -                            Safefree(locfold_buf);
> -                            Safefree(loc_correspondence);
> -
>                               if (upper_fill == 0) {
>                                   FAIL2("panic: loc_correspondence[%d] is 0",
> 
> Are the frees not still required before the FAIL2?

They are, but do we worry about leaks with panics, which by definition 
we don't think should ever happen?

**Comment by tonycoz** [comment]
> They are, but do we worry about leaks with panics, which by definition we don't think should ever happen?

If nothing else it gives static analysis tools one less thing to complain about.

The change I described in my comment moved the frees to inside the conditional for the panic.

**Comment by khwilliamson** [comment]
I am somewhat bothered by the need to add code to avoid a leak for a condition that should be impossible to happen.  That  panic is essentially an assert() with better diagnostics, and enabled even when not DEBUGGING.  There are plenty of asserts in our code that would result in leaks if they were triggered.

Could the static analyzers be told that something containing the word 'panic' should be considered unreachable?

Also, @tonycoz had an alternate approach.  Perhaps his should be used instead?

**Comment by hvds** [comment]
> I am somewhat bothered by the need to add code to avoid a leak for a condition that should be impossible to happen.

Today's impossible is very often tomorrow's normal, and somebody will realise that and change the message. Chances are they won't think at that point that someone may have left them a trap. The cost of removing that trap right now seems very small to me - certainly much smaller than discovering and removing it later.

> There are plenty of asserts in our code that would result in leaks if they were triggered.

I'm not suggesting we should drop everything to go fix them; however if we come to work on those pieces of code, I certainly hope we'd consider plugging those leaks at the same time.

**Comment by khwilliamson** [comment]
I have thought about this for a while, and I think requiring asserts and panics to clean up leaks, should they trigger, will inevitably lead to poorer code instead of better.   It feels like worrying about spilling your tea as the Titanic goes down.   I put in asserts when I'm fairly confident that the situation can't occur.  Or I want to make sure that future changes elsewhere don't impact the behavior here.  But I know that if I am supposed to analyze what could leak should the assert trigger, I am less likely to bother.  And I don't think I am lazier than most programmers.  And it is contrary to our automatic generation of asserts from the information of embed.fnc.  Those would have to be eliminated to conform.

I can see making changes because of static analyzers, just to shut them up, regardless of the merits of their complaints.  I don't have any idea if they would complain here.

**Comment by dur-randir** [comment]
There's a problem - perl doesn't have an actual universal panic. Assertions are no-op on release builds, and leaking through them will leak in production code. And all instances of croak("panic: ... are not actually enforced - it's just a plain croak with somewhat suggesting message, but it's a mere suggestion - nothing stops users from trapping them and continuing execution (and, alas, almost always successfully).

I've stumbled upon this during my fuzzer setup - it actually requires modifying source code to trap what appears to be a panic(), and even that's only a guess - there's nothing better than a substr() search.

I think that the route forward should be at least to introduce an actual panic() function into core, that terminates program regardless on compilation flags - since the interpreter has encountered an inconsistency in it's internal state.

**Comment by khwilliamson** [comment]
On 5/20/20 4:48 PM, Sergey Aleynikov wrote:
> I think that the route forward should be at least to introduce an actual 
> panic() function into core, that terminates program regardless on 
> compilation flags - since the interpreter has encountered an 
> inconsistency in it's internal state.

I think that's an excellent idea

**Comment by xsawyerx** [comment]
> There's a problem - perl doesn't have an actual universal panic. Assertions are no-op on release builds, and leaking through them will leak in production code. And all instances of croak("panic: ... are not actually enforced - it's just a plain croak with somewhat suggesting message, but it's a mere suggestion - nothing stops users from trapping them and continuing execution (and, alas, almost always successfully).
> 
> I've stumbled upon this during my fuzzer setup - it actually requires modifying source code to trap what appears to be a panic(), and even that's only a guess - there's nothing better than a substr() search.
> 
> I think that the route forward should be at least to introduce an actual panic() function into core, that terminates program regardless on compilation flags - since the interpreter has encountered an inconsistency in it's internal state.

I agree. I opened a ticket at #17802 for this. I think we can merge @khwilliamson meanwhile.

File: regcomp.c (hunk 1 above)
Comment (xsawyerx) [reply regcomp.c:15177]: (This was resolved outside the commit, within #17747.)
