### PR TITLE
Avoid unnecessary "changing use VERSION ..." message around string eval (fixes #22121)

### LINKED ISSUE #22121: Spurious "Changing use VERSION" warning for string eval in module
**Description**
The `Changing use VERSION while another use VERSION is in scope is deprecated, and will become fatal in Perl 5.46` warning triggers in cases that don't make sense. It looks like the `use VERSION` context sometimes leaks into `use`d modules that use string `eval`.

This affects CPAN modules like Data::Munge: https://rt.cpan.org/Ticket/Display.html?id=152677

**Steps to Reproduce**
Contents of `Foo.pm`:
```perl
package Foo;
use v5.14;
eval 'use v5.14';
1
```

This runs normally; no warnings:
```
$ ./perl -I. -e 'use Foo;'
$
```

This triggers a warning, but only for the eval'd code; the main module code is fine, apparently, even though both try to `use v5.14`:
```
$ ./perl -I. -e 'use v5.20; use Foo;'
Changing use VERSION while another use VERSION is in scope is deprecated, and will become fatal in Perl 5.46 at (eval 1) line 1.
```

**Expected behavior**
No warnings.

**Perl configuration**

```
Summary of my perl5 (revision 5 version 39 subversion 10) configuration:
  Commit id: 53a6f7aabfcbe508ff3e0835802d2dd2be935816
  Platform:
    osname=linux
    osvers=6.5.0-10027-tuxedo
    archname=x86_64-linux
    uname='linux luum 6.5.0-10027-tuxedo #31 smp preempt_dynamic tue mar 5 10:45:49 utc 2024 x86_64 x86_64 x86_64 gnulinux '
    config_args='-des -Dcc=cgcc -Dusedevel'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cgcc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='11.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cgcc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/x86_64-linux-gnu/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.35'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Apr  4 2024 13:00:21
  %ENV:
    PERLBREW_BASHRC_VERSION="0.74"
    PERLBREW_HOME="/home/mauke/.perlbrew"
    PERLBREW_MANPATH="/home/mauke/perl5/perlbrew/perls/perl-5.38.2/man"
    PERLBREW_PATH="/home/mauke/perl5/perlbrew/bin:/home/mauke/perl5/perlbrew/perls/perl-5.38.2/bin"
    PERLBREW_PERL="perl-5.38.2"
    PERLBREW_ROOT="/home/mauke/perl5/perlbrew"
    PERLBREW_VERSION="0.94"
    PERLDOC="-oman"
    PERL_UNICODE="SAL"
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.39.10/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.39.10
    /usr/local/lib/perl5/5.39.10/x86_64-linux
    /usr/local/lib/perl5/5.39.10
```

### PR DESCRIPTION
**Pull request by leonerd**
We need to save the value of PL_prevailing_version at the time the eval op was compiled, so it can be put in place during the running code.
    
Ideally we'd do something more robust, like change the OP_ENTERVAL op class into UNOP_AUX, so that the aux vector can store additional information like the version number and perhaps the frozen hints hash.
    
In practice it is far too close to the 5.40 release to contemplate such a change now, so this is a less intrusive but hackier change to achieve the same aim.

This is in two commits, because the first commit fixes the bug but leaves an ugly `$^H{"CORE/prevailing_version"}` in the hints hash inside a string eval. Probably not a huge disaster but it's messy. The second commit tidies that up too, but is implemented in a bit of a weird way around not triggering `PERL_MAGIC_hinthash` while deleting the key. It's not great but gets the job done.

We can discuss whether we want to merge both commits, or just one the first one.

### CODE REVIEW

**Comment by jkeenan** [comment]
Once I saw the test failures in 3 files reported by CI, I built and tested your branch on both Linux and FreeBSD.  Though the failures I got there were similar to what was reported by CI, there were some interesting differences in error output, most notably:

**Ubuntu Linux 22.04 LTS**
```
$ uname -mrs
Linux 6.5.0-28-generic x86_64

$ gcc --version
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

$ git describe;gitcurr
v5.39.9-74-g384b3bcd93
leonerd-fix-gh-22121-20240425

$ ./perl -Ilib -V:config_args
config_args='-des -Dusedevel -Duseithreads';

$ cd t;./perl harness re/pat_re_eval.t; cd -
free(): double free detected in tcache 2
re/pat_re_eval.t .. No subtests run 

Test Summary Report
-------------------
re/pat_re_eval.t (Wstat: 134 (Signal: ABRT, dumped core) Tests: 0 Failed: 0)
  Non-zero wait status: 134
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  0 wallclock secs ( 0.00 usr  0.00 sys +  0.01 cusr  0.00 csys =  0.01 CPU)
Result: FAIL
```
**FreeBSD-13**
```
$ uname -mrs
FreeBSD 13.2-RELEASE-p1 amd64

$ clang --version
FreeBSD clang version 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c)
...

$ git describe; gitcurr
v5.39.9-74-g384b3bcd93
leonerd-fix-22121-20240425

$ ./perl -Ilib -V:config_args
config_args='-des -Dusedevel -Duseithreads -Doptimize=-O2 -pipe -fstack-protector -fno-strict-aliasing';

$ cd t;./perl harness re/pat_re_eval.t; cd -
Global symbol "$t" requires explicit package name (did you forget to declare "my $t"?) at re/pat_re_eval.t line 847.
BEGIN not safe after errors--compilation aborted at re/pat_re_eval.t line 886.
re/pat_re_eval.t .. Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 

Test Summary Report
-------------------
re/pat_re_eval.t (Wstat: 512 (exited 2) Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.05 cusr  0.00 csys =  0.07 CPU)
Result: FAIL
```
Note the `free(): double free detected in tcache 2` in the error output on Linux/gcc -- not present on FreeBSD/clang.  But then on FreeBSD there's a warning that didn't appear on Linux:  `Global symbol "$t" requires explicit package name ...`

**Comment by jkeenan** [comment]
The test failures I cited last night are now PASSing.

**Comment by leonerd** [comment]
@haarg `cpan> test Moo` passed OK with this

**Comment by leonerd** [comment]
Here's some commits that attempt to fix it. See PR description for a fuller detail.

I vote we merge both, but if the second commit seems weird I'm happy to take just the first, and we'll document the weirdness. Somewhere.

File: pp_ctl.c [hunk 1]
```diff
@@ -4076,6 +4077,18 @@ S_doeval_compile(pTHX_ U8 gimme, CV* outside, U32 seq, HV *hh)
             SvREFCNT_dec(GvHV(PL_hintgv));
             GvHV(PL_hintgv) = hh;
             FETCHFEATUREBITSHH(hh);
+            /* temporarily turn magical flags off so we can delete without it getting in the way */
+            U32 wasflags = SvFLAGS(hh);
```
Comment (mauke) [inline pp_ctl.c]: I'd make that `const`.

**Comment by mauke** [comment]
I don't completely understand the ramifications of the code change, but it looks plausible to me and fixes the problem in my tests. So I'd say merge it.
