### PR TITLE
Expose some op related APIs

### LINKED ISSUE #23676: BBC: Blead Breaks IO::ExplicitHandle
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.43 running under perl 5.43.3.

-----------------------------------------------------------------

BBC: Blead Breaks IO::ExplicitHandle

Please see https://fast2-matrix.cpantesters.org/?dist=IO-ExplicitHandle-0.002

---
**Flags**
- category=core
- severity=low
---
**Perl configuration**
```
Site configuration information for perl 5.43.3:

Configured by cpan at Wed Sep  3 02:37:28 EDT 2025.

Summary of my perl5 (revision 5 version 43 subversion 3) configuration:
  Commit id: bb13a224451c8fbf0b9600bbc3d58cad55b3aec9
  Platform:
    osname=linux
    osvers=6.12.0-55.29.1.el10_0.x86_64
    archname=x86_64-linux
    uname='linux cjg-rhel10 6.12.0-55.29.1.el10_0.x86_64 #1 smp preempt_dynamic mon aug 18 05:37:24 edt 2025 x86_64 gnulinux '
    config_args='-des -Dprefix=/home/cpan/bin/perl -Dscriptdir=/home/cpan/bin/perl/bin -Dusedevel -Duse64bitall'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='14.2.1 20250110 (Red Hat 14.2.1-7)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib /usr/lib64 /usr/local/lib64
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/../lib64/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.39'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


---
@INC for perl 5.43.3:
    /home/cpan/bin/perl/lib/site_perl/5.43.3/x86_64-linux
    /home/cpan/bin/perl/lib/site_perl/5.43.3
    /home/cpan/bin/perl/lib/5.43.3/x86_64-linux
    /home/cpan/bin/perl/lib/5.43.3

---
Environment for perl 5.43.3:
    HOME=/home/cpan
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_ALL=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl/bin:/home/cpan/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
    PERL_BADLANG (unset)
    SHELL=/bin/bash
```

### PR DESCRIPTION
**Pull request by tonycoz**
Expose qerror() and op_clear() to the API and document them.

Fixes #23676 

-------------------------------------------------------------------------------

* This set of changes requires a perldelta entry, and I haven't written it yet. (PR so I can comment in #23676)

### CODE REVIEW

**Review by leonerd — COMMENTED** [review]
I was thinking about this while triaging the list for release blockers. It does make sense to expose a function with `qerror`'s behaviour, though I'm not sure if this name is best. We could pick a better name for it, though then that does mean all the modules currently using it will have to change anyway.

**Review by khwilliamson — APPROVED** [review]
Do we want to hedge our bets by marking any of these as experimental?

**Comment by khwilliamson** [comment]
> We could pick a better name for it, though then that does mean all the modules currently using it will have to change anyway.

We could make qerror a synonym for the better name, and mark qerror as C visibility instead of A visibility.  This is all now trivial

**Comment by tonycoz** [comment]
> I'm not sure if this name is best.

It is the name we have and it is the name used by Devel::CallParser, IO::ExplicitHandle, Sub::StrictDecl

Otherwise someone will need to adopt them (they are all by Zefram) and release fixes.

**Comment by jkeenan** [comment]
Locally on Linux I built an unthreaded perl from the branch in this p.r., compiled with `gcc-14`.  Then I attempted to install all 5 modules cited in https://github.com/Perl/perl5/issues/23676.  All 5 were successfully installed.
```
[gh-24335-tonycoz-23676-op-parser-20260330] 2079 $ ./bin/perl -Ilib -V:cc
cc='gcc-14';
$ ./bin/perl -Ilib -MIO::ExplicitHandle -E 'say STDOUT $IO::ExplicitHandle::VERSION'; \
./bin/perl -Ilib -MDevel::CallParser -E 'say $Devel::CallParser::VERSION;'; \
./bin/perl -Ilib -MDevel::GoFaster -E 'say $Devel::GoFaster::VERSION;'; \
./bin/perl -Ilib -MSub::StrictDecl -E 'say $Sub::StrictDecl::VERSION;'; \
./bin/perl -Ilib -MData::Alias -E 'say $Data::Alias::VERSION;'
0.002
0.002
0.001
0.005
1.30
```

**Comment by ap** [comment]
@khwilliamson

> We could make qerror a synonym for the better name, and mark qerror as C visibility instead of A visibility. This is all now trivial

Yeah, exposing a better name but keeping the old name around for backcompat was the general approach I was thinking of too. I don’t know enough about the visibility setting to judge it accurately, but that also sounds reasonable based on my faint understanding.

@tonycoz

> Otherwise someone will need to adopt them (they are all by Zefram) and release fixes.

If we can keep downstreams working without them having to be patched, we should. Sometimes that’s expensive, and then a judgement needs to be rendered, but I don’t see that here.

**Comment by tonycoz** [comment]
Any ideas on a name? `queue_error()`?

**Comment by Leont** [comment]
> Yeah, exposing a better name but keeping the old name around for backcompat was the general approach I was thinking of too. I don’t know enough about the visibility setting to judge it accurately, but that also sounds reasonable based on my faint understanding.

But lets please mark it as deprecated, so that we can hopefully remove it at a later time. `qerror` is an uncomfortably short name, and there's a real chance it will clash with external code.

**Comment by khwilliamson** [comment]
I think "queuing" doesn't adequately express what the function does.  I like the name someone came up with for a perl script, `die_at_end`.  I think that name is closer, but still not good enough.  Maybe something with `defer` in it.

**Comment by khwilliamson** [comment]
How about `defer_error`

**Comment by leonerd** [comment]
> How about `defer_error`

Sounds good

**Comment by Leont** [comment]
> It is the name we have and it is the name used by Devel::CallParser, IO::ExplicitHandle, Sub::StrictDecl
> 
> Otherwise someone will need to adopt them (they are all by Zefram) and release fixes.

It appears Devel::CallParser has been adopted now by LNATION.

**Comment by ap** [comment]
This addresses #23676, which is (now) a blocker. We are not waiting for next cycle.

File: op.c [hunk 1]
```diff
@@ -1100,6 +1100,15 @@ void S_op_clear_gv(pTHX_ OP *o, SV**svp)
     }
 }
 
+/*
+=for apidoc op_clear
+
+Clean up anything allocated for an OP, except the OP itself.
+
+You may want to use op_null() or op_free() instead.
```
Comment (khwilliamson) [inline op.c]: Suggest `You may want to use L<C<op_null()>|/op_null> or L<C<op_free()>|/op_free> instead.`
(untested)

File: util.h [hunk 2]
```diff
@@ -23,6 +23,18 @@
 #  define Perl_die_nocontext  Perl_die
 #endif
 
+/*
+=for apidoc_section $warning
+
+=for apidoc qerror
+
+An alias for L</defer_error>.
```
Comment (khwilliamson) [inline util.h]: s/An/A deprecated/

File: pod/perldelta.pod [hunk 3]
```diff
@@ -376,7 +376,20 @@ to tied hashes in list assignments.
 
 =item *
 
-XXX
+L<perlapi/defer_error>, formerly known as C<qerror>, and
+L<perlapi/op_clear> are now part of the API.
+
+Perl 5.43.2 hid Perl non-API function declarations unless you defined
+C<PERL_EXT> or C<PERL_CORE>, so these non-API functions were no longer
+has visible declarations.
```
Comment (khwilliamson) [inline pod/perldelta.pod]: I don't understand `has visible` here

File: embed.fnc [hunk 4]
```diff
@@ -1170,6 +1170,9 @@ Cp	|I32	|debstackptrs
 p	|void	|debug_hash_seed|bool via_debug_h
 Rp	|SV *	|defelem_target |NN SV *sv				\
 				|NULLOK MAGIC *mg
+: FIXME - either make it public, or stop exporting it. (Data::Alias uses this)
```
Comment (khwilliamson) [inline embed.fnc]: Can't this comment now  be deleted?

File: embed.fnc [hunk 5]
```diff
@@ -2853,7 +2853,7 @@ Adp	|char * |pv_uni_display |NN SV *dsv				\
 				|UV flags
 : FIXME - either make it public, or stop exporting it. (Data::Alias uses this)
```
Comment (khwilliamson) [inline embed.fnc]: Can't this comment now be deleted?

File: embed.fnc [hunk 6]
```diff
@@ -2606,7 +2606,7 @@ Adp	|OP *	|op_append_list |I32 optype				\
 				|NULLOK OP *last
 Adp	|OPclass|op_class	|NULLOK const OP *o
 : FIXME. Used by Data::Alias
```
Comment (khwilliamson) [inline embed.fnc]: Can't this comment now be deleted?

File: embed.fnc [hunk 7]
```diff
@@ -2853,7 +2853,7 @@ Adp	|char * |pv_uni_display |NN SV *dsv				\
 				|UV flags
 : FIXME - either make it public, or stop exporting it. (Data::Alias uses this)
 : Used in gv.c, op.c, toke.c
```
Comment (khwilliamson) [inline embed.fnc]: And this comment.  I don't see what advantage it gives.  It looks to me like something that could readily become outdated, and so mislead.  Maybe it already is.  But maybe I'm overlooking something

File: pp_ctl.c [hunk 8]
```diff
@@ -1953,6 +1953,30 @@ Perl_rpp_obliterate_stack_to(pTHX_ I32 ix)
 
 }
 
+/*
+=for apidoc qerror
+
+Reports compilation errors, either by:
```
Comment (khwilliamson) [inline pp_ctl.c]: grammar: s/either/one of/

**Review by khwilliamson — COMMENTED** [review]
A bunch of nits, but otherwise lgtm

File: pod/perldelta.pod (hunk 3 above)
Comment (tonycoz) [reply pod/perldelta.pod]: yeah, "... functions no longer had visible...", fix on the way

File: embed.fnc (hunk 4 above)
Comment (tonycoz) [reply embed.fnc]: Removed both relevant FIXMEs

File: pp_ctl.c (hunk 8 above)
Comment (tonycoz) [reply pp_ctl.c]: Fixed that and expanded on it a bit.

**Comment by jkeenan** [comment]
Today I built a local branch starting from https://github.com/Perl/perl5/pull/24335, rebased on blead.  I conducted this work on a Linux server running Debian 13 (trixie), to which I had recently upgraded from Debin 12 (bookworm).  It should be noted that `gcc-14` is now the default C-compiler for this machine.  It should also be noted that my previous reports *on Linux* in https://github.com/Perl/perl5/issues/23676 were run on Ubuntu rather than Debian.
```
$ cat /etc/debian_version 
13.4
$ uname -mrs
Linux 6.12.74+deb13+1-amd64 x86_64

$ export GCC_14_ARGS="-des -Dusedevel -Dcc=gcc-14" && \
   install_custom_branch_for_testing \
   gh-24335-tonycoz-23676-op-parser-20260415 \
   "$GCC_14_ARGS" \
   gcc-14
```
Then, in two separate batches, I tested the CPAN distributions which have been reported broken in GH #23676.
```
$ ./bin/cpan CPAN::DistnameInfo \
IO::ExplicitHandle \
Devel::CallParser \
Devel::GoFaster \
Sub::StrictDecl

$ ./bin/perl -Ilib \
-MIO::ExplicitHandle \
-MDevel::CallParser \
-MDevel::GoFaster \
-MSub::StrictDecl \
-E 'say STDOUT q{hello world};'
hello world

$ ./bin/cpan Data::Alias

$ ./bin/perl -Ilib -MData::Alias -E 'say q{hello world};'
hello world
```
**clang-19 compilation**

On this machine the most recent version of `clang` available is `clang-19`.  I built a separate `perl` with that s the C-compiler, then re-tested the CPAN distros.
```
$ export CLANG_19_ARGS="-des -Dusedevel -Dcc=clang-19" && \
   install_custom_branch_for_testing \
   gh-24335-tonycoz-23676-op-parser-20260415 \
   "$CLANG_19_ARGS" \
   clang-19
```
Then, in two separate batches, I tested the CPAN distributions which have been reported broken in GH #23676.
```
$ ./bin/cpan CPAN::DistnameInfo \
IO::ExplicitHandle \
Devel::CallParser \
Devel::GoFaster \
Sub::StrictDecl

$ ./bin/perl -Ilib \
-MIO::ExplicitHandle \
-MDevel::CallParser \
-MDevel::GoFaster \
-MSub::StrictDecl \
-E 'say STDOUT q{hello world};'

$ ./bin/cpan Data::Alias
hello world

$ ./bin/perl -Ilib -MData::Alias -E 'say q{hello world};'
hello world
```
I got similar results using `clang19` to compile a threaded build on FreeBSD-14.

**Review by khwilliamson — APPROVED** [review]
still approved
