### PR TITLE
Prevent empty cop_file shared string as a byproduct of @INC hook/source filter issues

### LINKED ISSUE #20535: BBC: Blead breaks NHORNE/Devel-FIXME-0.02.tar.gz on threaded+debugging perls
**Description**

Starting with 5.37.4-247-g6760f691a9 tests started to fail for NHORNE/Devel-FIXME-0.02.tar.gz on perls that have been built with both -Duseithreads and -DEBUGGING=both. So far only verified on linux.

Sample fail report: http://www.cpantesters.org/cpan/report/420dad10-6a12-11ed-9e87-7ee24d77e83b

Failure diagnostics:

perl: op.c:15318: Perl_rcpv_free: Assertion `rcpv->len' failed.

Bisect leads me to:
``` text
6760f691a95ab3a37fd59212795de2b1a7cf7888 is the first bad commit
commit 6760f691a95ab3a37fd59212795de2b1a7cf7888
Author: Yves Orton <demerphq@gmail.com>
Date:   Fri Oct 28 21:14:23 2022 +0200

    cop.h - add support for refcounted filenames in cops under threads
```

**Steps to Reproduce**

cpan -i NHORNE/Devel-FIXME-0.02.tar.gz

**Expected behavior**

Should build, test and install the pkg

**Perl configuration**

```
# perl -V output goes here
Summary of my perl5 (revision 5 version 37 subversion 6) configuration:
  Commit id: d569e7cc1171d70b4ea183bc7c257dcf50f0ab12
  Platform:
    osname=linux
    osvers=5.4.0-132-generic
    archname=x86_64-linux-thread-multi-ld
    uname='linux k93focal 5.4.0-132-generic #148-ubuntu smp mon oct 17 16:02:06 utc 2022 x86_64 x86_64 x86_64 gnulinux '
    config_args='-Dprefix=/home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.37.6/e463 -Dmyhostname=k93focal -Dinstallusrbinperl=n -Uversiononly -Dusedevel -des -Ui_db -Dlibswanted=cl pthread socket inet nsl gdbm dbm malloc dl ld sun m crypt sec util c cposix posix ucb BSD gdbm_compat -Duseithreads -Duselongdouble -DEBUGGING=both'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=define
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2 -g'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='9.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='long double'
    nvsize=16
    Off_t='off_t'
    lseeksize=8
    alignbytes=16
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.31.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.31'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    DEBUGGING
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_TRACK_MEMPOOL
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_LONG_DOUBLE
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Nov 20 2022 15:54:39
  %ENV:
    PERL="/tmp/basesmoker-reloperl-h690/bin/perl"
    PERL5LIB="/tmp/loop_over_bdir-3557066-bc6Ier/Dpkg-1.21.9-0/blib/arch:/tmp/loop_over_bdir-3557066-bc6Ier/Dpkg-1.21.9-0/blib/lib:/tmp/loop_over_bdir-3557066-bc6Ier/dta-tokwrap-0.98-0/blib/arch:/tmp/loop_over_bdir-3557066-bc6Ier/dta-tokwrap-0.98-0/blib/lib"
    PERL5OPT=""
    PERL5_CPANPLUS_IS_RUNNING="3557074"
    PERL5_CPAN_IS_RUNNING="3557074"
    PERL_CANARY_STABILITY_NOPROMPT="1"
    PERL_MM_USE_DEFAULT="1"
    PERL_USE_UNSAFE_INC="1"
  @INC:
    /tmp/loop_over_bdir-3557066-bc6Ier/Dpkg-1.21.9-0/blib/arch
    /tmp/loop_over_bdir-3557066-bc6Ier/Dpkg-1.21.9-0/blib/lib
    /tmp/loop_over_bdir-3557066-bc6Ier/dta-tokwrap-0.98-0/blib/arch
    /tmp/loop_over_bdir-3557066-bc6Ier/dta-tokwrap-0.98-0/blib/lib
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.37.6/e463/lib/site_perl/5.37.6/x86_64-linux-thread-multi-ld
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.37.6/e463/lib/site_perl/5.37.6
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.37.6/e463/lib/5.37.6/x86_64-linux-thread-multi-ld
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.37.6/e463/lib/5.37.6
    .


```

### PR DESCRIPTION
**Pull request by demerphq**
In short the following code should produce the following: 

```
perl -It/lib -le'BEGIN{ unshift @INC, sub { if ($_[1] eq "CannotParse.pm" and !$seen++) { eval q(require $_[1]); warn $@;  my $code= qq[die qq(error)]; open my $fh,"<", \$code; return $fh } } } require CannotParse;'
```

Should output the following:
```
syntax error at t/lib/CannotParse.pm line 2, at EOF
Compilation failed in require at (eval 1) line 1.
error at /loader/0x564c1906a850/CannotParse.pm line 1.
Compilation failed in require at -e line 1.
```

Before this PR it output the following:
```
syntax error at t/lib/CannotParse.pm line 2, at EOF
Compilation failed in require at (eval 1) line 1.
error at  line 1.
Compilation failed in require at -e line 1.
```

Note the missing content in the line starting with "error".

This is because the underlying code was using the value in %INC, which was undef due to the innermost require failing.

This was revealed by an assert fail in the rcpv logic. This PR includes some changes to that logic so that it will more reasonably accommodate length 0 strings, and so we can use the length to validate that the structure is sane. It also improves the documentation. 

Note the reason this PR contains both was that at first this looked like a bug in the rcpv logic, but the more i dug into it the more convinced I because that we still should not support empty strings for the /existing/ uses of rcpv. However if someone were to use the infra for a new task it would be reasonable they have a way to support empty strings. Given the way these issues are a bit entangled I think its reasonable to include changes regarding both in this PR. (No need for PR churn.)

This fixes https://github.com/Perl/perl5/issues/20535

### CODE REVIEW

File: op.c [hunk 1]
```diff
@@ -15268,23 +15284,34 @@ Perl_rcpv_new(pTHX_ const char *pv, STRLEN len, U32 flags) {
...
     if (!pv && (flags & RCPVf_NO_COPY) == 0)
         return NULL;
 
     if (flags & RCPVf_USE_STRLEN)
         len = strlen(pv);
 
-    rcpv = (RCPV *)PerlMemShared_malloc(sizeof(struct rcpv) + len + 1);
+#if DEBUGGING
+    assert(len || (flags & RCPVf_ALLOW_EMPTY));
+#endif
```
Comment (tonycoz) [inline op.c]: The assert() will only typically apply when DEBUGGING is defined, so the #ifdef is unnecessary.

**Review by tonycoz — CHANGES_REQUESTED** [review]
Consider it approved with the extraneous #ifdef cleaned up

File: op.c (hunk 1 above)
Comment (demerphq) [reply op.c]: Yeah, that was a stupid. Originally I had a warn in there, I just forgot to remove the #if when I changed it to an assert.

Fixed.
