### PR TITLE
S_invlist_trim - don't SvPV_renew if SvLEN(invlist) is < PTRSIZE larger

### LINKED ISSUE #23103: S_invlist_trim maybe doesn't need to SvPV_renew every time?
**Description**
`S_invlist_trim` does a surprising (to me) amount of`realloc()` calls during even
a `make perl`.

`S_invlist_trim` always calls `realloc()` via `SvPV_renew`, but looking at some of
the underlying values, many of these calls will not result in an actual reallocation
(because of malloc alignment requirements, or larger-than-asked-for allocations),
and the saving otherwise is arguably not worth it.

For example, printing out the relevant values on each call shows:
```
...
Going to resize from 0 to MAX(9, 1) - actual buffer size is 9
Going to resize from 168 to MAX(9, 169) - actual buffer size is 170
Going to resize from 0 to MAX(9, 1) - actual buffer size is 9
Going to resize from 168 to MAX(9, 169) - actual buffer size is 170
Going to resize from 0 to MAX(9, 1) - actual buffer size is 9
Going to resize from 168 to MAX(9, 169) - actual buffer size is 170
Going to resize from 40 to MAX(9, 41) - actual buffer size is 186
Going to resize from 136 to MAX(9, 137) - actual buffer size is 210
Going to resize from 40 to MAX(9, 41) - actual buffer size is 178
Going to resize from 168 to MAX(9, 169) - actual buffer size is 170
Going to resize from 0 to MAX(9, 1) - actual buffer size is 154
Going to resize from 168 to MAX(9, 169) - actual buffer size is 170
Going to resize from 0 to MAX(9, 1) - actual buffer size is 9
Going to resize from 168 to MAX(9, 169) - actual buffer size is 170
Going to resize from 0 to MAX(9, 1) - actual buffer size is 9
Going to resize from 168 to MAX(9, 169) - actual buffer size is 170
Going to resize from 0 to MAX(9, 1) - actual buffer size is 9
Going to resize from 168 to MAX(9, 169) - actual buffer size is 170
...
```

Should `S_invlist_trim` just return without doing the `SvPV_renew` if:
* `MAX(min_size, SvCUR(invlist) + 1) == SvLEN(invlist)`
* The difference between the two values is minimal (maybe less than a pointer's worth in it?)

**Steps to Reproduce**
Apply this quick 'n' dirty patch and run `make perl`:
```
diff --git a/regcomp_invlist.c b/regcomp_invlist.c
index 5289d5a5d5..45e53363a9 100644
--- a/regcomp_invlist.c
+++ b/regcomp_invlist.c
@@ -252,7 +252,7 @@ S_invlist_trim(SV* invlist)
     PERL_ARGS_ASSERT_INVLIST_TRIM;
 
     assert(is_invlist(invlist));
-
+PerlIO_stdoutf("Going to resize from %li to MAX(%li, %li) - actual buffer size is %li\n", SvCUR(invlist), min_size, SvCUR(invlist)+1, SvLEN(invlist));
     SvPV_renew(invlist, MAX(min_size, SvCUR(invlist) + 1));
 }
 
```

**Expected behavior**
`S_invlist_trim` returns without reallocating if the size difference is zero or minimal.

**Perl configuration**
_blead_

### PR DESCRIPTION
**Pull request by richardleach**
Currently, `S_invlist_trim` always calls `SvPV_renew(invlist, <size>)`,
 which is a macro wrapping a call to `safesysrealloc()`.

However, `SvLEN(invlist)` is often already exactly the desired size, 
or it is larger by less than the size of a pointer. With this commit, 
such cases just return without calling `SvPV_renew()`.

---------------------------------------------------------------------------------
* This set of changes does not require a perldelta entry.

### CODE REVIEW

**Comment by richardleach** [comment]
Tow comments:
* It will still be common to try to resize SvLEN == 34 down to 25 bytes. Given that it's common for malloc implementations to increase chunk sizes by 2 x PTRLEN, should that be the check here too?
* Allocated chunks will be pointer-aligned. 34 is not a multiple of 8! Maybe we should round up allocation sizes to a multiple of the pointer size generally?

**Comment by bulk88** [comment]
[S_invlist_trim_pv_shrink_evt_trace.txt](https://github.com/user-attachments/files/19775753/S_invlist_trim_pv_shrink_evt_trace.txt)
 made a log, "if( new == old ) goto skip;" isn't captured in the log. I already removed that permutation in the test build. byte counts are in hex/base16 on Win64 Perl, and the byte counts are whatever is in `SvLEN` field before and after.

There are so many problems with this API, IDK where to start. For example, the same `SV*` head is repeatedly getting shrunk. So why isn't perl core keeping it at the max/peak length? That means a single INVLIST GC pass at the "end" (IDK where "end" is), triggered from C stack C fn scope, or triggered by a save stack entry (runloop).

Also "new 0x9" which is `(UV)0`+`'\0'` probably shouldn't even exist in the SVt_INVLIST API on a C level, since that means "empty" or "0 entries", since the first `sizeof(UV)` bytes, at the start of the `SvPVX` in a `SVt_INVLIST`  is always a items counter.

Suggestion, why not just turn off `SvPOK` or its analog, `Safefree()` the `SvPVX` buffer, and set `SvLEN` to 0 inside a `SVt_INVLIST` `SV*` obj instead of keep a `Newx` that just means undef or zero on a high[-er] [API] level anyway?

ln 50 `	$args{strip_suffix} = $OPT{'s'} =~ m#^/([^/]*[^/\$]|)\$?/?$# ? qr/$1/ : qr/\Q$OPT{'s'}\E/;`
```
S_invlist_trim old 42 new 19 at 1d7ec10 at C:\sources\perl5\win32\bin\pl2bat.pl line 50.
S_invlist_trim old 42 new 19 at 1d7ec10 at C:\sources\perl5\win32\bin\pl2bat.pl line 50.
S_invlist_trim old 42 new 19 at 1d7ec10 at C:\sources\perl5\win32\bin\pl2bat.pl line 50.
S_invlist_trim old 42 new 19 at 1d7ec10 at C:\sources\perl5\win32\bin\pl2bat.pl line 50.
S_invlist_trim old 42 new 19 at 1d7ec10 at C:\sources\perl5\win32\bin\pl2bat.pl line 50.
S_invlist_trim old 42 new 19 at 1d7ec10 at C:\sources\perl5\win32\bin\pl2bat.pl line 50.
S_invlist_trim old 42 new 19 at 1d7ec10 at C:\sources\perl5\win32\bin\pl2bat.pl line 50.
```
ln 195 `	my (@rest) = ($args =~ /([^\s:])(?!\s*:)/g);`
```
S_invlist_trim old ba new b9 at 1d7ee20 at C:\sources\perl5\lib/Getopt/Std.pm line 195.
S_invlist_trim old aa new 9 at 1d7ed78 at C:\sources\perl5\lib/Getopt/Std.pm line 195.
S_invlist_trim old ba new b9 at 1d7ee20 at C:\sources\perl5\lib/Getopt/Std.pm line 195.
S_invlist_trim old ba new b9 at 1d7ee20 at C:\sources\perl5\lib/Getopt/Std.pm line 195.
S_invlist_trim old ba new b9 at 1d7ee20 at C:\sources\perl5\lib/Getopt/Std.pm line 195.
S_invlist_trim old ba new b9 at 1d7ee20 at C:\sources\perl5\lib/Getopt/Std.pm line 195.
S_invlist_trim old ba new b9 at 1d7ee20 at C:\sources\perl5\lib/Getopt/Std.pm line 195.
S_invlist_trim old ba new b9 at 1d7ee20 at C:\sources\perl5\lib/Getopt/Std.pm line 195.
S_invlist_trim old ba new b9 at 1d7ee20 at C:\sources\perl5\lib/Getopt/Std.pm line 195.
S_invlist_trim old ba new b9 at 1d7ee20 at C:\sources\perl5\lib/Getopt/Std.pm line 195.
S_invlist_trim old ba new b9 at 1d7ee20 at C:\sources\perl5\lib/Getopt/Std.pm line 195.
S_invlist_trim old ba new b9 at 1d7ee20 at C:\sources\perl5\lib/Getopt/Std.pm line 195.
S_invlist_trim old ba new b9 at 1d7ee20 at C:\sources\perl5\lib/Getopt/Std.pm line 195.
S_invlist_trim old ba new b9 at 1d7ee20 at C:\sources\perl5\lib/Getopt/Std.pm line 195.
```
ln 51 `			@e = split(/((?:\PM\pM*|^\pM+){$tabstop})/,$line,-1);`
$tabstop is a spiritual const at runtime, set 1x per proc as `our $tabstop = 8;`.
```
S_invlist_trim old 1382 new 19 at 2551f60 at C:\sources\perl5\cpan\Text-Tabs\lib/Text/Tabs.pm line 51, <$fh> line 668.
S_invlist_trim old 1382 new 19 at 2551fa8 at C:\sources\perl5\cpan\Text-Tabs\lib/Text/Tabs.pm line 51, <$fh> line 668.
S_invlist_trim old 1382 new 19 at 2551fa8 at C:\sources\perl5\cpan\Text-Tabs\lib/Text/Tabs.pm line 51, <$fh> line 668.
S_invlist_trim old 1382 new 19 at 2551fa8 at C:\sources\perl5\cpan\Text-Tabs\lib/Text/Tabs.pm line 51, <$fh> line 668.
S_invlist_trim old 1382 new 19 at 2551fa8 at C:\sources\perl5\cpan\Text-Tabs\lib/Text/Tabs.pm line 51, <$fh> line 668.
S_invlist_trim old 1382 new 19 at 2551fa8 at C:\sources\perl5\cpan\Text-Tabs\lib/Text/Tabs.pm line 51, <$fh> line 668.
S_invlist_trim old 1382 new 19 at 2551fa8 at C:\sources\perl5\cpan\Text-Tabs\lib/Text/Tabs.pm line 51, <$fh> line 668.
S_invlist_trim old 1382 new 19 at 2551fa8 at C:\sources\perl5\cpan\Text-Tabs\lib/Text/Tabs.pm line 51, <$fh> line 668.
S_invlist_trim old 1382 new 19 at 2551fa8 at C:\sources\perl5\cpan\Text-Tabs\lib/Text/Tabs.pm line 51, <$fh> line 668.
S_invlist_trim old 1382 new 19 at 2551fa8 at C:\sources\perl5\cpan\Text-Tabs\lib/Text/Tabs.pm line 51, <$fh> line 668.
```
ln 1425 `    return undef unless my ($quote_type, $value) = $Config_SH_expanded =~ /\n$key=(['"])(.*?)\1\n/s;`
This one looks like a total failure to precompute data at BEGIN phase/PP Compile time. SV* 0x22c90d0 and the others are repeating in a pattern.
```
S_invlist_trim old 3a new 9 at 22c90d0 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4259.
S_invlist_trim old 2a new 9 at 22c9130 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4259.
S_invlist_trim old 22 new 19 at 22ca658 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4259.
S_invlist_trim old 3a new 9 at 22c2fc8 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4260.
S_invlist_trim old 2a new 9 at 22c90e8 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4260.
S_invlist_trim old 22 new 19 at 22ca568 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4260.
S_invlist_trim old 3a new 9 at 22c0c48 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4261.
S_invlist_trim old 2a new 9 at 22c0cf0 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4261.
S_invlist_trim old 22 new 19 at 22ca598 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4261.
S_invlist_trim old 3a new 9 at 22ca628 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4262.
S_invlist_trim old 2a new 9 at 22ca658 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4262.
S_invlist_trim old 22 new 19 at 22c3010 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4262.
S_invlist_trim old 3a new 9 at 22c9130 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4263.
S_invlist_trim old 2a new 9 at 22ca568 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4263.
S_invlist_trim old 22 new 19 at 22c90d0 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4263.
S_invlist_trim old 3a new 9 at 22c90e8 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4272.
S_invlist_trim old 2a new 9 at 22ca598 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4272.
S_invlist_trim old 22 new 19 at 22c2fc8 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4272.
S_invlist_trim old 3a new 9 at 22c0cf0 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4281.
S_invlist_trim old 2a new 9 at 22c3010 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4281.
S_invlist_trim old 22 new 19 at 22c0c48 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4281.
S_invlist_trim old 3a new 9 at 22ca658 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4282.
S_invlist_trim old 2a new 9 at 22c90d0 at C:\sources\perl5\lib/Config_heavy.pl line 1425, <SH> line 4282.
```

Here is a sample of the different kinds of actual sizes/SvLEN values encountered by this API during a `gmake.exe all`.

```
S_invlist_trim old 304a new 69 at C:\sources\perl5\cpan\File-Path\lib/File/Path.pm line 183.
S_invlist_trim old 22 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 1399.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 87.
S_invlist_trim old 30a2 new 2fe9 at C:\sources\perl5\cpan\File-Path\lib/File/Path.pm line 183.
S_invlist_trim old 3a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1403.
S_invlist_trim old 3052 new 69 at C:\sources\perl5\cpan\File-Path\lib/File/Path.pm line 183.
S_invlist_trim old 2a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1403.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 87.
S_invlist_trim old 304a new 3039 at C:\sources\perl5\cpan\File-Path\lib/File/Path.pm line 183.
S_invlist_trim old 3a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1403.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 87.
S_invlist_trim old 2a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1403.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 87.
S_invlist_trim old ba new 29 at ../regen/HeaderParser.pm line 88.
S_invlist_trim old d2 new 89 at ../regen/HeaderParser.pm line 88.
S_invlist_trim old b2 new 29 at ../regen/HeaderParser.pm line 88.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 88.
S_invlist_trim old 9a new 9 at ../regen/HeaderParser.pm line 88.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 88.
S_invlist_trim old 22 new 19 at C:\sources\perl5\cpan\File-Path\lib/File/Path.pm line 349.
S_invlist_trim old 22 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 1403.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 88.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 88.
S_invlist_trim old 22 new 19 at C:\sources\perl5\cpan\File-Path\lib/File/Path.pm line 350.
S_invlist_trim old 22 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 1436.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 88.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 88.ources\perl5\lib\CORE\zaphod32_hash.h
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 88.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 88.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 88.
S_invlist_trim old 3a new 9 at C:\sources\perl5\cpan\File-Path\lib/File/Path.pmline 353.
S_invlist_trim old 22 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 1437.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 88.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 88.
S_invlist_trim old ba new 29 at ../regen/HeaderParser.pm line 98.
S_invlist_trim old 2a new 9 at C:\sources\perl5\cpan\File-Path\lib/File/Path.pmline 353.
S_invlist_trim old 22 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 1487.
S_invlist_trim old d2 new 89 at ../regen/HeaderParser.pm line 98.
S_invlist_trim old 22 new 19 at C:\sources\perl5\cpan\File-Path\lib/File/Path.pm line 356.
S_invlist_trim old 2a new 19 at C:\sources\perl5\lib/Config_heavy.pl line 1487.
S_invlist_trim old b2 new 29 at ../regen/HeaderParser.pm line 98.
S_invlist_trim old 32 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 1487.
S_invlist_trim old 3a new 9 at C:\sources\perl5\cpan\File-Path\lib/File/Path.pmline 572.
S_invlist_trim old 22 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 1487.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 98.
S_invlist_trim old 2a new 9 at C:\sources\perl5\cpan\File-Path\lib/File/Path.pmline 572.
S_invlist_trim old 32 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 1487.
S_invlist_trim old 9a new 9 at ../regen/HeaderParser.pm line 98.
S_invlist_trim old 2a new 9 at C:\sources\perl5\cpan\File-Path\lib/File/Path.pmline 572.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 98.
S_invlist_trim old 304a new 69 at C:\sources\perl5\lib/Config_heavy.pl line 1493.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 98.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 98.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 98.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 98.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 98.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 98.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 98.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 98.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 98.
S_invlist_trim old 42 new 19 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 42 new 19 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 42 new 19 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 42 new 19 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 42 new 19 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 42 new 19 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 42 new 19 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 42 new 19 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 42 new 19 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 42 new 19 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 42 new 19 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 42 new 19 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 42 new 19 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 42 new 19 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 42 new 19 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 42 new 19 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 3a new 11 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old ba new 9 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old aa new 9 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 3a new 29 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 3a new 9 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 115.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 3052 new 69 at C:\sources\perl5\lib/Config_heavy.pl line 1493.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 304a new 69 at C:\sources\perl5\lib/Config_heavy.pl line 1496.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 30a2 new 2fe9 at C:\sources\perl5\lib/Config_heavy.pl line 1496.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 3052 new 69 at C:\sources\perl5\lib/Config_heavy.pl line 1496.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 304a new 3039 at C:\sources\perl5\lib/Config_heavy.pl line 1496.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 10.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 14.
S_invlist_trim old 22 new 19 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old 22 new 9 at ../regen/HeaderParser.pm line 93.
S_invlist_trim old ba new 29 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 22 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 32.
S_invlist_trim old d2 new 89 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old b2 new 29 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 9a new 9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 22 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 49.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 304a new 69 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 30a2 new 2fe9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 3052 new 69 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 304a new 3039 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 304a new 69 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 30a2 new 2fe9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 3052 new 69 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 304a new 3039 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old ba new 29 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old d2 new 89 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old b2 new 29 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 9a new 9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old ba new 29 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old d2 new 89 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old b2 new 29 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 9a new 9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 304a new 69 at C:\sources\perl5\lib/Config_heavy.pl line 157.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 304a new 69 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 30a2 new 2fe9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 3052 new 69 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 3a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1425.
S_invlist_trim old 30a2 new 2fe9 at C:\sources\perl5\lib/Config_heavy.pl line 157.
S_invlist_trim old 304a new 3039 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 2a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1425.
S_invlist_trim old 3052 new 69 at C:\sources\perl5\lib/Config_heavy.pl line 157.
S_invlist_trim old 22 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 1425.
S_invlist_trim old 304a new 3039 at C:\sources\perl5\lib/Config_heavy.pl line 157.
S_invlist_trim old ba new 29 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 3a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1425.
S_invlist_trim old 22 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 157.
S_invlist_trim old d2 new 89 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 2a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1425.
S_invlist_trim old b2 new 29 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 22 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 1425.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 3a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1425.
S_invlist_trim old 9a new 9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 2a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1425.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 22 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 1425.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 3a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1386.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 3a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1425.
S_invlist_trim old 2a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1386.
S_invlist_trim old 2a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1425.
S_invlist_trim old 22 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 1386.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 22 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 1425.
S_invlist_trim old 3a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1399.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 3a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1425.
S_invlist_trim old 2a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1399.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 2a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1425.
S_invlist_trim old 3a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1399.
S_invlist_trim old 22 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 1425.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 2a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1399.
S_invlist_trim old 3a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1425.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 22 new 19 at C:\sources\perl5\lib/Config_heavy.pl line 1399.
S_invlist_trim old 2a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1425.
S_invlist_trim old aa new a9 at ../regen/HeaderParser.pm line 116.
S_invlist_trim old 3a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1403.
S_invlist_trim old 2a new 9 at C:\sources\perl5\lib/Config_heavy.pl line 1425.
```

**Comment by bulk88** [comment]
I'm just gonna drop a link here in this randomly picked ticket https://github.com/Perl/perl5/issues/23359

There are around 6 - 10 stalled PRs open related to the regexp engine's abuse of RenewTrim() and `SvPV_shrink_to_cur(sv)`.

And another about 8-12 bug reports without code/patches/fixes open right now related to the regexp engine's abuse of RenewTrim() and `SvPV_shrink_to_cur(sv)`.

And 2-6 bug reports without code/patches/fixes open right now related to the `<>`/`Perl_sv_gets()`;s abuse of RenewTrim() and `SvPV_shrink_to_cur(sv)`.

**Comment by richardleach** [comment]
I've modified this PR to make use of the recently introduced `Perl_expected_size` macro.

The current code does still see `SvPV_renew` called needlessly - for example when `SvLEN` ==40, the desired size is 32, but the valid allocation sizes are 24 bytes and 40 bytes. Improvements to come to `Perl_expected_size` seem the better solution to  that sort of case rather than applying fudge factors inside `S_invlist_trim`.

Ready for review.

**Comment by richardleach** [comment]
Though if there's consensus that the remaining amount of reallocation for small gain is undesirable, I'm not opposed to re-tweaking the condition from:
````
    if ( SvLEN(invlist) > realistic_size ) {
````
to something like:
````
    if ( SvLEN(invlist) > realistic_size + PTRSIZE) {
````

File: regcomp_invlist.c [hunk 1]
```diff
@@ -246,14 +246,33 @@ S_invlist_trim(SV* invlist)
...
 
     /* But don't free up the space needed for the 0 UV that is always at the
-     * beginning of the list, nor the trailing NUL */
-    const UV min_size = TO_INTERNAL_SIZE(1) + 1;
+     * beginning of the list, nor the trailing NUL. The smallest possible
+     * allocation size may or may not be larger than this, depending upon
+     * the malloc implementation in use. */
+
+    const STRLEN min_size = (PERL_STRLEN_NEW_MIN > TO_INTERNAL_SIZE(1) + 1)
+                            ? PERL_STRLEN_NEW_MIN : TO_INTERNAL_SIZE(1) + 1;
```
Comment (khwilliamson) [inline regcomp_invlist.c]: Why not use MAX() here?

**Review by khwilliamson — DISMISSED** [review]

**Comment by khwilliamson** [comment]
How many bytes do we consider too little to bother with trimming?  I don't know.  But I'd like to see some ideas.  I'd be fine if others are willing to tolerate some excess that doesn't get trimmed in the service of fewer malloc calls

File: regcomp_invlist.c (hunk 1 above)
Comment (richardleach) [reply regcomp_invlist.c]: Good suggestion, thanks. I'll do that.

**Comment by richardleach** [comment]
> How many bytes do we consider too little to bother with trimming? I don't know. But I'd like to see some ideas. I'd be fine if others are willing to tolerate some excess that doesn't get trimmed in the service of fewer malloc calls

I don't have a good understanding of the lifetime of invlists. Do some hang around under interpreter destruction but others might be short lived? (Less shrinkage seems like a reasonable trade off for the latter, but less so for the former.)

**Comment by khwilliamson** [comment]
Some are immortal; some come and go.   I instrumented invlist_trim to write out how many bytes it is calling.  The attached is the result.  The first column is how many times during the execution of the suite did the second column's byte count get freed.
[attached.txt](https://github.com/user-attachments/files/21950843/attached.txt)

**Comment by khwilliamson** [comment]
And, here is that file sorted by how common each request is
[sorted.txt](https://github.com/user-attachments/files/21956525/sorted.txt)

**Comment by richardleach** [comment]
I'm thinking maybe something in the ballpark of:
```
if ( SvLEN(invlist) > realistic_size + 6*PTRSIZE) {
```
The thinking being that will typically keep any wastage within a single cache line and itsn't completely atrocious, whilst still saving a lot of reallocs.

**Comment by richardleach** [comment]
I don't know what the correct balance looks like, so have updated with this fudge factor:
`if ( SvLEN(invlist) > realistic_size + 4*PTRSIZE )`

Unless there are any objections, I'll merge in a week or so.
