### PR TITLE
regcomp.c: validate \g{...} contents past first number

### LINKED ISSUE #23050: regex \g{...} syntax is missing error checks
**Description**

In a regex with an explicit backreference  like `/\g{...}/`, the `...` part is supposed to be either the name or the number of a capturing group (the latter can be negative for relative references). However, if the `...` sequence starts with a number, the rest of it is not syntax-checked.

**Steps to Reproduce**

```
$ perl -e '"" =~ /(.)\g{-1mtfnpy! &%{{{}/'
$ 
```

**Expected behavior**

A syntax error, possibly along the lines of `Sequence \g{... not terminated in regex; marked by <-- HERE in m/(.)\g{-1 <-- HERE mtfnpy! &%{{{}/ at -e line 1.`.

**Perl configuration**

```
Summary of my perl5 (revision 5 version 40 subversion 1) configuration:
   
  Platform:
    osname=linux
    osvers=6.8.0-110051-tuxedo
    archname=x86_64-linux-thread-multi-ld
    uname='linux luum 6.8.0-110051-tuxedo #52tux1 smp preempt_dynamic wed dec 18 12:34:04 utc 2024 x86_64 x86_64 x86_64 gnulinux '
    config_args='-de -Dprefix=/home/mauke/perl5/perlbrew/perls/perl-5.40.1 -Dcc=c-gcc -Doptimize=-O2 -march=native -flto=auto -Dman1dir=none -Dman3dir=none -Dusethreads -Duselongdouble -Aeval:scriptdir=/home/mauke/perl5/perlbrew/perls/perl-5.40.1/bin'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=define
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='c-gcc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2 -march=native -flto=auto'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='13.3.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='long double'
    nvsize=16
    Off_t='off_t'
    lseeksize=8
    alignbytes=16
    prototype=define
  Linker and Libraries:
    ld='c-gcc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/x86_64-linux-gnu/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.39'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -march=native -flto=auto -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_LONG_DOUBLE
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Jan 20 2025 18:07:12
  %ENV:
    PERLBREW_BASHRC_VERSION="0.74"
    PERLBREW_HOME="/home/mauke/.perlbrew"
    PERLBREW_MANPATH="/home/mauke/perl5/perlbrew/perls/perl-5.40.1/man"
    PERLBREW_PATH="/home/mauke/perl5/perlbrew/bin:/home/mauke/perl5/perlbrew/perls/perl-5.40.1/bin"
    PERLBREW_PERL="perl-5.40.1"
    PERLBREW_ROOT="/home/mauke/perl5/perlbrew"
    PERLBREW_VERSION="0.98"
    PERLDOC="-oman"
    PERL_UNICODE="SAL"
  @INC:
    /home/mauke/perl5/perlbrew/perls/perl-5.40.1/lib/site_perl/5.40.1/x86_64-linux-thread-multi-ld
    /home/mauke/perl5/perlbrew/perls/perl-5.40.1/lib/site_perl/5.40.1
    /home/mauke/perl5/perlbrew/perls/perl-5.40.1/lib/5.40.1/x86_64-linux-thread-multi-ld
    /home/mauke/perl5/perlbrew/perls/perl-5.40.1/lib/5.40.1
```

### PR DESCRIPTION
**Pull request by mauke**
This code used to silently accept `\g{123trailing garbage}` as long as it started with a valid number.

Fixes #23050.

---------------------------------------------------------------------------------
* This set of changes requires a perldelta entry, and it is included.

### CODE REVIEW

File: regcomp.c [hunk 1]
```diff
@@ -6021,7 +6028,7 @@ S_regatom(pTHX_ RExC_state_t *pRExC_state, I32 *flagp, U32 depth)
                 char * e = RExC_end;
 
                 if (*s == 'g') {
-                    bool isrel = 0;
+                    bool isrel = FALSE;
```
Comment (khwilliamson) [inline regcomp.c:6031]: Why not use C99 'false' here and similarly below?  We already have instances of the newer in core; I see no need to be consistent; I think new stuff should be using the C names, just like we should be using `ptr_diff_t` instead of our macro that was just removed

File: t/re/reg_mesg.t [hunk 2]
```diff
@@ -220,6 +220,8 @@ my @death =
  '/\g/' => 'Unterminated \g... pattern {#} m/\g{#}/',
  '/\g{1/' => 'Unterminated \g{...} pattern {#} m/\g{1{#}/',
  '/\g{-abc}/' => 'Group name must start with a non-digit word character {#} m/\g{-{#}abc}/',
+ '/\g{1-1}/'  => 'Sequence \g{... not terminated {#} m/\g{1{#}-1}/',
```
Comment (khwilliamson) [inline t/re/reg_mesg.t:223]: To a human, it is obvious that this is terminated; just syntactically invalid.  The parser can be forgiven for not being able to detect that.  But it is unfortunate that the existing diagnostic doesn't give that as a possibility.  You have to go to perldiag to find that a syntax error is a possibility,  We likely can't change existing diagnostics, but this is a new error, and so a clearer error message could be devised.

**Review by khwilliamson — APPROVED** [review]

File: regcomp.c (hunk 1 above)
Comment (mauke) [reply regcomp.c:6031]: Because I didn't see `bool`/`true`/`false` on the list of approved C99 features in perlhacktips. On closer examination there is a "When is a bool not a bool?" section near the bottom, but technically it doesn't say we can rely on `true`/`false` being present.

More to the point, there are already about 240 instances of `TRUE`/`FALSE` in regcomp.c. I'd rather keep things locally consistent; a later patch can then lowercase all the boolean constants in the file in one go.

File: t/re/reg_mesg.t (hunk 2 above)
Comment (mauke) [reply t/re/reg_mesg.t:223]: I was following the example of named backreferences:
```
$ perl -e '/\g{foo-bar}/'
Sequence \g{... not terminated in regex; marked by <-- HERE in m/\g{foo <-- HERE -bar}/ at -e line 1.
```

File: regcomp.c (hunk 1 above)
Comment (khwilliamson) [reply regcomp.c:6031]: fair enough

File: t/re/reg_mesg.t (hunk 2 above)
Comment (khwilliamson) [reply t/re/reg_mesg.t:223]: That's understandable, and maybe it isn't for this PR, but I believe new warning instances shouldn't be bound by inadequacies in previous instances.
