### PR TITLE
Fix targ handling for some builtin:: XS functions

### LINKED ISSUE #22542: goto &SUB segfaults with builtin::refaddr, reftype, stringify, etc
**Description**
Some of the built-in functions in `builtin::` crash when called via `goto &builtin::X`.

This is (one of) the underlying issue(s) from #22528. I'm reporting it separately so it doesn't get lost even if Tie::RefHash::Weak gets fixed (or rather, a workaround is deployed in Tie::RefHash). As noted in https://github.com/Perl/perl5/issues/22528#issuecomment-2302576538 by @leonerd:

> Huh. Exciting times:
> ```
> $ bleadperl -E 'sub { goto &builtin::refaddr }->(0)'
> panic: pad_sv po at -e line 1.
> ```

**Steps to Reproduce**
```
$ ./perl -e 'sub { goto &builtin::refaddr }->([])'
Segmentation fault
$ ./perl -e 'sub { goto &builtin::reftype }->([])'
Segmentation fault
$ ./perl -e 'sub { goto &builtin::stringify }->([])'
Segmentation fault
$ ./perl -e 'sub { goto &builtin::trim }->([])'
Segmentation fault
```

**Expected behavior**
No crash.

**Perl configuration**
```
Summary of my perl5 (revision 5 version 41 subversion 3) configuration:
  Derived from: 34d9693e57b11b0ee7c74c4981facac0091db166
  Platform:
    osname=linux
    osvers=6.5.0-10043-tuxedo
    archname=x86_64-linux
    uname='linux luum 6.5.0-10043-tuxedo #47 smp preempt_dynamic tue jun 4 14:29:55 utc 2024 x86_64 x86_64 x86_64 gnulinux '
    config_args='-Dcc=c-gcc -Dusedevel -des'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='c-gcc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='11.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='c-gcc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/x86_64-linux-gnu/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.35'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Locally applied patches:
    uncommitted-changes
  Built under linux
  Compiled at Aug 26 2024 04:28:06
  %ENV:
    PERLBREW_BASHRC_VERSION="0.74"
    PERLBREW_HOME="/home/mauke/.perlbrew"
    PERLBREW_MANPATH="/home/mauke/perl5/perlbrew/perls/perl-5.40.0/man"
    PERLBREW_PATH="/home/mauke/perl5/perlbrew/bin:/home/mauke/perl5/perlbrew/perls/perl-5.40.0/bin"
    PERLBREW_PERL="perl-5.40.0"
    PERLBREW_ROOT="/home/mauke/perl5/perlbrew"
    PERLBREW_VERSION="0.94"
    PERLDOC="-oman"
    PERL_UNICODE="SAL"
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.41.3/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.41.3
    /usr/local/lib/perl5/5.41.3/x86_64-linux
    /usr/local/lib/perl5/5.41.3
```

### PR DESCRIPTION
**Pull request by tonycoz**
Tests and fixes #22542

### CODE REVIEW

File: builtin.c [hunk 1]
```diff
@@ -740,6 +759,56 @@ Perl_boot_core_builtin(pTHX)
     newXS_flags("builtin::import", &XS_builtin_import, __FILE__, NULL, 0);
 }
 
+/* These pp_ funcs all need to use dXSTARG */
+
+PP(pp_refaddr)
```
Comment (leonerd) [inline builtin.c]: I feel that, since we have various XSUBs in this file already, the related PP funcs should probably live in the same area, nearer the top, with the wrapping machinary for import/etc at the bottom.

File: regen/op_private [hunk 2]
```diff
@@ -606,6 +606,12 @@ addbits('entersub',
     # 7    => OPpLVAL_INTRO, already defined above
 );
 
+# these builtin:: implementing OPs also use dXSTARG and expect HASTARG to be
+# set if a targ is available
+addbits($_,
+        2      => qw(OPpENTERSUB_HASTARG  TARG  ),
+) for qw(refaddr reftype ceil floor goto);
```
Comment (leonerd) [inline regen/op_private:630]: Did you mean to include `goto` in here as well? I don't see any other changes elsewhere that would include it.

Comment (tonycoz) [reply regen/op_private:630]: We check for the flag when the XSUB is called from goto, so while we never set the flag it is reserved.

Comment (leonerd) [reply regen/op_private:630]: Ahyes, makes sense. Might be worth adding a comment to that effect then.

Comment (tonycoz) [reply regen/op_private:630]: I thought of renaming `OPpENTERSUB_HASTARG` to `OPpXSUB_HASTARG` to make things a bit clearer but it is used in code generated by EU::PXS and by code in PathTools, so I suspect the rename would be more confusing than helpful.

File: builtin.c (hunk 1 above)
Comment (tonycoz) [reply builtin.c]: moved up

File: regen/op_private (hunk 2 above)
Comment (tonycoz) [reply regen/op_private:630]: added a more detailed comment

**Review by leonerd — APPROVED** [review]
LGTM
