### PR TITLE
Fixes to bytes_to_utf8-type functions

### LINKED ISSUE #22902: BBC: Blead Breaks Sereal::Encoder
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.43 running under perl 5.41.8.

-----------------------------------------------------------------

BBC: Blead Breaks Sereal::Encoder

Please see http://fast-matrix.cpantesters.org/?dist=Sereal::Encoder

---
**Flags**
- category=core
- severity=low
---
**Perl configuration**
```
Site configuration information for perl 5.41.8:

Configured by cpan at Sat Jan 11 02:10:58 EST 2025.

Summary of my perl5 (revision 5 version 41 subversion 8) configuration:
  Commit id: 3a16cb5fb8114b7773a9c488c78684bffd787b62
  Platform:
    osname=linux
    osvers=5.14.0-503.21.1.el9_5.x86_64
    archname=x86_64-linux
    uname='linux cjg-rhel9 5.14.0-503.21.1.el9_5.x86_64 #1 smp preempt_dynamic thu dec 19 09:37:00 est 2024 x86_64 x86_64 x86_64 gnulinux '
    config_args='-des -Dprefix=/home/cpan/bin/perl -Dscriptdir=/home/cpan/bin/perl/bin -Dusedevel -Duse64bitall'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='11.5.0 20240719 (Red Hat 11.5.0-2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib /usr/lib64 /usr/local/lib64
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/../lib64/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.34'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


---
@INC for perl 5.41.8:
    /home/cpan/bin/perl/lib/site_perl/5.41.8/x86_64-linux
    /home/cpan/bin/perl/lib/site_perl/5.41.8
    /home/cpan/bin/perl/lib/5.41.8/x86_64-linux
    /home/cpan/bin/perl/lib/5.41.8

---
Environment for perl 5.41.8:
    HOME=/home/cpan
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_ALL=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl/bin:/home/cpan/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
    PERL_BADLANG (unset)
    SHELL=/bin/bash
```

### PR DESCRIPTION
**Pull request by khwilliamson**
This commit turns bytes_to_utf8() back into an (inline) function, and changes the type of a parameter in bytes_to_utf8_freeme() to void*, which is a more accurate type for it.

Fixes #22902

* This set of changes does not require a perldelta entry.

### CODE REVIEW

File: inline.h [hunk 1]
```diff
@@ -1133,6 +1133,12 @@ in lvalue context.
 */
 
 
+PERL_STATIC_INLINE U8 *
+Perl_bytes_to_utf8(pTHX_ const U8 *s, STRLEN *lenp)
+{
+    return bytes_to_utf8_free_me(s, lenp, NULL);
+}
+
```
Comment (tonycoz) [inline inline.h]: This should be above the doc comment (which is for the code following), and probably with other utf8 related functions.

File: utf8.c [hunk 2]
```diff
@@ -3292,7 +3292,7 @@ EBCDIC), see L</sv_recode_to_utf8>().
 
 U8*
 Perl_bytes_to_utf8_free_me(pTHX_ const U8 *s, Size_t *lenp,
-                                 const U8 ** free_me_ptr)
+                                 const void ** free_me_ptr)
```
Comment (tonycoz) [inline utf8.c]: `free_me_ptr` shouldn't be const.

Comment (khwilliamson) [reply utf8.c]: Thanks

File: inline.h (hunk 1 above)
Comment (khwilliamson) [reply inline.h]: Indeed.  I wonder how it ended up there; all I can think of is during rebasing.

**Review by tonycoz — APPROVED** [review]
