### PR TITLE
locale.c: Don't do asymmetric back out on failure

### LINKED ISSUE #23159: locale.t ends with panic "attempting to unlock already unlocked locale" on Mac OS X Tiger
On Mac OS X Tiger/i386 (darwin 8) when running the test suite 2 failures are observed. One in `run/locale.t` and one in `../lib/locale.t`.

```
Test Summary Report
-------------------
run/locale.t                                                       (Wstat: 65280 (exited 255) Tests: 41 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
run/todo.t                                                         (Wstat: 0 Tests: 6 Failed: 0)
  TODO passed:   3-4
../lib/locale.t                                                    (Wstat: 65280 (exited 255) Tests: 380 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=2908, Tests=1180577, 2206 wallclock secs (170.38 usr 33.76 sys + 1608.72 cusr 206.82 csys = 2019.68 CPU)
Result: FAIL
```

for `run/locale.t`
```
panic: locale.c: 4715: attempting to unlock already unlocked locale; depth was 0                                                            
Dubious, test returned 255 (wstat 65280, 0xff00)                                                                                            
All 41 subtests passed                                                                                                                      
(less 3 skipped subtests: 38 okay)
```

for `../lib/locale.t`
```
panic: locale.c: 4715: attempting to unlock already unlocked locale; depth was 0
Dubious, test returned 255 (wstat 65280, 0xff00)
All 380 subtests passed 
```

The issue is not observed on Tiger/powerpc but I'm not sure if that's just because all the PowerPC systems I have to test on are uniprocessor and this is a bug observed on multiprocessor systems or the issue is actually exclusive to the Intel build as there are version differences with components shipped with the OS (they're newer on the Intel build)

I built and ran the test suite using the following steps
`./Configure -Duseshrplib -Duselargefiles -Dusethreads -des -Dusedevel && make && make test`

### PR DESCRIPTION
**Pull request by khwilliamson**
This fixes #23159

When something goes wrong doing locale-aware string collation, the code attempts to carry on as well as can be expected.  prior to this commit the backout code was asymmetric, trying to undo things that had not been done.  This happened when the failure was early on.
     
In the case of this ticket, the platform has a defective locale that was detectable before getting very far along.
     
The solution adopted here is to jump to a different label for those early failures that does less backout than for later failures.

* This set of changes does not require a perldelta entry.

### CODE REVIEW

**Comment by Leont** [comment]
It's not clear to me if `free_me`, `sans_nuls` and `sans_highs` will be correctly freed when an error occurs.

**Comment by tonycoz** [comment]
There's a few paths where they can leak.

**Comment by sevan** [comment]
```
All tests successful.
Elapsed: 2660 sec
u=22.73  s=11.66  cu=2088.93  cs=219.98  scripts=2748  tests=1180795
```

**Comment by khwilliamson** [comment]
I've reexamined this commit, and don't see anything wrong with it.  It does look to me that the first two goto's can be replaced by returns, as nothing has been allocated yet.   But I don't see any leak paths. @tonycoz can you provide a case

File: locale.c [hunk 1]
```diff
@@ -10090,7 +10090,7 @@ Perl_mem_collxfrm_(pTHX_ const char *input_string,
     if (UNLIKELY(! xbuf)) {
         DEBUG_L(PerlIO_printf(Perl_debug_log,
                       "mem_collxfrm_: Couldn't malloc %zu bytes\n", xAlloc));
-        goto bad;
+        goto bad_no_strxfrm;
```
Comment (mauke) [inline locale.c:10116]: This looks like a potential memory leak to me. At this point, `sans_highs`, `sans_nuls`, and `free_me` may have been allocated, but `bad_no_strxfrm` skips over the `free()` calls.

Comment (khwilliamson) [reply locale.c:10116]: Somehow I got it into my head that that label had code to do the necessary cleanup, and was blind to the fact that it didn't.  But with the latest push, it should now.

**Comment by sevan** [comment]
Test suite still passes on Tiger/i386 with the latest version of the patch applied.
```
All tests successful.
Elapsed: 2294 sec
u=23.85  s=10.62  cu=1848.69  cs=199.30  scripts=2658  tests=1314307
```

**Review by tonycoz — APPROVED** [review]
