### PR TITLE
peep.c: Only remove expected empty if/else block structures

### LINKED ISSUE #23505: BBC: Blead Breaks Test::Inter
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.43 running under perl 5.43.2.

-----------------------------------------------------------------

BBC: Blead Breaks Test::Inter

Please see https://fast2-matrix.cpantesters.org/?dist=Test::Inter

---
**Flags**
- category=core
- severity=low
---
**Perl configuration**
```
Site configuration information for perl 5.43.2:

Configured by cpan at Tue Jul 29 13:49:40 EDT 2025.

Summary of my perl5 (revision 5 version 43 subversion 2) configuration:
  Commit id: 148136c313ee439bdf7c9faed3dbbb772c04a925
  Platform:
    osname=linux
    osvers=6.12.0-55.22.1.el10_0.x86_64
    archname=x86_64-linux
    uname='linux cjg-rhel10 6.12.0-55.22.1.el10_0.x86_64 #1 smp preempt_dynamic mon jul 14 04:43:00 edt 2025 x86_64 gnulinux '
    config_args='-des -Dprefix=/home/cpan/bin/perl -Dscriptdir=/home/cpan/bin/perl/bin -Dusedevel -Duse64bitall'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='14.2.1 20250110 (Red Hat 14.2.1-7)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib /usr/lib64 /usr/local/lib64
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/../lib64/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.39'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


---
@INC for perl 5.43.2:
    /home/cpan/bin/perl/lib/site_perl/5.43.2/x86_64-linux
    /home/cpan/bin/perl/lib/site_perl/5.43.2
    /home/cpan/bin/perl/lib/5.43.2/x86_64-linux
    /home/cpan/bin/perl/lib/5.43.2

---
Environment for perl 5.43.2:
    HOME=/home/cpan
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_ALL=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl/bin:/home/cpan/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
    PERL_BADLANG (unset)
    SHELL=/bin/bash
```

### LINKED ISSUE #23686: BBC: v5.43.2 breaks MAUKE/Switch-Plain-0.0501.tar.gz
**Description**

With commit v5.43.1-40-g75a310dd6d tests with debugging perls of MAUKE/Switch-Plain-0.0501.tar.gz are running into an assertion:

`perl: peep.c:3621: Perl_rpeep: Assertion `stub == OpSIBLING(OpSIBLING( cLOGOP->op_first ))' failed.`

Fail report: https://www.cpantesters.org/cpan/report/dd4f0c60-89ef-11f0-bb62-8268fbfb54e6

Bisect leads to

```
commit 75a310dd6d6a8cfcd7519613d66d46756b5265f0
Author: Richard Leach <rich+perl@hyphen-dash-hyphen.info>
Date:   Fri Dec 20 17:33:13 2024 +0000

    op.c/peep.c - Optimise away empty else{} blocks
    
    This is a replacement for https://github.com/Perl/perl5/pull/22745, which
    aimed to prevent the associated `OP_STUB` from being created in
    `Perl_newCONDOP` and subsequently removed in peep.c. However, doing that
    turned out to be unavoidable, since it is not safe to omit the `OP_STUB`
    if it is in scalar context, but `Perl_newCONDOP` runs before context is
    applied.
    
    This commit:
     * Re-adds the logic in `Perl_op_scope` to not wrap a bare `OP_STUB` in an
       `ENTER/LEAVE` pair.
     * Removes any relevant `OP_STUB`s in non-scalar context in `Perl_rpeep`.
     * Adds B::Deparse support
     * Adds a test based on the failures seen in https://github.com/Perl/perl5/issues/22866
```

**Steps to Reproduce**

`cpan -i MAUKE/Switch-Plain-0.0501.tar.gz`

**Expected behavior**

Worked up to this commit

**Perl configuration**

```
# perl -V output goes here
Summary of my perl5 (revision 5 version 43 subversion 2) configuration:
  Commit id: 7afd3f158f75d5730469889406f8f98c681d58c1
  Platform:
    osname=linux
    osvers=5.4.0-216-generic
    archname=x86_64-linux
    uname='linux k93focal 5.4.0-216-generic #236-ubuntu smp fri apr 11 19:53:21 utc 2025 x86_64 x86_64 x86_64 gnulinux '
    config_args='-Dprefix=/home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.43.2/b254 -Dmyhostname=k93focal -Dinstallusrbinperl=n -Uversiononly -Dusedevel -des -Ui_db -Dlibswanted=cl pthread socket inet nsl gdbm dbm malloc dl ld sun m crypt sec util c cposix posix ucb BSD gdbm_compat -Uuseithreads -Uuselongdouble -DEBUGGING=both'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2 -g'
    cppflags='-fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='9.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.31.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.31'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    DEBUGGING
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Aug 26 2025 20:20:28
  %ENV:
    PERL="/tmp/basesmoker-reloperl-X2Ur/bin/perl"
    PERL5LIB="/tmp/loop_over_bdir-1215702-hxGB3Y/Net-OpenVPN-DDNS-0.1-0/blib/arch:/tmp/loop_over_bdir-1215702-hxGB3Y/Net-OpenVPN-DDNS-0.1-0/blib/lib:/tmp/loop_over_bdir-1215702-hxGB3Y/Business-Shipping-DataFiles-1.02-0/blib/arch:/tmp/loop_over_bdir-1215702-hxGB3Y/Business-Shipping-DataFiles-1.02-0/blib/lib:/tmp/loop_over_bdir-1215702-hxGB3Y/Net-Async-WebService-lxd-0.03-0/blib/arch:/tmp/loop_over_bdir-1215702-hxGB3Y/Net-Async-WebService-lxd-0.03-0/blib/lib"
    PERL5OPT=""
    PERL5_CPANPLUS_IS_RUNNING="1215715"
    PERL5_CPAN_IS_RUNNING="1215715"
    PERL_CANARY_STABILITY_NOPROMPT="1"
    PERL_MM_USE_DEFAULT="1"
    PERL_USE_UNSAFE_INC="1"
  @INC:
    /tmp/loop_over_bdir-1215702-hxGB3Y/Net-OpenVPN-DDNS-0.1-0/blib/arch
    /tmp/loop_over_bdir-1215702-hxGB3Y/Net-OpenVPN-DDNS-0.1-0/blib/lib
    /tmp/loop_over_bdir-1215702-hxGB3Y/Business-Shipping-DataFiles-1.02-0/blib/arch
    /tmp/loop_over_bdir-1215702-hxGB3Y/Business-Shipping-DataFiles-1.02-0/blib/lib
    /tmp/loop_over_bdir-1215702-hxGB3Y/Net-Async-WebService-lxd-0.03-0/blib/arch
    /tmp/loop_over_bdir-1215702-hxGB3Y/Net-Async-WebService-lxd-0.03-0/blib/lib
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.43.2/b254/lib/site_perl/5.43.2/x86_64-linux
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.43.2/b254/lib/site_perl/5.43.2
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.43.2/b254/lib/5.43.2/x86_64-linux
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.43.2/b254/lib/5.43.2
    .
```

### LINKED ISSUE #23687: BBC: v5.43.2 breaks COSMICNET/CGI-Application-Plugin-YAML-0.03.tar.gz
**Description**

With commit v5.43.1-41-ge7778069bc the test t/pod-coverage.t starts to run into an assertion. The perl must be a DEBUGGING perl and it must have Test::Pod::Coverage installed, otherwise the test gets skipped.

Fail report: https://www.cpantesters.org/cpan/report/0b023688-8a03-11f0-800b-802d3c22ace3

Bisect leads to:

```
commit e7778069bc401e5729ab4da6d5fa9821098030bf
Author: Richard Leach <rich+perl@hyphen-dash-hyphen.info>
Date:   Fri Dec 20 21:08:41 2024 +0000

    op.h/op.c/peep.c - Optimise away empty if{} blocks
    
    This commit optimises away the OP_STUB associated with an empty `true`
    branch of an `OP_COND_EXPR`.
    
    The `OPf_SPECIAL` flag has been brought into use on the `OP_COND_EXPR`
    to indicate that it is the `else`, not the `if`, block that has been
    optimised away. This is purely for the benefit of B::Deparse.
```

**Steps to Reproduce**

`cpan -i COSMICNET/CGI-Application-Plugin-YAML-0.03.tar.gz`

**Expected behavior**

**Perl configuration**

```
# perl -V output goes here
Summary of my perl5 (revision 5 version 43 subversion 2) configuration:
  Commit id: 7afd3f158f75d5730469889406f8f98c681d58c1
  Platform:
    osname=linux
    osvers=5.4.0-216-generic
    archname=x86_64-linux
    uname='linux k93focal 5.4.0-216-generic #236-ubuntu smp fri apr 11 19:53:21 utc 2025 x86_64 x86_64 x86_64 gnulinux '
    config_args='-Dprefix=/home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.43.2/b254 -Dmyhostname=k93focal -Dinstallusrbinperl=n -Uversiononly -Dusedevel -des -Ui_db -Dlibswanted=cl pthread socket inet nsl gdbm dbm malloc dl ld sun m crypt sec util c cposix posix ucb BSD gdbm_compat -Uuseithreads -Uuselongdouble -DEBUGGING=both'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2 -g'
    cppflags='-fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='9.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.31.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.31'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    DEBUGGING
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Aug 26 2025 20:20:28
  %ENV:
    PERL="/tmp/basesmoker-reloperl-X2Ur/bin/perl"
    PERL5LIB="/tmp/loop_over_bdir-1215702-hxGB3Y/Net-OpenVPN-DDNS-0.1-0/blib/arch:/tmp/loop_over_bdir-1215702-hxGB3Y/Net-OpenVPN-DDNS-0.1-0/blib/lib:/tmp/loop_over_bdir-1215702-hxGB3Y/Business-Shipping-DataFiles-1.02-0/blib/arch:/tmp/loop_over_bdir-1215702-hxGB3Y/Business-Shipping-DataFiles-1.02-0/blib/lib:/tmp/loop_over_bdir-1215702-hxGB3Y/Net-Async-WebService-lxd-0.03-0/blib/arch:/tmp/loop_over_bdir-1215702-hxGB3Y/Net-Async-WebService-lxd-0.03-0/blib/lib"
    PERL5OPT=""
    PERL5_CPANPLUS_IS_RUNNING="1215715"
    PERL5_CPAN_IS_RUNNING="1215715"
    PERL_CANARY_STABILITY_NOPROMPT="1"
    PERL_MM_USE_DEFAULT="1"
    PERL_USE_UNSAFE_INC="1"
  @INC:
    /tmp/loop_over_bdir-1215702-hxGB3Y/Net-OpenVPN-DDNS-0.1-0/blib/arch
    /tmp/loop_over_bdir-1215702-hxGB3Y/Net-OpenVPN-DDNS-0.1-0/blib/lib
    /tmp/loop_over_bdir-1215702-hxGB3Y/Business-Shipping-DataFiles-1.02-0/blib/arch
    /tmp/loop_over_bdir-1215702-hxGB3Y/Business-Shipping-DataFiles-1.02-0/blib/lib
    /tmp/loop_over_bdir-1215702-hxGB3Y/Net-Async-WebService-lxd-0.03-0/blib/arch
    /tmp/loop_over_bdir-1215702-hxGB3Y/Net-Async-WebService-lxd-0.03-0/blib/lib
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.43.2/b254/lib/site_perl/5.43.2/x86_64-linux
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.43.2/b254/lib/site_perl/5.43.2
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.43.2/b254/lib/5.43.2/x86_64-linux
    /home/sand/src/perl/repoperls/installed-perls/host/k93focal/v5.43.2/b254/lib/5.43.2
    .
```

### PR DESCRIPTION
**Pull request by richardleach**
https://github.com/Perl/perl5/pull/23367 _expected_ that empty `OP_COND_EXPR`
branches would produce one of the following OP tree structures fit for removal:
```
  +-- stub
```
or
```
  +-- scope
    |
    +-- stub
```

GH #23505 showed that `{ BEGIN {} }` blocks will also generate the likes of:
```
  +--scope
    |
    +--stub
    |
    +--null (ex-nextstate)
```

This commit does the minimal possible to fix this bug - the peephole optimizer
now checks for the expected cases and ignores anything else.

Future commits may extend the optimization to remove this additional type of
structure. Additional tests have been added now and give a useful structure for
future commit tests to fit into.

-------------------------------------------------------------------------------
* This set of changes does not require a perldelta entry.

### CODE REVIEW

**Comment by richardleach** [comment]
Rather than handling the `BEGIN {}` case in the peephole optimizer, it seems tidier to handle it back in `Perl_op_scope`, ensuring that one of the expected `OP_STUB` patterns results.

However, initial work showed that `Perl_pmruntime` and `S_regmatch` (`case EVAL:`) would have to be amended to recognise bare `OP_STUB`s. (It would be nice if `S_regmatch` could be made to not execute OP trees that are functionally no-ops.)

I'll work on this a bit more in the background.

**Comment by leonerd** [comment]
> I'll work on this a bit more in the background.

By this, do you mean this PR is still in progress (and should be marked draft), or that you'll do that separately in a different PR? I.e. should we still review this one?

File: peep.c [hunk 1]
```diff
@@ -3590,41 +3590,110 @@ Perl_rpeep(pTHX_ OP *o)
...
+                        /*     cond_expr
+                         *         -condition-
+                         *         scope
+                         *             stub
+                         *         -else-
+                         */
+                            cLOGOP->op_other = trueop->op_next;
+                            op_sibling_splice(o, cLOGOP->op_first, 1, NULL);
+                            op_free(stub);
+                            op_free(trueop);
```
Comment (richardleach) [inline peep.c:3628]: I had forgotten that `op_free` will free kids, so this should be just `op_free(trueop)` before being merged.

**Comment by richardleach** [comment]
Apologies for the vagueness of that first comment!
* This PR is ready for review. (I added a comment about `op_free` just now, but don't let that prevent review.)
* The comment was to explain why I didn't just add the `BEGIN {}` case to the optimization and why there are placeholder comments in the source code instead.

Basically, this PR should fix #23505 as-is but I then intend to build on it later in this dev cycle.

**Comment by jkeenan** [comment]
> Apologies for the vagueness of that first comment!
> 
>     * This PR is ready for review. (I added a comment about `op_free` just now, but don't let that prevent review.)
> 
>     * The comment was to explain why I didn't just add the `BEGIN {}` case to the optimization and why there are placeholder comments in the source code instead.
> 
> 
> Basically, this PR should fix #23505 as-is but I then intend to build on it later in this dev cycle.

@richardleach can we move forward with this pull request?  Who should be reviewing it?

I ask because I anticipate other BBC breakage for distributions which use Test-Inter in their test suites, e.g., Date-Manip. Thanks.

**Comment by richardleach** [comment]
> Who should be reviewing it?

@leonerd, @tonycoz, @mauke - do any of you have time to review this PR? (If you're happy with it, please go ahead & merge it, as I might not be able to check in for several days.)

**Comment by khwilliamson** [comment]
I'm not competent in this area to review this, but given that no one is reviewing it in a timely manner, and it is early in the development cycles, to that it can be tweaked if necessary, and it is likely to fix a bunch of problems that keep arising in the field which are causing people to spend time that they otherwise wouldn't have to:

I'm merging it now
