### PR TITLE
`GetOpt::Std`: Fix `import` methods' indirect syntax

### LINKED ISSUE #21465: `Getopt::Std`: Indirect object syntax in the `import` methods
- https://github.com/Perl/perl5/blob/92ddeac03bb34a9c34a0187468d02fbb0a9cc4dd/lib/Getopt/Std.pm#L149

- https://github.com/Perl/perl5/blob/92ddeac03bb34a9c34a0187468d02fbb0a9cc4dd/lib/Getopt/Std.pm#L307

Should these not be `Getopt::Std->import;` instead?

https://perldoc.perl.org/perlobj#Indirect-Object-Syntax

### PR DESCRIPTION
**Pull request by rwp0**
Also some minor documention, formatting, styling

Fixes https://github.com/Perl/perl5/issues/21465

---

Add some tests for the scoped syntax

### CODE REVIEW

File: lib/Getopt/Std.pm [hunk 1]
```diff
@@ -14,11 +14,12 @@ Getopt::Std - Process single-character switches with switch clustering
...
 
     getopts('oif:');  # -o & -i are boolean flags, -f takes an argument
-		      # Sets $opt_* as a side effect.
-    getopts('oif:', \%opts);  # options as above. Values in %opts
-    getopt('oDI');    # -o, -D & -I take arg.
-                      # Sets $opt_* as a side effect.
-    getopt('oDI', \%opts);    # -o, -D & -I take arg.  Values in %opts
+		      # Sets $opt_* global variables as a side effect
+    getopts('oif:', \my %opts);  # Options as above, values in %opts
+
```
Comment (rwp0) [inline lib/Getopt/Std.pm]: This blank line helps to separate `getopts` and `getopt` visually since `s` is the only difference in their names.

File: lib/Getopt/Std.pm [hunk 2]
```diff
@@ -39,8 +40,8 @@ The C<getopts()> function returns true unless an invalid option was found.
 The C<getopt()> function is similar, but its argument is a string containing
 all switches that take an argument.  If no argument is provided for a switch,
 say, C<y>, the corresponding C<$opt_y> will be set to an undefined value.
-Unspecified switches are silently accepted.  Use of C<getopt()> is not
-recommended.
+Unspecified switches are silently accepted.  Use of C<getopt()> is B<not
```
Comment (rwp0) [inline lib/Getopt/Std.pm:42]: `getopt` is not recommended, make this bold, so that it's not somewhat hidden at the end.

File: lib/Getopt/Std.pm [hunk 3]
```diff
@@ -146,7 +147,7 @@ sub getopt (;$$) {
     }
     unless (ref $hash) { 
 	local $Exporter::ExportLevel = 1;
-	import Getopt::Std;
+	Getopt::Std->import;
```
Comment (rwp0) [inline lib/Getopt/Std.pm:149]: I'm still not [very sure](https://perldoc.perl.org/functions/import), it might be due to some magic by the `Exporter`, but its "argument" is a bareword, so looks like the reverse method syntax.

Comment (Leont) [reply lib/Getopt/Std.pm:149]: Yeah this is indirect syntax.

**Comment by rwp0** [comment]
If this is approved I can begin a general work of converting other indirect object notations in the Core distributions/utilities.

File: lib/Getopt/Std.pm [hunk 4]
```diff
@@ -14,11 +14,11 @@ Getopt::Std - Process single-character switches with switch clustering
     use Getopt::Std;
 
     getopts('oif:');  # -o & -i are boolean flags, -f takes an argument
-		      # Sets $opt_* as a side effect.
-    getopts('oif:', \%opts);  # options as above. Values in %opts
-    getopt('oDI');    # -o, -D & -I take arg.
-                      # Sets $opt_* as a side effect.
-    getopt('oDI', \%opts);    # -o, -D & -I take arg.  Values in %opts
+		      # Sets $opt_* global variables as a side effect
+    getopts('oif:', \my %opts);  # Options as above, values in %opts
```
Comment (jkeenan) [inline lib/Getopt/Std.pm:18]: While recommending `\my %opts` is probably better guidance for a Synopsis than a reference to a global variable, I don't see any tests for that syntax in `lib/Getopt/Std.t`.  Can you add unit tests that exercise this syntax?  (I suspect the p.r. will be good to go thereafter).  Thanks.

**Review by jkeenan — CHANGES_REQUESTED** [review]

File: lib/Getopt/Std.pm (hunk 4 above)
Comment (jkeenan) [reply lib/Getopt/Std.pm:18]: Looks good.  Unless some new objection emerges, let's merge it into blead tomorrow.

**Review by jkeenan — APPROVED** [review]

**Comment by jkeenan** [comment]
> If this is approved I can begin a general work of converting other indirect object notations in the Core distributions/utilities.

Recommend posting to mailing list a list of the distros/utilities which will be part of this effort.  Clear out any objections in advance.

**Comment by rwp0** [comment]
> If this is approved I can begin a general work of converting other indirect object notations in the Core distributions/utilities.

Okay, thanks for the tip!
