### PR TITLE
Don't use buggy POSIX 2008 locales on Darwin

### LINKED ISSUE #21556: Darwin doesn't work properly for POSIX 2008 locale operations
**Description**

blead smoke tests are failing on Darwin.  I have tracked it down to a bug in their code.  Attached is a C reproducer not involving Perl.  I have not tried to boil it down to fewer lines.
[test.txt](https://github.com/Perl/perl5/files/12885481/test.txt)
**Steps to Reproduce**

Compile the attached program, and call the binary with something like 4.888.
On Darwin, it prints 4; on other boxes, 4.888.  Then change to use "4,888".  On Darwin it prints 4.888; on other boxes it prints 4.
This indicates that Darwin thinks the locale radix character is a comma, when in fact the locale is C, so it is a dot.

**Expected behavior**

The output should be as I described above under "other boxes"

**Perl configuration**

```
# perl -V output goes here
``Summary of my perl5 (revision 5 version 39 subversion 4) configuration:
  Derived from: 54b519ce9f48eefc96f484f5b7b9596382829294
  Platform:
    osname=darwin
    osvers=23.0.0
    archname=darwin-thread-multi-2level
    uname='darwin grannysmith.local 23.0.0 darwin kernel version 23.0.0: fri sep 15 14:40:03 pdt 2023; root:xnu-10002.1.13~1release_arm64_vmapple arm64 '
    config_args='-des -Uversiononly -Dprefix=/Users/khw/devel -Dusedevel -Doptimize=-O0 -DDEBUGGING -A'optimize=-g3' -A'optimize=-ggdb3' -A'optimize=-gdwarf-3' -A'optimize=-g3' -Accflags='-Wno-deprecated' -Dman1dir='none' -Dman3dir='none' -Dcc=g++ -Dusecbacktrace -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='g++'
    ccflags ='-fno-common -DPERL_DARWIN -no-cpp-precomp -mmacosx-version-min=14.0 -Wno-deprecated -DDEBUGGING'
    optimize='-O0 -g3 -ggdb3 -gdwarf-3 -g3'
    cppflags='-no-cpp-precomp -fno-common -DPERL_DARWIN -no-cpp-precomp -mmacosx-version-min=14.0 -Wno-deprecated -DDEBUGGING'
    ccversion=''
    gccversion='Apple LLVM 15.0.0 (clang-1500.0.40.1)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=8
    longdblkind=0
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags =' -mmacosx-version-min=14.0'
    libpth=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/lib /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib /usr/lib
    libs= 
    perllibs=
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=14.0 -bundle -undefined dynamic_lookup'


Characteristics of this binary (from libperl): 
  Compile-time options:
    DEBUGGING
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_TRACK_MEMPOOL
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Locally applied patches:
    uncommitted-changes
  Built under darwin
  Compiled at Oct 12 2023 23:57:31
  %ENV:
    PERL5OPT="-w"
    PERL_DIFF_TOOL="wgdiff"
    PERL_POD_PEDANTIC="1"
    PERL_TEST_HARNESS_ASAP="1"
  @INC:
    /Users/khw/perl/working/lib
    /Users/khw/perl/working/t
    /Users/khw/devel/lib/perl5/site_perl/5.39.4/darwin-thread-multi-2level
    /Users/khw/devel/lib/perl5/site_perl/5.39.4
    /Users/khw/devel/lib/perl5/5.39.4/darwin-thread-multi-2level
    /Users/khw/devel/lib/perl5/5.39.4

`

### PR DESCRIPTION
**Pull request by khwilliamson**
This fixes #21556

A non-perl C reproducer program is attached to that bug report.

This shows that the current Darwin gets confused.  The solution here is to turn off the POSIX 2008 locale interface, which means that Darwin perls aren't thread-safe w.r.t locale handling.

Past experience has left me cynical about Apple's commitment to fixing reported bugs.  I have examined their locale-handling code previously (not about this bug), and it looked like an early port of *BSD code, which had many locale bugs, which *BSD seem to eventually fix.

### CODE REVIEW

**Comment by jkeenan** [comment]
The string `-DNO_POSIX_2008_LOCALE` was mentioned in the perldelta for 5.38.0.  Should this patch get a mention in perldelta as well?

**Comment by khwilliamson** [comment]
On 10/15/23 05:49, James E Keenan wrote:
> The string |-DNO_POSIX_2008_LOCALE| was mentioned in the perldelta for 
> 5.38.0. Should this patch get a mention in perldelta as well?

After all the locale patches get merged, I'll write up a perldelta for 
the whole thing.

File: hints/darwin.sh [hunk 1]
```diff
@@ -364,6 +364,10 @@ esac
 # Darwin's querylocale() has races
 ccflags="$ccflags -DNO_THREAD_SAFE_QUERYLOCALE"
 
+# But it doesn't much matter because the whole implementation has bugs [GH
+# #21556]
+ccflags="$ccflags -DNO_POSIX_2008_LOCALE"
+
```
Comment (jkeenan) [inline hints/darwin.sh:370]: The patch itself is minimal, therefore easily rolled back if harmful.  So +1 from me -- but I have no Darwin to test this on.

**Review by jkeenan — APPROVED** [review]

**Comment by khwilliamson** [comment]
A smoke-me test passed before I issued this pull request [https://perl.develop-help.com/?b=smoke-me%2Fkhw-debug_darwing](url)
