### PR TITLE
fix set magic handling for scalar reverse and an index() optimization

### LINKED ISSUE #17737: panic: sv_len_utf8 cache 1 real 0 for  at
This is a bug report for perl from sergey.aleynikov@gmail.com,
generated with the help of perlbug 1.41 running under perl 5.31.10.

[Please describe your issue here]

While fuzzing perl v5.31.9-70-g0c96aa4b7b built with afl and run
under libdislocator, I found the following program

```
length reverse
              chop for split
                            chr,"\x{c00}0"
```
```
00000000  6c 65 6e 67 74 68 20 72  65 76 65 72 73 65 0c 63  |length reverse.c|
00000010  68 6f 70 20 66 6f 72 20  73 70 6c 69 74 0b 63 68  |hop for split.ch|
00000020  72 2c 22 5c 78 7b 63 30  30 7d 00 00 30 22        |r,"\x{c00}..0"|
```
to emit panic():

panic: sv_len_utf8 cache 1 real 0 for  at

GDB stack trace at the point of croak() is:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7c24535 in __GI_abort () at abort.c:79
#2  0x00005555557270b6 in Perl_vcroak (pat=0x555555b48a90 "panic: %s cache %lu real %lu for %-p", args=0x7fffffffdc90) at util.c:1745
#3  0x00005555557273e2 in Perl_croak (pat=0x555555b48a90 "panic: %s cache %lu real %lu for %-p") at util.c:1803
#4  0x00005555557d2ad1 in S_assert_uft8_cache_coherent (func=0x555555b489b3 "sv_len_utf8", from_cache=1, real=0, sv=0x555555c3afc8) at sv.c:7877
#5  0x00005555557d0c4e in Perl_sv_len_utf8_nomg (sv=0x555555c3afc8) at sv.c:7257
#6  0x0000555555811f4d in Perl_pp_length () at pp.c:3119
#7  0x00005555557206b2 in Perl_runops_debug () at dump.c:2571
#8  0x00005555555f083e in S_run_body (oldscope=1) at perl.c:2759
#9  0x00005555555efdbc in perl_run (my_perl=0x555555c15260) at perl.c:2682
#10 0x00005555555a2155 in main (argc=2, argv=0x7fffffffe1b8, env=0x7fffffffe1d0) at perlmain.c:134
```

This is a regression between 5.26 and 5.28, bisect points to 47836a13cc4c999c9b3589c6797d6769b52c37fd is the first bad commit
commit 47836a13cc4c999c9b3589c6797d6769b52c37fd
Author: Zefram <zefram@fysh.org>
Date:   Fri Dec 8 19:23:29 2017 +0000

    don't lose mark when pp_reverse extends stack

    Nullary reverse needs to extend the stack to push its result scalar.
    It was actually extending the stack, but doing so invalidated MARK,
    which it relied upon to place the stack pointer afterwards.  Upon stack
    reallocation it was therefore leaving the stack pointer pointing to the
    freed stack memory.  Reformulate stack manipulation to not rely on MARK
    after extending.  Fixes [perl #132544].
```
[Please do not change anything below this line]
Flags:
category=core
severity=medium
Site configuration information for perl 5.31.10:

Configured by root at Fri Mar 13 17:15:02 MSK 2020.

Summary of my perl5 (revision 5 version 31 subversion 10) configuration:
Commit id: 0c96aa4
Platform:
osname=linux
osvers=4.19.0-8-amd64
archname=x86_64-linux
uname='linux dorothy 4.19.0-8-amd64 #1 smp debian 4.19.98-1 (2020-01-26) x86_64 gnulinux '
config_args='-de -Dusedevel -Doptimize=-O2'
hint=recommended
useposix=true
d_sigaction=define
useithreads=undef
usemultiplicity=undef
use64bitint=define
use64bitall=define
uselongdouble=undef
usemymalloc=n
default_inc_excludes_dot=define
bincompat5005=undef
Compiler:
cc='cc'
ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
optimize='-O2'
cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
ccversion=''
gccversion='8.3.0'
gccosandvers=''
intsize=4
longsize=8
ptrsize=8
doublesize=8
byteorder=12345678
doublekind=3
d_longlong=define
longlongsize=8
d_longdbl=define
longdblsize=16
longdblkind=3
ivtype='long'
ivsize=8
nvtype='double'
nvsize=8
Off_t='off_t'
lseeksize=8
alignbytes=8
prototype=define
Linker and Libraries:
ld='cc'
ldflags =' -fstack-protector-strong -L/usr/local/lib'
libpth=/usr/local/lib /usr/lib/gcc/x86_64-linux-gnu/8/include-fixed /usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
libc=libc-2.28.so
so=so
useshrplib=false
libperl=libperl.a
gnulibc_version='2.28'
Dynamic Linking:
dlsrc=dl_dlopen.xs
dlext=so
d_dlsymun=undef
ccdlflags='-Wl,-E'
cccdlflags='-fPIC'
lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'

@inc for perl 5.31.10:
lib
/usr/local/lib/perl5/site_perl/5.31.10/x86_64-linux
/usr/local/lib/perl5/site_perl/5.31.10
/usr/local/lib/perl5/5.31.10/x86_64-linux
/usr/local/lib/perl5/5.31.10

Environment for perl 5.31.10:
HOME=/home/afl
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE=en_US.UTF-8
LC_TIME=C
LD_LIBRARY_PATH (unset)
LOGDIR (unset)
PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.30.0-dbg/bin:/opt/local/bin:/usr/texbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PERLBREW_HOME=/home/afl/.perlbrew
PERLBREW_MANPATH=/home/afl/perlbrew/perls/perl-5.30.0-dbg/man
PERLBREW_PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.30.0-dbg/bin
PERLBREW_PERL=perl-5.30.0-dbg
PERLBREW_ROOT=/home/afl/perlbrew
PERLBREW_SHELLRC_VERSION=0.88
PERLBREW_VERSION=0.88
PERL_BADLANG (unset)
```

### LINKED ISSUE #17739: $lexical = (index($x, y) == -1) optimization returns the right side
Module:

**Description**

7e8d786b optimized code like:

  $lexical = (index(...) == -1);

into an index op with flags that makes it assign to $lexical.  Unfortunately that new operation returns the result of the == rather than $lexical.  For example with 5.18.3:
```
$ ~/perl/5.18.3-dbg/bin/perl5.18.3 -le 'my $x; ($x = (index($y, $z) == -1)) =~ s/^/x/; print $x'
x
```

but with blead:

```
$ ./perl -le 'my $x; ($x = (index($y, $z) == -1)) =~ s/^/x/; print $x'
Modification of a read-only value attempted at -e line 1.
```

Note that without the index this works as expected:
```
$ ./perl -le 'my $x; ($x = 1) =~ s/^/x/; print $x'
x1
```

**Expected behavior**

The assignment should return the modifiable lvalue for $lexical

**Perl configuration**

```
Summary of my perl5 (revision 5 version 31 subversion 11) configuration:
  Commit id: ece42804593a3366ce48ea404a2c0c60063eeb1e
  Platform:
    osname=linux
    osvers=4.19.0-6-amd64
    archname=x86_64-linux
    uname='linux mars 4.19.0-6-amd64 #1 smp debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2 -g'
    cppflags='-fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='8.3.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/gcc/x86_64-linux-gnu/8/include-fixed /usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib /lib64 /usr/lib64
    libs=-lpthread -lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.28.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.28'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector-strong'

Characteristics of this binary (from libperl): 
  Compile-time options:
    DEBUGGING
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Apr 22 2020 14:46:25
  %ENV:
    PERLBREW_BASHRC_VERSION="0.43"
    PERLBREW_HOME="/home/tony/.perlbrew"
    PERLBREW_MANPATH=""
    PERLBREW_PATH="/home/tony/perl5/perlbrew/bin"
    PERLBREW_ROOT="/home/tony/perl5/perlbrew"
    PERLBREW_VERSION="0.67"
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.31.11/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.31.11
    /usr/local/lib/perl5/5.31.11/x86_64-linux
    /usr/local/lib/perl5/5.31.11

```

### PR DESCRIPTION
**Pull request by tonycoz**
fixes #17737 fixes #17739 (github didn't pick it up from the commits)

### CODE REVIEW

**Comment by xsawyerx** [comment]
@iabyn, @ilmari, ping. :)

File: pp.c [hunk 1]
```diff
@@ -3522,9 +3522,11 @@ PP(pp_index)
     if (PL_op->op_private & OPpTRUEBOOL) {
         PUSHs( ((retval != -1) ^ cBOOL(PL_op->op_private & OPpINDEX_BOOLNEG))
                     ? &PL_sv_yes : &PL_sv_no);
-        if (PL_op->op_private & OPpTARGET_MY)
+        if (PL_op->op_private & OPpTARGET_MY) {
             /* $lex = (index() == -1) */
             sv_setsv(TARG, TOPs);
+            SETTARG;
```
Comment (ilmari) [inline pp.c]: Isn't the `SETs(TARG)` part of `SETTARG` redundant when we've just done `sv_setsv(TARG, TOPs)`?
I.e. couldn't this just be `SvSETMAGIC(TARG)`?

Comment (Leont) [reply pp.c]: Or just call `sv_setsv_mg(TARG, TOPs)`?

Comment (tonycoz) [reply pp.c]: That would break the fix for returning the lexical, see #17739 

The code could be clearer though, to avoid pushing the wrong SV, I'll re-work this.

Comment (xsawyerx) [reply pp.c]: @ilmari, @leont, do you consider this resolved now?
