### PR TITLE
Ensure stack is in consistent state while restoring SAVEt_HINTS (fixes #17903)

### LINKED ISSUE #17903: SIGSEGV if you croak() from inside free magic invoked by tidying up SAVEt_HINTS + hintsthash
I am still investigating the exact situation that triggers it, so I might alter the subject line while I''m working, but....

I have some code that inserts an SV into the (localized) hints hash, which has `free` magic on it. In fact that is the only magic hook, which is why it is there. I intend to run some code when the hints hash is cleared up. If my code doesn't `croak`, then all works as expected.

But, if I `croak` from somewhere inside that free magic, I get a segfault from perl itself. A stack trace from 5.30:

```
Program received signal SIGSEGV, Segmentation fault.
Perl_leave_scope (my_perl=my_perl@entry=0x5555558aa2a0, base=base@entry=0) at scope.c:922
922     scope.c: No such file or directory.
(gdb) bt
#0  Perl_leave_scope (my_perl=my_perl@entry=0x5555558aa2a0, base=base@entry=0)
    at scope.c:922
#1  0x00005555555bd803 in S_my_exit_jump (my_perl=my_perl@entry=0x5555558aa2a0)
    at perl.c:5327
#2  0x00005555555c6b8e in Perl_my_failure_exit (my_perl=my_perl@entry=0x5555558aa2a0)
    at perl.c:5311
#3  0x000055555569fdc7 in Perl_die_unwind (my_perl=my_perl@entry=0x5555558aa2a0, 
    msv=msv@entry=0x5555560bed90) at pp_ctl.c:1815
#4  0x000055555563359a in Perl_vcroak (my_perl=0x5555558aa2a0, 
    pat=pat@entry=0x7ffff7934e9b "TODO test croak", args=args@entry=0x7fffffffd850)
    at util.c:1711
#5  0x00005555556337ce in Perl_croak_nocontext (
    pat=pat@entry=0x7ffff7934e9b "TODO test croak") at util.c:1745
#6  0x00007ffff7931fcb in on_free_compclassmeta (my_perl=<optimized out>, 
    sv=<optimized out>, mg=<optimized out>) at lib/Object/Pad.xs:697
#7  0x000055555563a041 in S_mg_free_struct (my_perl=my_perl@entry=0x5555558aa2a0, 
    sv=sv@entry=0x5555560be880, mg=0x5555560c2ae0) at mg.c:558
#8  0x000055555563ab71 in Perl_mg_free (my_perl=my_perl@entry=0x5555558aa2a0, 
    sv=sv@entry=0x5555560be880) at mg.c:594
#9  0x0000555555661c20 in Perl_sv_clear (my_perl=my_perl@entry=0x5555558aa2a0, 
    orig_sv=orig_sv@entry=0x555556111388) at sv.c:6599
#10 0x0000555555662396 in Perl_sv_free2 (my_perl=my_perl@entry=0x5555558aa2a0, 
    sv=0x555556111388, rc=<optimized out>) at sv.c:7093
#11 0x0000555555694e04 in S_SvREFCNT_dec (sv=<optimized out>, my_perl=0x5555558aa2a0)
    at inline.h:216
#12 Perl_leave_scope (my_perl=my_perl@entry=0x5555558aa2a0, base=base@entry=25)
    at scope.c:1350
#13 0x00005555555ab01b in Perl_block_end (my_perl=my_perl@entry=0x5555558aa2a0, 
    floor=25, seq=<optimized out>) at op.c:5253
#14 0x00005555555f62a9 in Perl_yyparse (my_perl=my_perl@entry=0x5555558aa2a0, 
    gramtype=gramtype@entry=258) at perly.y:125
#15 0x00005555555c59f3 in S_parse_body (xsinit=0x55555559c580 <xs_init>, env=0x0, 
    my_perl=<optimized out>) at perl.c:2531
#16 perl_parse (my_perl=<optimized out>, xsinit=0x55555559c580 <xs_init>, 
    argc=<optimized out>, argv=<optimized out>, env=0x0) at perl.c:1822
#17 0x000055555559c3c3 in main (argc=<optimized out>, argv=<optimized out>, 
    env=<optimized out>) at perlmain.c:126
```

When run on a debugperl I get a slightly more exciting failure:

```
TODO test croak at t/30unit-class.t line 23.
panic: leave_scope inconsistency 56 at t/30unit-class.t line 23.
```

The code printing that number 56 is because it looked at the next save type from the savestack and didn't recognise it. Oddly, when I wrote some savestack-debugging code relating to #17895 - before I realised the non-constant nature of SAVEt_HINTS.

What I *suspect* is going on here is that the free magic on my SV is being invoked at a time after `Perl_leave_scope()` has popped the type/ptr/i32 off the save stack but *before* it has popped the second pointer as part of the hints HV. The savestack now isn't in a consistent state, meaning the croak that runs inside my free magic sees an inconsistent state of the save stack, and this causes further upset.

I suspect a fix for #17895 would fix this bug.

### PR DESCRIPTION
**Pull request by leonerd**
`SAVEt_HINTS` has a non-constant savestack structure. If the `HINT_LOCALIZE_HH` flag was set it pushes an additional pointer. In some complex code scenarios it is possible reënter Perl code while destroying nested `PL_hintgv` hashes (for example, if any stored objects contain `free` magic). Because of this, it is important that we pop the extra value from the save stack before any other code can be invoked, so if they need to inspect or alter the save stack, they can do so in a consistent manner.

See also

  https://github.com/Perl/perl5/issues/17895

### CODE REVIEW

**Comment by leonerd** [comment]
Even if this fix is applied, I shall likely adjust and reshape the code as part of #17895 anyway.

**Comment by leonerd** [comment]
Anyone fancy reviewing this? @ilmari, @arc et.al - you're usually good with these bits and pieces.

@iabyn - your name popped up around some of this code the on the previous bugfix (way back in https://github.com/Perl/perl5/issues/7131). Any thoughts here?

File: scope.c [hunk 1]
```diff
@@ -1348,7 +1348,12 @@ Perl_leave_scope(pTHX_ I32 base)
 	    break;
 
 	case SAVEt_HINTS:
+        {
```
Comment (ilmari) [inline scope.c:1351]: The perl style is to indent the braces to the same level as the `case` keyword. Aslo, new code should use spaces for identation, not tabs.

Comment (leonerd) [reply scope.c:1351]: Ah I was wondering about spaces vs. tabs; this file is full of tabs all around the area I'm working. But I can adjust my newly-added lines to be spaces.

Comment (leonerd) [reply scope.c:1351]: Also, if you view the file outside of github you'll see the braces *are* aligned with the `case`. The difference is that the `case` line begins with a tab, whereas the braces line starts with 8 spaces. Because of the two leading columns of `diff` output to print the "+ " here, it means that visually the brace looks like it's in column 10, while the `case` is still on column 8.

Comment (leonerd) [reply scope.c:1351]: See also - https://twitter.com/cpan_pevans/status/1277026253711777793

But in summary, what should I do here? My newly-added brace line is space-indented, the previous `case` line is tabbed. They do align for real, their alignment is just being messed up by diff. Should I leave the code as it is, or edit the `case` line to be space-indented too?

Comment (karenetheridge) [reply scope.c:1351]: my $0.02: make the minimum number of changes in this commit, and then we can reformat the file later in a different commit/PR to make everything consistent.

Comment (leonerd) [reply scope.c:1351]: OK; as of 1a15b8e0a5 all the newly-added lines are done with only spaces. That things don't appear to line up is a github/diff artefact of mixed spaces/tabs - see my tweet link. I am happy to assert it does line up nicely when viewed for real.

**Comment by ilmari** [comment]
Would it be feasible to write a test for this? Even just something that would crash or assert without the fix.

File: scope.c [hunk 2]
```diff
@@ -1348,7 +1348,12 @@ Perl_leave_scope(pTHX_ I32 base)
...
+	    HV *was_hinthv;
             a0 = ap[0]; a1 = ap[1];
+            if (a0.any_i32 & HINT_LOCALIZE_HH) {
```
Comment (atoomic) [inline scope.c:1354]: I would suggest moving that `if` block just one line after, as we are only going to use `was_hinthv` is `PL_hints & HINT_LOCALIZE_HH`
otherwise this looks good

**Comment by leonerd** [comment]
@ilmari I really had hoped to be able to write a test, but so far the exact nature of such a test eludes me. I have a few promising starts which turn out not to crash, and also Ribasushi has attempted at https://github.com/karenetheridge/B-Hooks-EndOfScope/pull/8. Meanwhile, I do have the Object::Pad tests which demonstrate the failure, but that's from an XS file over 2k lines long, so not very minimal.

File: scope.c (hunk 2 above)
Comment (leonerd) [reply scope.c:1354]: Nope, the point is that we have to `SSPOPPTR` which applies a globally-stateful change *before* we run any other code. Such as side-effects of `free` magic run as a result of `SvREFCNT_dec`ing here.

Comment (leonerd) [reply scope.c:1354]: Really, the true bug here is the non-constant stack shape of `SAVEt_HINTS` itself - which I aim to fix in #17895. This code here is currently very subtle because it contains the one lone instance of an `SSPOP*` macro in `Perl_leave_scope`, which is otherwise clean without them.

Comment (atoomic) [reply scope.c:1354]: thanks for your answer

**Comment by ilmari** [comment]
LGTM. Please squash into a single commit before merging.

**Review by ilmari — APPROVED** [review]
LGTM

**Comment by leonerd** [comment]
force-pushed a squash commit atop latest blead. If it still tests OK I'll merge it then

**Comment by leonerd** [comment]
The `testsuite / cygwin (pull_request)` CI test still fails, but it looks like a platform setup problem unrelated to this change. The fact it passes everywhere else gives me confidence to just merge this now.

```

Run path %GITHUB_WORKSPACE%\cygwin\bin;%GITHUB_WORKSPACE%\cygwin\usr\bin
  path %GITHUB_WORKSPACE%\cygwin\bin;%GITHUB_WORKSPACE%\cygwin\usr\bin
  sh -c "mkdir -p ~; cd ~; echo \"$GITHUB_REPOSITORY\"; git clone -qn \"***github.com/$GITHUB_REPOSITORY\" work ; cd work ; if [ \"$GITHUB_EVENT_NAME\" = pull_request ] ; then git fetch origin \"$GITHUB_REF\" ; fi ; git checkout \"$GITHUB_SHA\""
  shell: C:\windows\system32\cmd.EXE /D /E:ON /V:OFF /S /C "CALL "{0}""
  env:
    PERL_SKIP_TTY_TEST: 1
    CONTINUOUS_INTEGRATION: 1
    GITHUB_TOKEN: ***
Perl/perl5
From https://github.com/Perl/perl5
 * branch                  refs/pull/17904/merge -> FETCH_HEAD
fatal: reference is not a tree: 5fa8afda7456b51811945687137edd5a1f3ad208
##[error]Process completed with exit code 128.
```
