### PR TITLE
op.c - Restrict nested eval/BEGIN blocks to a user controllable maximum

### LINKED ISSUE #20176: segfault with BEGIN and eval
**Description**
Our guards against stackoverflow from recursion dont cover the case of a BEGIN inside of an eval. With appropriately crafted code we can trigger a segfault inside of an eval.

**Steps to Reproduce**
```
./perl -le'sub f{ eval "BEGIN{ f() }" } f()'
```

**Expected behavior**
Some kind of catchable exception, not a segfault.

**Perl configuration**
```
$ ./perl -Ilib -V
Summary of my perl5 (revision 5 version 37 subversion 4) configuration:
  Commit id: 6dacde6e70aa89d33e9b44e2c00050775261d8fb
  Platform:
    osname=linux
    osvers=5.14.0-1049-oem
    archname=x86_64-linux-thread-multi
    uname='linux oncidium 5.14.0-1049-oem #56-ubuntu smp fri aug 12 10:23:08 utc 2022 x86_64 x86_64 x86_64 gnulinux '
    config_args='-Dusethreads -Doptimize=-g -d -Dusedevel -Dcc=ccache gcc -Dld=gcc -DDEBUGGING'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='gcc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-g'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='9.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='gcc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.31.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.31'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    DEBUGGING
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_TRACK_MEMPOOL
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Aug 28 2022 10:54:12
  %ENV:
    PERLBREW_CONFIGURE_FLAGS="-de -Dcc=ccache\ gcc -Dld=gcc"
    PERLBREW_HOME="/home/yorton/.perlbrew"
    PERLBREW_MANPATH="/home/yorton/perl5/perlbrew/perls/perl-5.34.1/man"
    PERLBREW_PATH="/home/yorton/perl5/perlbrew/bin:/home/yorton/perl5/perlbrew/perls/perl-5.34.1/bin"
    PERLBREW_PERL="perl-5.34.1"
    PERLBREW_ROOT="/home/yorton/perl5/perlbrew"
    PERLBREW_SHELLRC_VERSION="0.88"
    PERLBREW_VERSION="0.88"
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.37.4/x86_64-linux-thread-multi
    /usr/local/lib/perl5/site_perl/5.37.4
    /usr/local/lib/perl5/5.37.4/x86_64-linux-thread-multi
    /usr/local/lib/perl5/5.37.4
```

### PR DESCRIPTION
**Pull request by demerphq**
Nested BEGIN blocks can cause us to segfault by exhausting
the C stack. Eg:

    perl -le'sub f { eval "BEGIN { f() }" } f()'

will segfault. This adds a new interpreter var PL_eval_begin_nest_depth
to keep track of how many layer of eval/BEGIN we have seen, and a new
reserved variable called ${^MAX_NESTED_EVAL_BEGIN_BLOCKS} which can be
used to raise or lower the limit. When set to 0 it blocks BEGIN entirely,
which might be useful from time to time.

This fixes https://github.com/Perl/perl5/issues/20176

### CODE REVIEW

File: INSTALL [hunk 1]
```diff
@@ -528,6 +528,31 @@ C<-Accflags=-DNO_PERL_HASH_ENV>.
...
+=over 2
+
+=item PERL_MAX_NESTED_EVAL_BEGIN_BLOCKS_DEFAULT
+
+This define is used to control the default maximum number of nested
+eval/BEGIN statements. Currently each C<BEGIN> block inside of an C<eval
+EXPR> operation will uses a certain number of frames of the perl
+internal C stack, and this value is used to prevent stack overflows.
+Normally this is 1000 but it can be configured to another value, for
+instance 100, like this
```
Comment (tonycoz) [inline INSTALL]: This doesn't just limit the number of levels of BEGIN within eval, but the nesting levels of BEGINs in general.

This includes `use ModuleName;` since that's just `BEGIN { require ModuleName; ModuleName->import }`.

So the name of the variables and the documentation only talks about eval, but it has a more general effect.

File: op.c [hunk 2]
```diff
@@ -10717,11 +10717,32 @@ S_process_special_blocks(pTHX_ I32 floor, const char *const fullname,
...
+                sv_setiv(max_nest_sv, PERL_MAX_NESTED_EVAL_BEGIN_BLOCKS_DEFAULT);
+            max_nest_iv = SvIV(max_nest_sv);
+            if (max_nest_iv < 0) {
+                max_nest_iv = PERL_MAX_NESTED_EVAL_BEGIN_BLOCKS_DEFAULT;
+                sv_setiv(max_nest_sv, max_nest_iv);
+            }
+
+            if (PL_eval_begin_nest_depth >= max_nest_iv) {
+                Perl_croak(aTHX_ "Too many nested BEGIN blocks, maximum of %d allowed",
+                             (int)max_nest_iv);
```
Comment (tonycoz) [inline op.c]: You could use `IVdf` here to avoid the cast.

File: INSTALL (hunk 1 above)
Comment (demerphq) [reply INSTALL]: >This doesn't just limit the number of levels of BEGIN within eval, but the nesting levels of BEGINs in general.

No, that isn't correct. It looks like that but it does not work like that.

Consider this code:

```
BEGIN { $a++; BEGIN { $b++; BEGIN{ $c++ }  } } }
```
this code will complete parsing the innermost BEGIN first. So it increments the counter, executes the BEGIN, and then the  counter is decremented. It then finishes parsing the second BEGIN, and does the same thing. That is it is equivalent to this code:

```
BEGIN { $c++; }
BEGIN { $b++; }
BEGIN { $a++; }
```

so even though there are three nested BEGIN's textually, they are executed in the order of completion and thus the inner necessarily finishes before the outer.

Only when the code inside the BEGIN does an eval (or require, same thing) does this counter get incremented without being immediately decremented.

BEGIN {} blocks are executed *immediately* after parsing and then thrown away.  This means they don't nest without an eval inside them. Be aware that require is just a special type of eval.

> This includes use ModuleName; since that's just BEGIN { require ModuleName; ModuleName->import }.

Yes, it is true that affects such case, because 'require' is actually an eval internally that rethrows its exceptions.

Ill tweak the wording anyway, and maybe add a comment. The fact that BEGIN{} dont nest due to execution order unless they contain an eval/required is not obvious. I actually wrote tests to check this and then realized my expectations are broken.

File: op.c (hunk 2 above)
Comment (demerphq) [reply op.c]: sure. willdo.

**Comment by demerphq** [comment]
@tonycoz you good with the changes?

**Comment by demerphq** [comment]
Repushed with the commits squashed.

**Review by tonycoz — APPROVED** [review]
