### PR TITLE
Bugfix for `PadnameFIELDINFO` on thread cloning

### LINKED ISSUE #24150: t/class/thread.t fails on 64 bit big endian
Module:

**Description**

Since I got my smoker working again last year, I have been seeing failures in threads.t, but I only build a threaded perl for the smoker so I haven't looked at this in detail.  I'm building one now to see if I can find more detail about what is failing, but hopefully these reports help:

https://perl5.test-smoke.org/search?selected_host=perl-sparc64-stable.home.hewus.com

The most recent at the moment is:
https://perl5.test-smoke.org/report/5524935

**Steps to Reproduce**

I will see if I can follow-up with that once I get perl built not in the smoker.

**Expected behavior**

threads.t should pass its tests reliably.

**Perl configuration**

```
Automated smoke report for branch blead 5.43.8 patch 31c482381e938d6cc3aa35fa4f6b037101897c6f v5.43.7-140-g31c482381e.
perl-sparc64-stable.home.hewus.com: SPARC-T4 (rev 0.0) @ 2847.862 MHz (2847 MHz) (sparc64/12 cpus)
    on        openbsd 7.8
    using     cc version 4.2.1 20070719 (*1)
    smoketime 1 day 19 hours 20 minutes (average 5 hours 25 minutes)

Summary: FAIL(XF)

O = OK  F = Failure(s), extended report at the bottom
X = Failure(s) under TEST but not under harness
? = still running or test results not (yet) available
Build failures during:       - = unknown or N/A
c = Configure, m = make, M = make (after miniperl), t = make test-prep

v5.43.7-140-g31c482381e
----------------------- ----------------------------------------------------
X  O  O  O  O  O         (*1)
X  X  O  O  F  O        -Duseithreads (*1)
O  O  O  O  O  O        -Acppflags=-DBIG_TIME -DNO_LOCALE_NUMERIC -DNO_LOCALE_COLLATE (*1)
X  O  X  F  O  F        -Acppflags=-DBIG_TIME -DNO_LOCALE_NUMERIC -DNO_LOCALE_COLLATE -Duseithreads (*1)
|  |  |  |  |  |
|  |  |  |  |  +------  locale:UTF-8 DEBUGGING
|  |  |  |  +---------  perlio DEBUGGING
|  |  |  +------------  stdio DEBUGGING
|  |  +---------------  locale:UTF-8
|  +------------------  perlio
+---------------------  stdio




Skipped tests:
        # One test name on a line

Test failures:
  ../t/class/threads.t (FAILED No plan found in TAP output)
      [stdio/locale:UTF-8] -Acppflags=-DBIG_TIME -DNO_LOCALE_NUMERIC -DNO_LOCALE_COLLATE -Duseithreads DEBUGGING
      [perlio] -Duseithreads DEBUGGING
```

### PR DESCRIPTION
**Pull request by leonerd**
Fixes #24150

Much thanks to @nwc10 and @wolfsage on IRC who helped find this.

The change in `pad.c` is the actual bugfix. The change in `class.c` was related to debugging while I was working on it.

### CODE REVIEW

File: class.c [hunk 1]
```diff
@@ -1059,12 +1059,15 @@ Perl_class_add_field(pTHX_ HV *stash, PADNAME *pn)
...
     aux->xhv_class_next_fieldix++;
 
-    Newxz(PadnameFIELDINFO(pn), 1, struct padname_fieldinfo);
-    PadnameFLAGS(pn) |= PADNAMEf_FIELD;
+    struct padname_fieldinfo *fieldinfo;
+    Newxz(fieldinfo, 1, struct padname_fieldinfo);
+
+    fieldinfo->refcount = 1;
+    fieldinfo->fieldix = fieldix;
+    fieldinfo->fieldstash = (HV *)SvREFCNT_inc(stash);
```
Comment (Leont) [inline class.c]: `HvREFCNT_inc`?

Comment (leonerd) [reply class.c]: Good idea.

**Comment by wolfsage** [comment]
If we merge this, I think...

Both commit messages could be expanded greatly to provide context for what they are doing and why.

A test could be added to show the fix works - perhaps the original one and also https://github.com/Perl/perl5/issues/24150#issuecomment-3873170567

**Comment by leonerd** [comment]
@wolfsage I've attempted to write more in the messages, though it's not easy to imagine what is missing that the code diff itself doesn't already cover.
Also I added a copy of the test.

**Comment by wolfsage** [comment]
> @wolfsage I've attempted to write more in the messages, though it's not easy to imagine what is missing that the code diff itself doesn't already cover. Also I added a copy of the test.

Thanks, I think the diffs often have enough context for you (the author with good understanding of the code) but not me :)

For the changes to class.t, the new message makes it more clear what and why you're doing it which is helpful, I didn't see the point before.

For the changes to pad.c, the updated message is an improvement as well IMO, but could be better (but I won't ask that you change it.)

The way I like to look at commit messages is "Do they contain enough info to say what is changing and why it is changing", and imagine that you're in the middle of chasing down a problem in git blame.

"Bugfix for foo" isn't super helpful - now I have to go open up a browser and read the whole thread - and it doesn't explain the bugfix at all in git. It took a bunch of us a lot of work to track down the bug so we understand what went wrong, but:
```
- src
+ sinfo
```
lacks any of that. I can see how "Oh, clearly it was just using the wrong data", but *why* is it the wrong data could be interesting.

The bigger lack of info though is "How did this bug present itself?" which I think is good discussion for the commit message. You've included some, so I won't ask you to change it, but knowing "what did it look like when things went wrong before this change" is really good info.

*steps off soapbox*

**Comment by jkeenan** [comment]
Tests work as intended.

**Comment by afresh1** [comment]
Good news!  This seems to correct the crash on my sparc64.  However, in this branch I get this now:
```
$ ./perl harness re/pat_thr.t
re/pat_thr.t .. Failed 325/1298 subtests
        (less 55 skipped subtests: 918 okay)

Test Summary Report
-------------------
re/pat_thr.t (Wstat: 139 (Signal: SEGV, dumped core) Tests: 973 Failed: 0)
  Non-zero wait status: 139
  Parse errors: Bad plan.  You planned 1298 tests but ran 973.
Files=1, Tests=973,  5 wallclock secs ( 0.52 usr  0.04 sys +  3.41 cusr  0.80 csys =  4.77 CPU)
Result: FAIL
Finished test run at Tue Feb 10 12:45:02 2026.
```

I haven't looked further.

**Comment by jkeenan** [comment]
> Good news! This seems to correct the crash on my sparc64. However, in this branch I get this now:
> 
> ```
> $ ./perl harness re/pat_thr.t
> re/pat_thr.t .. Failed 325/1298 subtests
>         (less 55 skipped subtests: 918 okay)
> 
> Test Summary Report
> -------------------
> re/pat_thr.t (Wstat: 139 (Signal: SEGV, dumped core) Tests: 973 Failed: 0)
>   Non-zero wait status: 139
>   Parse errors: Bad plan.  You planned 1298 tests but ran 973.
> Files=1, Tests=973,  5 wallclock secs ( 0.52 usr  0.04 sys +  3.41 cusr  0.80 csys =  4.77 CPU)
> Result: FAIL
> Finished test run at Tue Feb 10 12:45:02 2026.
> ```
> 
> I haven't looked further.

Hmm, that smells oddly familiar.  IIRC it's the sort of test failure I get in memory-constrained environments where I'm attempting something like valgrind.  See:
https://perl5.test-smoke.org/submatrix?test=../t/re/pat_thr.t&pversion=5.43.8

**Comment by afresh1** [comment]
I tried cranking my ulimits and it didn't help.  This _is_ built with `-O0` and I may just not have noticed it failing on blead when I did that.  I can recompile on blead and see.

```
ok 970 - \60 works with 60 buffers 'aa'=~/...\60/
ok 971 - \60 works with 60 buffers 'aba'=~/...b\60/
ok 972 - \61 works with 61 buffers 'aa'=~/...\61/
ok 973 - \61 works with 61 buffers 'aba'=~/...b\61/
Failed 325/1298 subtests
        (less 55 skipped subtests: 918 okay)
```

**Comment by nwc10** [comment]
> Good news! This seems to correct the crash on my sparc64. However, in this branch I get this now:
> 
> ```
> $ ./perl harness re/pat_thr.t
> re/pat_thr.t .. Failed 325/1298 subtests
>         (less 55 skipped subtests: 918 okay)

> I haven't looked further.

On the Debian sparc64 machine that I have access to this test passes:

```
nick@cfarm202 t$ ./perl harness re/pat_thr.t
re/pat_thr.t .. ok
All tests successful.
Files=1, Tests=1298,  5 wallclock secs ( 0.33 usr  0.01 sys +  4.17 cusr  0.84 csys =  5.35 CPU)
Result: PASS
Finished test run at Tue Feb 10 23:49:23 2026.
nick@cfarm202 t$ uname -a
Linux cfarm202 6.17.0-rc5+ #1 SMP Fri Sep 12 20:37:32 UTC 2025 sparc64 GNU/Linux
```

so the problem you report seems either to be OpenBSD specific, or something specific to your machine (hitting `ulimit` or thread stack size? Two things to try to rule out quickly)

**Comment by afresh1** [comment]
Same issue with `re/pat_thr.t` on blead.  Likely something with my machine/setup.  Ignore that.

**Comment by leonerd** [comment]
Any comments on this bugfix? Can we merge it?

**Review by tonycoz — APPROVED** [review]
