### PR TITLE
Don't set `OPf_REF` on `OP_ANONCODE` during `op_lvalue()`

### LINKED ISSUE #20384: BBC: Blead breaks XS-Parse-Keyword, Devel-Chitin, Devel-WatchVars, others
**Description**

Starting with v5.37.4-92-g35458d36d3  tests started to fail for PEVANS/XS-Parse-Keyword-0.25.tar.gz

Sample fail reports:

- http://www.cpantesters.org/cpan/report/a7af5df2-493e-11ed-a119-5c71d9fbdcec # Solaris
- http://www.cpantesters.org/cpan/report/eb2e4352-4968-11ed-b9a4-86c3d88efda4 # Linux

Git bisect for this fail lead me to

```  text
35458d36d3c9fcf47064e4379e15276057b0bca5 is the first bad commit
commit 35458d36d3c9fcf47064e4379e15276057b0bca5
Author: Felipe Gasper <felipe@felipegasper.com>
Date:   Mon Sep 12 08:58:00 2022 -0400

    Compile anonymous subs as anoncode without srefgen.

```

**Steps to Reproduce**

cpan  -i  PEVANS/XS-Parse-Keyword-0.25.tar.gz

**Expected behavior**

Should build, test and install the pkg

**Perl configuration**

```
# perl -V output goes here
Summary of my perl5 (revision 5 version 37 subversion 5) configuration:
  Commit id: 35458d36d3c9fcf47064e4379e15276057b0bca5
  Platform:
    osname=linux
    osvers=5.19.0-2-amd64
    archname=x86_64-linux
    uname='linux k93msid 5.19.0-2-amd64 #1 smp preempt_dynamic debian 5.19.11-1 (2022-09-24) x86_64 gnulinux '
    config_args='-Dprefix=/home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.37.4-92-g35458d36d3/da1c -Dmyhostname=k93msid -Dinstallusrbinperl=n -Uversiononly -Dusedevel -des -Ui_db -Dlibswanted=cl pthread socket inet nsl gdbm dbm malloc dl ld sun m crypt sec util c cposix posix ucb BSD gdbm_compat -Uuseithreads -Uuselongdouble -DEBUGGING=-g'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2 -g'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='12.2.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/x86_64-linux-gnu/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.35'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Oct  9 2022 23:55:17
  %ENV:
    PERL5LIB=""
    PERL5OPT=""
    PERL5_CPANPLUS_IS_RUNNING="3244786"
    PERL5_CPAN_IS_RUNNING="3244786"
    PERL_CANARY_STABILITY_NOPROMPT="1"
    PERL_MM_USE_DEFAULT="1"
    PERL_USE_UNSAFE_INC="1"
  @INC:
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.37.4-92-g35458d36d3/da1c/lib/site_perl/5.37.5/x86_64-linux
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.37.4-92-g35458d36d3/da1c/lib/site_perl/5.37.5
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.37.4-92-g35458d36d3/da1c/lib/5.37.5/x86_64-linux
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.37.4-92-g35458d36d3/da1c/lib/5.37.5
    .
```

### PR DESCRIPTION
**Pull request by leonerd**
Doing so will upset XS code that manually builds optrees using `OP_REFGEN` + `OP_ANONCODE` (as would be required prior to perl 5.37.3), causing a double-reference to be generated.

(Fixes https://github.com/Perl/perl5/issues/20384 )

### CODE REVIEW

File: op.c [hunk 1]
```diff
@@ -3444,6 +3444,10 @@ Perl_op_lvalue_flags(pTHX_ OP *o, I32 type, U32 flags)
     case OP_SCALAR:
         op_lvalue(cUNOPo->op_first, OP_ENTERSUB);
         goto nomod;
+
+    case OP_ANONCODE:
+        /* We need to not set OPf_REF on this, because of GH#20384 */
```
Comment (bram-perl) [inline op.c]: Personally I don't like such comments.
I would prefer seeing something like: `because <minimal explanation of why>, see also GH#20384)`

Reading #20384 the reason isn't obvious to me
The commit message is also not crystal clear to me but it's better; *based on the commit message* I would make the comment something like: `, because doing so causes a double-reference to be generated, see ...` or something like that

(I also wonder if a test is possible/feasible..)

Comment (leonerd) [reply op.c]: > Personally I don't like such comments. I would prefer seeing something like: `because <minimal explanation of why>, see also GH#20384)`

Fair; I can expand on the reason in the comment.

> (I also wonder if a test is possible/feasible..)

A test would be possible, but only as an XS test that replicates the behaviour that older CPAN modules would perform in the same situation. For such a small code change in obscure situations like this, I wasn't sure if that would be justified.

Comment (bram-perl) [reply op.c]: > > (I also wonder if a test is possible/feasible..)
> 
> A test would be possible, but only as an XS test that replicates the behaviour that older CPAN modules would perform in the same situation. For such a small code change in obscure situations like this, I wasn't sure if that would be justified.

For me that would depend on the actual explanation in the comment;
With the current code it's somewhat unclear (to me) why the exception is needed.
And if the reason is not clear then someone else in a distant future might be tempted to remove it and see what breaks.. and if no tests breaks they may even commit it... (which may lead to BBC again)

So having a test (or I suppose sample code in the commit message) might make it clearer in which situation this exception is needed.

Comment (leonerd) [reply op.c]: A better comment is added.

**Review by tonycoz — APPROVED** [review]

**Comment by leonerd** [comment]
@bram-perl This OK for you now?

**Comment by bram-perl** [comment]
> @bram-perl This OK for you now?

LGTM

**Review by bram-perl — APPROVED** [review]
